### ISSUE TITLE
User-shared movies as new type of feature/event source?

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#104]
Some thought should be put in to making the user-shared movies a feature/event source.  The movies are not classified by solar feature/event, but do show interesting features in general.  We will need to decide on where to place pins, etc, and what to show in pop-up windows (perhaps links to the YouTube videos?).

**Comment by ddialer** [comment]
Completed. Available on beta site.

Movie markers can be enabled from "View Helioviewer Movies Shared to YouTube." -> Movies spanning observation date ->  Show in Viewport.
<img width="377" alt="screen shot 2017-03-31 at 12 45 13 pm" src="https://cloud.githubusercontent.com/assets/403007/24560246/f6cdf5d2-160f-11e7-9420-c1abbcd86e16.png">

Also, movie icons can be displayed on screenshots and generated movies. Movie icons will be automatically displayed on screenshots if they are visible on viewport. For movies, icons can be enabled inside advanced options for movie generation dialog.
<img width="331" alt="screen shot 2017-03-31 at 12 45 32 pm" src="https://cloud.githubusercontent.com/assets/403007/24560332/59cefe7e-1610-11e7-8040-6c2499493bb0.png">

**Comment by wafels** [comment]
Looks like the screenshot does not accurately reproduce the selected area.  See the attached images.

![2016_04_06_12_23_47_aia_171](https://cloud.githubusercontent.com/assets/983575/24769242/c98834c0-1ad3-11e7-9833-ca99d1bb8db0.png)

![screenshot from 2017-04-06 14 16 00](https://cloud.githubusercontent.com/assets/983575/24769277/eec078ba-1ad3-11e7-8407-1805e786f418.png)

**Comment by ddialer** [comment]
fixed
