### ISSUE TITLE
Thumbnails in image timeline broken

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#105]
Looks like the thumbnails in the image timeline are not being made. Also confirmed when a single AIA layer is present.

![screen shot 2016-04-16 at 8 03 37 am](https://cloud.githubusercontent.com/assets/983575/14580851/09a28480-03aa-11e6-8090-7ae7be5aabb0.png)

**Comment by ddialer** [comment]
Unfortunately I can't reproduce it. But looks like you had small network issue when you requested file and  browsers cached that there is no image. I added timestamp to the image url to make sure it always load new image
