### ISSUE TITLE
HMI SHARP labels not created in screenshots

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#106]
HMI SHARP labels are not appearing in screenshots, and consequently in movies.

Here is the screen grab, and what I expect:
<img width="1057" alt="screen shot 2016-04-19 at 10 41 15 pm" src="https://cloud.githubusercontent.com/assets/983575/14661979/224cda70-0680-11e6-97ab-303972ac7f3f.png">

And here is what the screenshot function returns:
![2014_04_19_23_37_36_aia_304](https://cloud.githubusercontent.com/assets/983575/14661986/2a0514f8-0680-11e6-8247-c7361060c190.png)

**Comment by ddialer** [comment]
Fixed. https://github.com/Helioviewer-Project/api/commit/cce539a77dcc3d521368889c7cdf2fdc29f62036

**Comment by wafels** [comment]
confirmed.
