### ISSUE TITLE
Helioviewer.org mash-up: low visual quality

### ISSUE THREAD

**Issue by dmueller3000** [Helioviewer-Project/helioviewer.org#107]
I have embedded a hv.org display on the Solar Orbiter web pages: http://www.cosmos.esa.int/web/solar-orbiter/

Currently, the visual quality is very low. I believe this has already been fixed once, but it looks like this somehow got lost. Could you check? Thanks a lot!

Daniel

<img width="994" alt="screen shot 2016-05-20 at 10 06 26" src="https://cloud.githubusercontent.com/assets/9073862/15421270/987befa6-1e72-11e6-8ff3-3dea500ff0ab.png">

**Comment by ddialer** [comment]
@dmueller3000, I can see that you still using API v1 to embed images. I would recommend to switch to v2 API. In your case you need to use this URL:

```
http://api.helioviewer.org/?action=takeScreenshot&date=2999-01-01T00:00:00.000Z&imageScale=4.8&layers=%5bSDO,AIA,171,1,100%5d&x1=-1228.8&y1=-1228.8&x2=1228.8&y2=1228.8&display=true
```

**Comment by dmueller3000** [comment]
Thanks, Serge - works like a charm!

Best regards,
Daniel

Dr. Daniel Mueller
Solar Orbiter Project Scientist 
European Space Agency / ESTEC (SCI-S)

P.O. Box 299, NL-2200 AG, The Netherlands
dmueller@cosmos.esa.int mailto:dmueller@cosmos.esa.int | www.esa.int http://www.esa.int/
Tel: +31 71 565 4033 | Fax: +31 71 565 4697
