### ISSUE TITLE
[event timeline] highlight events in viewer window

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#108]
The event timeline can show a lot of events.  It would be useful to use a highlight functionality similar to that already used by the feature/event selector.  When the event timeline is in histogram mode and the user hovers over a type of event, then all other events in the viewer window at the observation time are faded out.  When the event timeline is zoomed in to event-line mode and the user hovers over a particular event, then that single event is highlighted in the viewer window.

**Comment by ddialer** [comment]
Added events highlight inside the main viewport.
Note: Events will only highlight when specific event persist inside the main viewport.

**Comment by wafels** [comment]
confirmed
