### ISSUE TITLE
 [event timeline] active region class incorrectly rendered

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#109]
See screenshot

![screen shot 2016-06-20 at 11 55 10 am](https://cloud.githubusercontent.com/assets/983575/16201141/4303cf38-36de-11e6-8a61-a998f78f37b1.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
I still see the same error.

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed.
