### ISSUE TITLE
[event timeline] [image timeline] no need for logarithmic view in event-line mode

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#110]
The logarithmic view button is not needed in the event-line mode.

![screen shot 2016-06-20 at 12 10 08 pm](https://cloud.githubusercontent.com/assets/983575/16201571/09cb2f66-36e0-11e6-89db-2b1ffe4e09ff.png)

![screen shot 2016-06-20 at 12 12 14 pm](https://cloud.githubusercontent.com/assets/983575/16201634/543e8304-36e0-11e6-9938-3a0e6d6f77d3.png)

**Comment by ddialer** [comment]
Removed logarithmic view from linear views

**Comment by wafels** [comment]
confirmed, but reopening #112
