### ISSUE TITLE
[event timeline] [image timeline] highlight which timeline is being used

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#111]
It should be clearer to the user which timeline is being used.  The timeline in use should be highlighted like the tools in the top right of the application - see attached.
![screen shot 2016-06-20 at 12 15 17 pm](https://cloud.githubusercontent.com/assets/983575/16201758/c3a5c8a6-36e0-11e6-828e-fe685bf7f850.png)

**Comment by ddialer** [comment]
@wafels, I added tab highlights by inverting color for the text and background.

**Comment by wafels** [comment]
confirmed.
