### ISSUE TITLE
[event timeline] [image timeline] center / zoom buttons slightly off the bottom of the page

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#112]
The bottom segment of the center / zoom buttons are slightly off the bottom of the page - see attached.
![screen shot 2016-06-20 at 12 21 01 pm](https://cloud.githubusercontent.com/assets/983575/16201958/ae418cce-36e1-11e6-902c-990f716df4e8.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed
