### ISSUE TITLE
[event timeline] double clicking on an event jumps observation date to start of event.

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#113]
Let's say I want to jump to a particular time during an event.  Instead of the observation date jumping to where my cursor is, the observation date jumps to the start of the event.  For example, my cursor for the flare event was close to where the pop-up window was:

![screen shot 2016-06-20 at 12 20 22 pm](https://cloud.githubusercontent.com/assets/983575/16202541/0c31059c-36e4-11e6-93b0-bcdf24d1f86c.png)

but the observation date ended up here.

![screen shot 2016-06-20 at 12 20 50 pm](https://cloud.githubusercontent.com/assets/983575/16202545/13e905dc-36e4-11e6-8654-aaed85b682b7.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed
