### ISSUE TITLE
[event timeline] changing event types in the event selector does not update the event timeline

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#114]
I consider this a bug.  When a new event type is added using the event selector, the event timeline does not immediately update with the new event type.  Similarly, when removing an event type using the event selector, the event timeline does not show the change.  Changes take effect when the time is changed, either by clicking and dragging the timeline or by changing the observation time.

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed
