### ISSUE TITLE
[event timeline] why does spray surge show up when there are no spray surges?

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#115]
See attached.
![screen shot 2016-06-20 at 5 37 03 pm](https://cloud.githubusercontent.com/assets/983575/16230644/8f75ed94-3790-11e6-9c73-8a009965e237.png)
![screen shot 2016-06-20 at 5 37 17 pm](https://cloud.githubusercontent.com/assets/983575/16230643/8f74d684-3790-11e6-9f9f-32f6bfe3b06b.png)

**Comment by ddialer** [comment]
Done. now title will be hidden if there is no visible events inside the chart

**Comment by ddialer** [comment]
Compleated and released in v3.1
