### ISSUE TITLE
[event timeline] why aren't there NOAA AR detections up to the end of the day?

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#116]
NOAA active regions extend for an entire day.  In the histogram view, the NOAA active regions stop before the end of the day - see attached screen shot.
![screen shot 2016-06-21 at 9 24 16 am](https://cloud.githubusercontent.com/assets/983575/16230982/07d6f64c-3792-11e6-9a9b-154b4ead6186.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed
