### ISSUE TITLE
[event timeline] transparency over logarithmic view

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#118]
In histogram mode, the pop-up summary is transparent over the logarithmic view text, but not on any other text.  See attached.

![screen shot 2016-06-22 at 8 57 55 am](https://cloud.githubusercontent.com/assets/983575/16267380/7a9f1cde-3857-11e6-865b-afd9db33cc13.png)
![screen shot 2016-06-22 at 8 53 46 am](https://cloud.githubusercontent.com/assets/983575/16267383/7d2f6bac-3857-11e6-9969-fbb8906253dc.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
When the mouse cursor was at the left-hand end just past the last column, the transparency of the pop-up returned.

![screen shot 2016-06-22 at 5 44 22 pm](https://cloud.githubusercontent.com/assets/983575/16284815/07fc9db0-38a1-11e6-9361-28fd13a6c290.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed
