### ISSUE TITLE
[event timeline] start time is wrong

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#120]
The timeline starts at a time earlier than that shown on the header of the timeline.

![screen shot 2016-06-22 at 1 32 26 pm](https://cloud.githubusercontent.com/assets/983575/16276886/5ebeef36-387e-11e6-81e7-978c4b2024a5.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed
