### ISSUE TITLE
[event timeline] highlight events in the timeline

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#121]
I think it would be good to highlight the events in the time line that are in visible in the viewer window.  I suggest the following.  By default, all events have a black outline instead of a white outline.  Those events that are visible in viewer window have a white outline.  This gives a visual clue to the user that there are differences between events that are visible in the viewer window and others.

**Comment by ddialer** [comment]
Added events highlight for current observation date

**Comment by wafels** [comment]
I think this looks great!
