### ISSUE TITLE
[event timeline] enlarge events under the mouse

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#122]
In timeline mode, it would be good to further highlight which event is currently underneath the mouse.  This could be done by enlarging the horizontal line very slightly.  This would help the user understand which event the mouse is on.

**Comment by ddialer** [comment]
I added point highlight by making background color white. Can you please check and let me know if it looking fine. Or I still need to enlarge point in size?

**Comment by wafels** [comment]
looks good!
