### ISSUE TITLE
[event timeline] features and events not easily visible in the viewer window

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#123]
The attachment illustrates the issue.  When the mouse is used in the timeline, often the feature/event selected appears in the viewer window below a large number of semi-transparent objects, rendering it hard to read.  The selected feature/event should be brought to the top, mimicking the behavior of feature/events highlighted via the feature/event selector drawer.

![screen shot 2016-06-27 at 11 32 23 am](https://cloud.githubusercontent.com/assets/983575/16385566/55c11d4c-3c5b-11e6-909b-9f706c4939d7.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
The event under the mouse turns white on Firefox/Chrome, and so achieves the objective of making the event under the mouse more noticeable.  Confirmed as fixed.
