### ISSUE TITLE
[event timeline] emerging flux and many other feature/events types are not highlighted in the viewer window

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#124]
The attached screenshot illustrates the bug.  Although the mouse is over an emerging flux region, that region has not been highlighted in the viewer window.  Other feature and event types also have the same issue (although coronal holes and active regions seem to be ok).

![screen shot 2016-06-27 at 11 32 58 am](https://cloud.githubusercontent.com/assets/983575/16385971/f9513b76-3c5c-11e6-9487-6e3c46b90b9f.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed

**Comment by wafels** [comment]
Filament activation seems to be partially highlighted when selecting other event types - see attached:
![screen shot 2016-06-29 at 2 16 30 pm](https://cloud.githubusercontent.com/assets/983575/16464011/4c28d656-3e06-11e6-9bcd-0edcffa2e17d.png)
![screen shot 2016-06-29 at 2 16 13 pm](https://cloud.githubusercontent.com/assets/983575/16464012/4c29b2ce-3e06-11e6-8567-aa112aeb41b2.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed
