### ISSUE TITLE
Enhanced event listening across UI elements

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#125]
There are currently three different UI elements that show feature and event information - the feature/event selector, the viewer window and the feature/event timeline.  It would aid the user to locate events if there were enhanced event listening and some responsiveness across these elements.
For example, when the user mouses over the 'Active Regions' text in the Feature/event selector, everything except the active regions are highlighted in the viewer window.  This behavior could be repeated in the feature/event timeline - all events other than the active regions are faded out.  This helps the user see when the active regions are in the timeline.

Similarly, when a user mouses over an event in the viewer window, perhaps all the other events in the event timeline should fade out.

**Comment by ddialer** [comment]
Now when user mouseover on event inside main viewport it will hide all other events. This will help users to better find events based on the main viewport.

**Comment by wafels** [comment]
confirmed.
