### ISSUE TITLE
[event timeline] coronal mass ejection events have no pop-up window in timeline mode

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#126]
Coronal mass ejections (CE) do not have any associated pop-up information, or are highlighted.

![screen shot 2016-06-27 at 11 52 58 am](https://cloud.githubusercontent.com/assets/983575/16390787/7555a274-3c72-11e6-9dbf-1e1cc5c63dbb.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed
