### ISSUE TITLE
Different timescales

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#129]
A user has suggested that different timescales be implemented in the timelines.  The three timescales to be implemented are UTC (already there), Julian Date and Carrington rotation number.  A toggle would allow users to swap from one timescale to another.  The times on the y-axis would then change to reflect the selected timescale.

Some notable issues are that almost all our dates and times that we show are in UTC.  What would we do with them?  Would these also be converted over to the different time scales?

**Comment by wafels** [comment]
A compromise solution would be to allow users to change the time scale used in the observation/date selector, and then allow users to edit the time as appropriate for that time scale.  All other times in the interface would remain using UTC.  A further refinement to this would be to display a mouseover pop-up with the UTC time shown in multiple formats.

**Comment by ddialer** [comment]
Implemented new Time Converter dialog and tooltips to show different timescales in Julian Day and Carrington rotation number.
Tooltips are displayed when user mouseover "UTC" label next to the date. To open Time Converter dialog user must click on "UTC" label (applying only to the input fields: Observation Date and Request science data).

Examples of tooltips:
<img width="456" alt="screen shot 2017-05-23 at 9 42 37 am" src="https://cloud.githubusercontent.com/assets/403007/26357680/12fbd53c-3f9e-11e7-9104-e62ad64b25d4.png">
<img width="820" alt="screen shot 2017-05-23 at 9 42 48 am" src="https://cloud.githubusercontent.com/assets/403007/26357679/12e2e158-3f9e-11e7-8e35-a7a63b613d2d.png">

An example of Time Converter dialog:
<img width="596" alt="screen shot 2017-05-23 at 9 42 27 am" src="https://cloud.githubusercontent.com/assets/403007/26357695/238561e8-3f9e-11e7-9467-acf842b20f01.png">

**Comment by wafels** [comment]
Looks like the date box is not big enough - see attached
![screenshot from 2017-05-24 15 03 29](https://cloud.githubusercontent.com/assets/983575/26421006/6ca20620-4092-11e7-977c-83b41387fb82.png)

**Comment by ddialer** [comment]
Fixed
