### ISSUE TITLE
[event timeline] time ticks are wrong

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#132]
The attached image illustrates the problem.  The NOAA AR starts at 00:00, but the 00:00 time ticks are in the wrong place.

![screen shot 2016-06-28 at 8 34 11 am](https://cloud.githubusercontent.com/assets/983575/16415442/352a32b6-3d0b-11e6-9149-158e16cfcd09.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed
