### ISSUE TITLE
[event timeline] event timeline does not respond to changing feature recognition methods

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#133]
In general, removing specific feature recognition methods does not remove their presence from the timeline, in both histogram and timeline mode, except when in the case when removing a feature recognition method means that no feature recognition methods for that event type remain.  See the attached screenshots for examples of this behavior.
![screen shot 2016-06-28 at 10 32 02 am](https://cloud.githubusercontent.com/assets/983575/16420236/9794252a-3d1e-11e6-9ded-6173f3b65ad9.png)
![screen shot 2016-06-28 at 10 32 25 am](https://cloud.githubusercontent.com/assets/983575/16420239/9aa46bd0-3d1e-11e6-985b-c78cd7cf9aaa.png)
![screen shot 2016-06-28 at 10 33 59 am](https://cloud.githubusercontent.com/assets/983575/16420247/9f5a8aa6-3d1e-11e6-90f6-4ccbe8844209.png)
![screen shot 2016-06-28 at 10 34 10 am](https://cloud.githubusercontent.com/assets/983575/16420252/a27ee7ae-3d1e-11e6-9bbb-c622e14c5c22.png)

**Comment by ddialer** [comment]
Fixed.
Also, all events data is regenerated to support feature recognition names

**Comment by wafels** [comment]
confirmed.
