### ISSUE TITLE
[event timeline] HMI SHARP 5692

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#134]
According to the timeline, HMI SHARP 5692 should be plotted on the Sun.  On mouseover, nothing happens - see here:
![screen shot 2016-06-30 at 1 58 05 pm](https://cloud.githubusercontent.com/assets/983575/16500773/1672d628-3ed4-11e6-8a2a-7e426d90bcd9.png)

Also, the feature/event selector does not show an entry for HMI SHARP 5692.
![screen shot 2016-06-30 at 1 59 59 pm](https://cloud.githubusercontent.com/assets/983575/16500794/2a6ff9b2-3ed4-11e6-803d-6f2c9c32f60a.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed
