### ISSUE TITLE
New player it is not transparent.

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/helioviewer.org#137]
Because it does not help that the player prevents the view of the date of Helios viewer, you can fix it and add button for full screen?

**Comment by ddialer** [comment]
Could you please explain what you mean by "player is not transparent"? 
By player do you mean all User Interface elements that cover viewport with the sun view?

**Comment by Anthrwpos** [comment]
It does not allow to see the time during the course of the film.
![screenshot_1](https://cloud.githubusercontent.com/assets/20747347/17414687/0f414822-5a8f-11e6-850e-328eee8bff45.png)

**Comment by Anthrwpos** [comment]
Thanks for channge.
It's easy to add fullscreen button lower right the player, to see more easily the film's details?

**Comment by ddialer** [comment]
@Anthrwpos, I updated helioviewer website with a better player layout, so video controls not covering video information. Fullscreen button will be added in Helioviewer 3.1 release (should be live in the next week or two). For now, you can test Fullscreen button on the beta website (http://beta3.helioviewer.org)

**Comment by Anthrwpos** [comment]
Thank you.
But in beta version, again, the time, is not visible until press the fullscreen button.
The player in the new version will be the one that exists now (dark), or white player?

**Comment by ddialer** [comment]
The player position is corrected. And the player will be dark like on the image below:
![screen shot 2016-08-08 at 1 56 09 pm](https://cloud.githubusercontent.com/assets/403007/17517482/a370e8ce-5e11-11e6-82fc-6977cec03a69.png)

**Comment by Anthrwpos** [comment]
Thanks for the corrections.
I noticed something in the new dark player.
When full screen is performed, the bar seemed half. (Or it is only in my screen?)

![screenshot_1](https://cloud.githubusercontent.com/assets/20747347/17539926/01d44376-5ebb-11e6-89ad-105245b849a6.png)

**Comment by ddialer** [comment]
Thank You for finding the issue. Fixed already.

**Comment by ddialer** [comment]
Compleated and released in v3.1

**Comment by Anthrwpos** [comment]
Because played automatically the player, you can change the option not to play the movie automatically the player? 
It's easy?
