### ISSUE TITLE
Are the image timeline numbers being updated correctly?

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#138]
It seems that there are many days that don't have the correct number of files

![screen shot 2016-08-09 at 10 48 29 am](https://cloud.githubusercontent.com/assets/983575/17520800/08d113f8-5e1f-11e6-9c4d-ff6d530dca06.png)

If you go to http://sdowww.lmsal.com/sdomedia/hv_jp2kwrite/v0.8/jp2/AIA/2016/07/25/335/ you can see that there are many more files available, so either we didn't count them correctly or they are not on the server.

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed.
