### ISSUE TITLE
Plus/minus symbol not being shown

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#139]
There should be a plus/minus symbol between the 466 and the 8 in the feature/event pop-up.  Either use "+/-" or the proper symbol.

![screen shot 2016-08-09 at 11 05 50 am](https://cloud.githubusercontent.com/assets/983575/17521443/575a32f0-5e21-11e6-919c-cd80fb8a844e.png)
![screen shot 2016-08-09 at 11 05 40 am](https://cloud.githubusercontent.com/assets/983575/17521442/57562d4a-5e21-11e6-9a08-223a7113b8e7.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
There is one space to the left of the plus/minus sign.  Probably should remove that space, or add another on the right hand side.

**Comment by ddialer** [comment]
Done. Added space after plus/minus symbol

**Comment by wafels** [comment]
confirmed
