### ISSUE TITLE
Color tables not being applied to EIT images

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#14]
For example,

http://helioviewer.org/?date=2008-10-03T20:05:00.000Z&imageScale=4.8408818&centerX=1.936323173602295&centerY=-0.7261765895965576&imageLayers=%5BSOHO,EIT,EIT,195,1,100%5D,%5BSOHO,LASCO,C2,white-light,2,100%5D&eventLayers=&eventLabels=true

![screen shot 2015-12-02 at 10 42 58 am](https://cloud.githubusercontent.com/assets/983575/11535354/7fc1f530-98e1-11e5-8d33-ff40538ebd66.png)

**Comment by wafels** [comment]
Also present on 3.0beta

**Comment by ddialer** [comment]
Fixed

**Comment by wafels** [comment]
Tested; fix confirmed.
