### ISSUE TITLE
Emerging flux pop-up formatting issues

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#140]
(1) peak time is not being shown
(2) plus/minus sign is not being shown (after 1.2e8)
(3) superscript '2' not being displayed after 'km'

![screen shot 2016-08-09 at 11 10 14 am](https://cloud.githubusercontent.com/assets/983575/17521607/e919a3a6-5e21-11e6-80a2-3ee8a0748fdf.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed
