### ISSUE TITLE
Flare peak time not being shown in pop up

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#141]
see attached - this affects all flares regardless of feature recognition method
![screen shot 2016-08-09 at 11 21 49 am](https://cloud.githubusercontent.com/assets/983575/17522050/99794ec6-5e23-11e6-8bcc-ccb1ae3e2862.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed
