### ISSUE TITLE
Feature/event window needs to be darker

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#142]
When the full details of a feature/event are shown, the feature/event window needs to be much darker as it is almost impossible to read the text at present.  See the attached screenshot.
![screen shot 2016-08-09 at 11 24 22 am](https://cloud.githubusercontent.com/assets/983575/17522163/fe9bcd56-5e23-11e6-88c4-eaf2710133f9.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed.
