### ISSUE TITLE
Change titles of YouTube browsing capability

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#143]
The titles of the YouTube browsers should be changed as they are slightly redundant.

"Current observation date movies shared to YouTube" -> "Movies spanning observation date"
"Movies shared to YouTube" -> "Recently shared"

Any better ideas?

![screen shot 2016-08-09 at 11 41 06 am](https://cloud.githubusercontent.com/assets/983575/17522749/303ed8ce-5e26-11e6-86e9-7b0e691d67ab.png)

**Comment by ddialer** [comment]
Seems good. Already changed

**Comment by wafels** [comment]
confirmed
