### ISSUE TITLE
Increased navigation possibilities with the time-sensitive YouTube browser

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#145]
Perhaps clicking on the observation date in the time-sensitive YouTube browser should replace the viewer window at the mid-time of the YouTube movie and with the shared movie's data selections.  This does not need to be implemented right away.

**Comment by ddialer** [comment]
Done. Now when user click on 'Movies spanning observation date' video name it will set observation date to the mid-time of the movie

**Comment by wafels** [comment]
Confirmed.
