### ISSUE TITLE
Field of view of movie rotates with Sun

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#146]
Two users have suggested that helioviewer.org allow users to create movies that track features on the Sun.  This means the field of view of the data moves as the Sun rotates.  This should be possible to do given that features/events already follow solar rotation.

**Comment by wafels** [comment]
Perhaps this should be put in the current movie creation dialog.

**Comment by wafels** [comment]
Got some odd notifications when testing this feature.

![screenshot from 2017-05-04 11 45 43](https://cloud.githubusercontent.com/assets/983575/25725281/52b748ce-30ed-11e7-9fda-486ea158ec1f.png)

**Comment by wafels** [comment]
Movies are not correctly centered - see attached images.  The active region should always be in the middle of the FOV.

requested:

![screen shot 2017-05-09 at 3 04 03 pm](https://cloud.githubusercontent.com/assets/983575/25868383/7de3442c-34ca-11e7-8b58-5e8e4c1ac00a.png)

returned:
![screen shot 2017-05-09 at 3 04 36 pm](https://cloud.githubusercontent.com/assets/983575/25868390/83fce962-34ca-11e7-8f12-8f7e60073ba8.png)

**Comment by wafels** [comment]
Movies that follow solar rotation are not performing as expected.  

The request below is based on an image at 2014/05/17 21:18:41.  The selection is chosen so that the spot feature is in the middle of the field of view at 2014/05/17 21:18:41.  If the resulting movie follows solar rotation properly, then the spot should always be in the middle of the field of view.

![screenshot from 2017-05-17 14 12 04](https://cloud.githubusercontent.com/assets/983575/26169400/710eb992-3b0b-11e7-8ce6-fd4c3b68240f.png)

![screenshot from 2017-05-17 14 11 09](https://cloud.githubusercontent.com/assets/983575/26169393/6ab79c62-3b0b-11e7-8056-bb8898372a1a.png)

The movie request is for images in the time range  2014/05/16 21:18:41 -  2014/05/18 21:18:41.  Therefore the image in the viewer window is at the midway point in the movie.  The movie can be downloaded from https://helioviewer.org/?movieId=GfQh5 .  The spot feature is not in the middle of the field of view as anticipated.

In the first image in the movie, the spot feature is over to the left in the field of view.  This is not what is expected.  This implies that the field of view is over too far to the right.  Is the initial field of view at the start of the movie being rotated by the right amount (the difference between the movie start time minus viewer window time - a negative amount).

**Comment by ddialer** [comment]
Fixed. Now if current Observation date within requested movie times it will shift requested coordinates to the beginning of the video

**Comment by wafels** [comment]
Confirmed.
