### ISSUE TITLE
Extra higlighting of features and events

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#147]
When a user mouses over a particular feature/event type in the feature/event selector, those particular feature/event types are highlighted in the viewer window.  It would be good if those particular feature/event types were also highlighted in the feature/event time line.

The attached screenshot illustrates the current situation.  The mouse was over "NOAA SWPC Observer" in the feature/event selector, but the feature/event timeline still shows all of the feature events.  On mouse over, only those feature/events that have the same type and feature recognition method should be highlighted.  This will aid the user in understanding and navigating features/events and the timeline.

![screen shot 2016-08-11 at 2 57 58 pm](https://cloud.githubusercontent.com/assets/983575/17601082/66a3fe30-5fd4-11e6-9d90-e5552890d4d5.png)

**Comment by ddialer** [comment]
Done. Now when user hover mouse over one of the feature and events checkbox it will highlight all events with same type

**Comment by wafels** [comment]
confirmed as implemented.  Very useful!
