### ISSUE TITLE
Features and events that extend beyond the left hand limit are not shown

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#148]
The attached screenshot illustrates the issue.  Although the mouse is over the NOAA active region in the feature/event selector, the NOAA active regions which are on the Sun are not present in the timeline.  I know this has been noted before, but I think this has to be fixed before release because it looks like a bug to the user.  I'd expect to see these events in the timeline.  Hence the "blocks release" label.

![screen shot 2016-08-11 at 2 57 58 pm](https://cloud.githubusercontent.com/assets/983575/17601254/26849322-5fd5-11e6-806d-e03a3712dd00.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed
