### ISSUE TITLE
Hovering over feature/event in the viewer window, event not highlighted in timeline.

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#149]
I hovered over an emerging flux region in the viewer window, and it was not highlighted in the timeline.  Also applies to all other features and events

![screenshot from 2016-08-12 12 03 56](https://cloud.githubusercontent.com/assets/983575/17628829/28aecf0e-6085-11e6-8a21-8deeda175e76.png)

http://beta3.helioviewer.org/?date=2016-08-11T16:47:21.585Z&imageScale=2.42044088&centerX=-82.29498992&centerY=121.02204400000001&imageLayers=%5BSDO,AIA,94,1,100%5D&eventLayers=%5BAR,all,1%5D,%5BCC,all,1%5D,%5BCD,all,1%5D,%5BCH,all,1%5D,%5BCJ,all,1%5D,%5BCE,all,1%5D,%5BCR,all,1%5D,%5BCW,all,1%5D,%5BEF,all,1%5D,%5BER,all,1%5D,%5BFI,all,1%5D,%5BFA,all,1%5D,%5BFE,all,1%5D,%5BFL,all,1%5D,%5BLP,all,1%5D,%5BOS,all,1%5D,%5BPG,all,1%5D,%5BSG,all,1%5D,%5BSP,all,1%5D,%5BSS,all,1%5D&eventLabels=true

**Comment by ddialer** [comment]
Fixed

**Comment by wafels** [comment]
confirmed
