### ISSUE TITLE
Observable features and events are not plotted in viewer window on launch

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#150]
and they don't appear in the feature/event selector either.

![screen shot 2016-08-12 at 2 45 23 pm](https://cloud.githubusercontent.com/assets/983575/17634036/81fc2048-609e-11e6-81ca-ab5c72ce7ebe.png)

**Comment by ddialer** [comment]
Seems like I can't reproduce it. Possible was network error or previously cached js file. Is it still happening?

**Comment by ddialer** [comment]
Applied temporarily solution. 
In future, I need to reorganize "feature and events" checkbox generation and event handling
