### ISSUE TITLE
Timelines do not update when they are closed

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#152]
This issue affects both timelines.  When the timelines are closed, and the observation date changes, the timelines remain at the previous times.  The timelines should always recenter to the observation date when the observation date changes.

**Comment by ddialer** [comment]
Fixed

**Comment by wafels** [comment]
I am still able to reproduce this error.

**Comment by ddialer** [comment]
I'm sorry, forgot to compile scripts. All is done.

**Comment by wafels** [comment]
Confirmed as fixed. Thanks
