### ISSUE TITLE
Representation of zero duration events

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#155]
The HEK stores a number of zero time duration events.  These are currently not represented in the timeline.  These events are discoverable in iSolSearch, but not discoverable in helioviewer.org. We should work out a way to represent, display and interact with them through the current interface.  One idea I had for timeline mode was to indicate the time of the zero duration events with a single star, or square.  Hovering over the star would result in a pop up window which would say something like "Event type: CH, FRM: PFSS, 12 events of zero duration."  Double clicking on the star would move helioviewer.org to observation time of the zero duration events, and make them visible in the viewer window"

**Comment by wafels** [comment]
Raised the priority level as there are a large number of events that are just not being seen by our users.  For example, filaments are important to track as they can erupt.  However, many of them are stored with zero duration.  These really need to be discoverable.

For example:

http://helioviewer.org/?date=2012-09-11T06:16:22.000Z&imageScale=1.21022044&centerX=-0.04033083253417969&centerY=-0.04033083253417969&imageLayers=%5BSDO,AIA,304,1,100%5D&eventLayers=%5BAR,NOAA_SWPC_Observer,1%5D,%5BFI,all,1%5D&eventLabels=true

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed as fixed.
