### ISSUE TITLE
SSWIDL data download script has incorrect ycen

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#157]
I downloaded some data via the functionality of hv.org.  This was the state of hv.org
![screen shot 2016-09-02 at 2 05 58 pm](https://cloud.githubusercontent.com/assets/983575/18213486/8284d34c-7116-11e6-8933-6fe9407431aa.png)

This was the request reported by the LMSAL cutout service:
![screen shot 2016-09-02 at 2 05 40 pm](https://cloud.githubusercontent.com/assets/983575/18213597/ffd7f202-7116-11e6-835e-f660dcc58c09.png)

And this was the SSWIDL script generated:
![screen shot 2016-09-02 at 2 06 10 pm](https://cloud.githubusercontent.com/assets/983575/18213531/b613e34c-7116-11e6-8520-cd81881c02f0.png)

As you can see, the sign of the ycen value is wrong.  It should be negative, the same as that passed to the LMSAL cutout service.

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed
