### ISSUE TITLE
Share Link to current viewport functionality does not react to changes when it is open

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#159]
When the "Share Link to current viewport" window is open, it does not update in reaction to changes in the viewer window, like changes in scale, date and feature/events selected.  It really should change in order to reflect the exact state of helioviewer.org.

Maybe the link in the browser window should also update, like Google Maps.

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed.
