### ISSUE TITLE
Timeline: add in Carrington rotation number

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#16]
The Carrington rotation number is commonly used in the study of solar and heliospheric phenomena.  It would be useful if the Carrington rotation number was indicated on the timeline.

**Comment by ddialer** [comment]
Added Carrington rotation numbers to the timeline. CRN will be visible as plot line on the chart.

**Comment by wafels** [comment]
A couple of suggestions after using this feature.
It is not clear if the line indicates the start of a Carrington rotation, or the end of one.  I suggest a small arrow pointing to the right at the top of Carrington rotation label.  The attached image shows that I am intending with this.
![screen shot 2016-01-22 at 10 15 48 am](https://cloud.githubusercontent.com/assets/983575/12514389/25d8b8fa-c0f1-11e5-8a1c-1eab5046f9c5.png)

Also, how are the times of when an Carrington rotation starts and stops calculated?  They seem different from those listed here: http://umtof.umd.edu/pm/crn/ .  Finally, according to that table, CR 2172 ends at 2016 Jan 21 1952, and not at the time indicated in the attached image

![screen shot 2016-01-22 at 10 19 10 am](https://cloud.githubusercontent.com/assets/983575/12514665/77f1d3be-c0f2-11e5-9f42-4f01f339f72c.png)

**Comment by wafels** [comment]
Note the second image also illustrates a more extreme example of #39 .

**Comment by wafels** [comment]
Fixed - there appears to be only a few minutes difference between the online tabulated version and the version on helioviewer.org.  This is a fraction of percent.
