### ISSUE TITLE
Double clicking in event and image time line zooms in and recenters

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#160]
At the moment, double clicking in the event and image timelines when in histogram mode results in a zoom in and a recentering.  I think the functionality should be change so that on double clicking, the timelines should recenter only.  This is because the zoom and recenter happening simultaneously is somewhat unexpected.

**Comment by ddialer** [comment]
@wafels, when you double click, there are three thinks happening: changing observation date, zoom in and recenter timeline to new observation date. By "on double clicking, the timelines should recenter only" you mean keep change observation date and center it on the timeline and remove zoom in functionality from it?

**Comment by wafels** [comment]
fixed
