### ISSUE TITLE
No difference in action between Mouse wheel roll in and roll out

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#163]
Regardless if the mouse wheel rolls in or out, the timeline always zooms out.  Probably best to follow the Helioviewer viewer window usage, where a rolling the wheel away from you pushes the images away from you, corresponding to a zoom out.  Rolling the wheel towards you pulls the images towards you, corresponding to a zoom in. The timelines should act in the same way.

**Comment by wafels** [comment]
the issue seems to be confined to Firefox

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed
