### ISSUE TITLE
Full viewport thumbnails move the wrong way in the y direction

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#164]
My original view was this:

![screen shot 2016-09-13 at 11 55 10 am](https://cloud.githubusercontent.com/assets/983575/18481207/61907434-79a9-11e6-99eb-666c80b0f9b9.png)

then I moved the lower active region on the edge of the disk out of the viewer window to get this

![screen shot 2016-09-13 at 11 55 37 am](https://cloud.githubusercontent.com/assets/983575/18481234/809b2fb8-79a9-11e6-9eb8-44a908405478.png)

but the thumbnail in the cutout service drop down went the opposite way, which is the incorrect behavior.

The same thing happens using the "Select area function"  For example:

Requested area (north of the equator):

![screen shot 2016-09-13 at 12 02 10 pm](https://cloud.githubusercontent.com/assets/983575/18481378/fbf8db92-79a9-11e6-9bb0-4541c0eb3ba4.png)

Thumbnail reports the wrong area (south of the equator):

![screen shot 2016-09-13 at 12 02 20 pm](https://cloud.githubusercontent.com/assets/983575/18481388/02a9c8d4-79aa-11e6-839b-c5bacba52379.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed.
