### ISSUE TITLE
SSWIDL cutout service script enforces minimum values to fovx and fovy

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#165]
The SSWIDL cutout service script generated by helioviewer.org enforces minimum values to fovx and fovy.
I wanted the cutout to this area:

![screen shot 2016-09-19 at 10 57 36 am](https://cloud.githubusercontent.com/assets/983575/18636812/21fb3b34-7e58-11e6-80e1-97992f0a7195.png)

which came up here with a width of 53.25 arcsec and a height of 41.75 arcsec.

![screen shot 2016-09-19 at 10 57 58 am](https://cloud.githubusercontent.com/assets/983575/18636822/2a95131e-7e58-11e6-8eac-327cfa5dfe54.png)

The width value in the helioviewer drop down is equivalent to fovx in the script, and the height value in the helioviewer drop down is equivalent to fovy in the script:

![screen shot 2016-09-19 at 10 58 25 am](https://cloud.githubusercontent.com/assets/983575/18636866/53c21020-7e58-11e6-8ebc-b10db91f594d.png)

fovx and fovy should give the correct width and height values.

http://helioviewer.org/?date=2016-09-18T17:45:25.000Z&imageScale=0.60511022&centerX=-867.7280554800001&centerY=349.72344980235016&imageLayers=%5BSDO,AIA,171,1,100%5D&eventLayers=%5BAR,NOAA_SWPC_Observer,1%5D,%5BCC,all,1%5D,%5BCD,all,1%5D,%5BCJ,all,1%5D,%5BCE,all,1%5D,%5BCR,all,1%5D,%5BCW,all,1%5D,%5BER,all,1%5D,%5BFI,all,1%5D,%5BFA,all,1%5D,%5BFE,all,1%5D,%5BFL,all,1%5D,%5BLP,all,1%5D,%5BOS,all,1%5D,%5BPG,all,1%5D,%5BSG,all,1%5D,%5BSP,all,1%5D,%5BSS,all,1%5D&eventLabels=true

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed
