### ISSUE TITLE
Reducing the number of old movies on the server

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#166]
The Lead Developer has a solution that will reduce the amount of space we use to store old movies.  The idea is to have a job that deletes movies older than a certain amount of time (say, 90 days), and coupled with that, replace the age-of-movie notification on the client side with a button that allows the user to kick-off a regeneration process.  This solution is efficient of server resources, and allows the user access to their videos with a small penalty.

**Comment by ddialer** [comment]
Compleated. The solution was to keep generated images for 180 days. After 180 days movies is deleting from the server. A user is allowed to regenerate the movies by clicking on theirs names.
