### ISSUE TITLE
Screenshots and movies do not show NOAA labels correctly

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#167]
The view of helioviewer was this, and I made a screen shot including the active regions on the right.  It looks like the unicode characters are not being correctly rendered in the screenshots made by helioviewer.  Movies also show the same issue.

screen view:
![screen shot 2016-09-22 at 12 40 33 pm](https://cloud.githubusercontent.com/assets/983575/18757451/fd6361ea-80c1-11e6-89e4-ef4ade729645.png)

downloaded screenshot:
![2016_02_16_16_36_07_aia_171](https://cloud.githubusercontent.com/assets/983575/18757508/32ab4674-80c2-11e6-9adf-839385705208.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed.
