### ISSUE TITLE
Initial view of image timeline does not show any data in recent days...

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#168]
The initial view seems to show no AIA 94 data was downloaded

![screen shot 2016-10-12 at 5 20 19 pm](https://cloud.githubusercontent.com/assets/983575/19328123/4a5c8f1a-90a0-11e6-85f1-50e82b44ea72.png)

However, if you zoom in, there is data there.  The initial view does not correctly report the data we have.

**Comment by ddialer** [comment]
was fixed
