### ISSUE TITLE
Movie pop-up notification does not download movie

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#169]
When a movie has been completed, a "movie-ready" pop-up notification appears.  The notification says that you can watch or download the movie.  In older versions of helioviewer.org, clicking on the "movie-ready" pop-up notification started the movie player.  In the current version, clicking on the "movie-ready" pop-up notification does nothing.  

Clicking on the "movie-ready" pop-up notification should start the movie player.

The bug has been observed on Chrome and Firefox, but I think it is reproducible on other browsers.

**Comment by ddialer** [comment]
Fixed. Now when user click on "movie-ready" notification it will open movie player

**Comment by wafels** [comment]
confirmed
