### ISSUE TITLE
SOLAR FLARE DATA NOT DISPLAYED ON SUN

### ISSUE THREAD

**Issue by acan19** [Helioviewer-Project/helioviewer.org#170]
When using Atmospheric Imaging Assembly – Sun In Time http://sdowww.lmsal.com/suntoday_v2/index.html?suntoday_date=2014-08-01
to record solar flares, the peak time via the Helioviewer.org link has not been available for 14 October 2016, start times B5.6 03:57, B8.6 08:53, B9.4 11:02, B9.4 11:19, B8.4 11:48, B4.9 13:28, 15 October, B3.3 03:08, B3.0 04:45, B2.6 08:33, 16 October, B7.5 17:02, 17 October, B2.0 06:01.  The flare start time is displayed and the flare box ticked, but the flare start, peak and end times are not displayed on the Sun. e.g. Sun In Time B5.6  Start 2016-10-14 T03:57:00 End 2016-10-14 T04:19:00 then click on the Helioviewer.Org link to display Date: 2016/10/14 Time: 03:57:00 UTC Jump: 1  Day,  but the flare reference on the Sun is not displayed. Previously the reference on the Sun appeared immediately after switching to the Helioviewer.

**Comment by ddialer** [comment]
@acan19, fixed

**Comment by wafels** [comment]
See #171

**Comment by wafels** [comment]
I don't see the 14 October 2016, start time B5.6 03:57 flare in the database.

**Comment by ddialer** [comment]
We have it in our database. But seems there is no location for this event. Location also is not available on HEK site
<img width="373" alt="screen shot 2016-10-31 at 3 21 51 pm" src="https://cloud.githubusercontent.com/assets/403007/19868329/f22a879c-9f7d-11e6-9897-db4d065318ca.png">
