### ISSUE TITLE
SOLAR FLARES DATA NOT DISPLAYED ON SUN

### ISSUE THREAD

**Issue by acan19** [Helioviewer-Project/helioviewer.org#171]
When using Atmospheric Imaging Assembly – Sun In Time http://sdowww.lmsal.com/suntoday_v2/index.html?suntoday_date=2014-08-01
to record solar flares, the peak time via the Helioviewer.org link has not been available for 15 October 2016, start time B3.3 03:08, 16 October, B7.5 17:02, 17 October, B2.0 06:01, 24 October B1.4 12:30.   The flare start time is displayed and the flare box ticked, but the flare start, peak and end times are not displayed on the Sun. e.g. Sun In Time B3.3  Start 2016-10-15 T03:08:00 End 2016-10-15 T03:40:00 then click on the Helioviewer.Org link to display Date: 2016/10/15 Time: 03:08:00 UTC Jump: 1  Day,  but the flare reference on the Sun is not displayed. Previously the reference on the Sun appeared immediately after switching to the Helioviewer.

**Comment by ddialer** [comment]
@acan19, Fixed. The problem was on the import events script.

**Comment by wafels** [comment]
See #170
