### ISSUE TITLE
More sophisticated movie creation from helioviewer.org

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#172]
Along with #2, users have been requesting more flexibility in creating movies.  The movie generation API is capable of making a wider range of movies than is currently permitted.  Perhaps we could extend the movie creation capabilities through a "More..." link in the current movie generation dialog.  This would allow users to specify start times and end times, image cadences (up to some maximum but high level), and over/under sampling to get movies of the required dimension.  Some thought is required to decide how best ti implement more of the capability of the API.

**Comment by wafels** [comment]
The code of referenced in #136 and stored at _https://github.com/mjpauly/aia_ will be used to implement the functionality of normalizing the AIA images.  AIA 304 images will become substantially brighter.

**Comment by mjpauly** [comment]
Hi @wafels,

I've moved the rescaling data to a CSV file which you can download here: `http://lmsal.com/~pauly/aia_rescaling/aia_rescaling_data.csv` This should make it easier to implement the rescaling easily in any language. The values represent the median intensity on the disk of the sun on *almost* every day of the mission. The filtered columns are the regressions used for The Sun Today page. The CSV data goes up through June 2016. I'm currently working on making sure it gets updated every week.

Hope this helps!

**Comment by bogdanni** [comment]
@wafels : note that the scaling is performed before gamma correction/de-linearization and mapping to 8 bit data.

**Comment by wafels** [comment]
Testing on beta3.helioviewer.org - the wrong dates are being used to create the movie.  I requested that a movie be made from data in early 2015, but the movie shows the most recent data.

![screen shot 2017-01-03 at 12 11 35 pm](https://cloud.githubusercontent.com/assets/983575/21615988/d3ddda2a-d1ad-11e6-9e17-2970aecbd0e8.png)

**Comment by wafels** [comment]
I would change the "More Settings" tag to "Advanced..."
![screen shot 2017-01-10 at 11 02 07 am](https://cloud.githubusercontent.com/assets/983575/21813451/4a6bb448-d724-11e6-80a8-ea2dfd50a82b.png)

**Comment by wafels** [comment]
On beta3, the growl movie notification at the top does not launch the movie player as it should.

![screen shot 2017-01-10 at 11 03 26 am](https://cloud.githubusercontent.com/assets/983575/21813487/7250a964-d724-11e6-866c-2c8cc84fe123.png)

**Comment by wafels** [comment]
The movie pop-up information window does not report the correct pixel size.  The movie indicated here is a 4K movie.  The movie does have the correct size 3840 × 2160, but the movie pop-up information window reports the wrong size.

![screen shot 2017-01-10 at 11 15 46 am](https://cloud.githubusercontent.com/assets/983575/21814123/463a40b8-d726-11e6-87f6-f0ab6f894087.png)

**Comment by ddialer** [comment]
@wafels, all small issues is fixed: Incorrect dimensions text, click on video are ready notification, changed "More" to "Advanced"

**Comment by mjpauly** [comment]
The brightness CSV file at http://lmsal.com/~pauly/aia_rescaling/aia_rescaling_data.csv and the code at https://github.com/mjpauly/aia are both now up to date. I haven't updated the README to keep up with the current version yet, but I will soon.

**Comment by bogdanni** [comment]
@mjpauly, thanks, would it be possible to turn on compression for the LMSAL HTTP server? (i.e. reply to Accept-Encoding with Content-Encoding something like gzip). Also, would it be possible to use a format like JSON?

**Comment by mjpauly** [comment]
@bogdanni I'm actually going to switch to hosting it on the Github repo, since it will be more reliably accessible than the LMSAL server. Github probably has HTTP compression turned on already, right? I formatted the data with JSON and that file is also in the repo.

**Comment by bogdanni** [comment]
@mjpauly Github is alright. Would it be possible to get a simplified JSON with just the date and rescaling factor pairs for each wavelength? Thanks!

**Comment by mjpauly** [comment]
@bogdanni Sure. Is the file currently in the repo like what you had in mind?

**Comment by bogdanni** [comment]
JHV revision 8405 or later that can be downloaded from http://swhv.oma.be/download_test/ attempts to use this data. Currently it is shipped with the program. Much closer to the Sun In Time website, but I feel it needs like 10% more brightness. Maybe it has to do with differences for the range (dataMin, dataMax) in the JP2 processing?

@mjpauly Thanks! If you could remove the *_paths and *_raw from the JSON file, I believe the file will become quite smaller.

**Comment by bogdanni** [comment]
@mjpauly
- 94 appears to have increased response now compared with 2010
- 335 seems to need more boost
- are there corrections for 1600 & 1700?

**Comment by wafels** [comment]
Closing this issue.  The image darkening issue has its own issue at "Many of the Images Are Darker and Darker in Comparison with Previous Releases and with the SDO" #136.  Please continue the conversation there.
