### ISSUE TITLE
Formatting issue when showing image accordion with XRT data

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#173]
The attached screenshots show that the observation time bumps down one line for certain combinations of filter wheels in XRT.  The image time and the nickname / measurement combo should all be on the same line.

![screen shot 2016-11-08 at 3 53 33 pm](https://cloud.githubusercontent.com/assets/983575/20116752/8783fe06-a5cb-11e6-9211-135f591db46f.png)
![screen shot 2016-11-08 at 3 52 04 pm](https://cloud.githubusercontent.com/assets/983575/20116754/88e90048-a5cb-11e6-99b5-dcfc3405670f.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed
