### ISSUE TITLE
Allow the "any" option for XRT data

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#174]
XRT has a possible 36 filter wheel combinations.  It is easy to jump a few days or months when a particular filter wheel combination is chosen.  In order to allow users to explore the data more efficiently, we should allow another filter wheel value - "any".  This would permit any filter wheel value.  If filter wheel1 and filter wheel2 are set to "any" then this would return whichever XRT observation (of any kind) is closest to current observation time.

**Comment by wafels** [comment]
Confirmed as implemented.  The data selector, screenshots and movies respond to the changing XRT filters as expected.

**Comment by wafels** [comment]
The image timeline in beta3 does not react well to changing the filter wheel options in the image selector.  I originally selected Any/Any and then changed the filter options.  The timeline did not react.

![screen shot 2017-03-02 at 2 45 29 pm](https://cloud.githubusercontent.com/assets/983575/23524037/fc6113fa-ff56-11e6-8770-d32daa04b39c.png)

**Comment by wafels** [comment]
The SSWIDL download script should also include the ability to download XRT data.  When XRT data has been selected, please include the following code to the script.  The VSO does not allow searching based on the filter wheel locations, so the code below is valid regardless of the user's filter wheel selections.
;
; XRT data - downloadable via the VSO
;
a_xrt = vso_search(tstart, tend, instrument='XRT')
b_xrt= vso_get( a_XRT )

**Comment by ddialer** [comment]
Fixed the issue with timeline refresh on datasource change. Also added Hinode XRT to the SSWIDL download script

**Comment by wafels** [comment]
Fixed.
