### ISSUE TITLE
Adding a new image layer adds it below the existing image.

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#177]
I added an XRT image to an AIA 94 image.

![screen shot 2016-11-18 at 3 44 42 pm](https://cloud.githubusercontent.com/assets/983575/20446112/15be6d14-ada6-11e6-88fd-244f9650d1d8.png)

The XRT image is below the AIA 94 image.  The user might think that the image is not there.  Adding an image should always put the new image on top of the existing images.  New AIA images also appear below existing images.

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed. thanks!
