### ISSUE TITLE
making movie randomizes start time

### ISSUE THREAD

**Issue by andromedagirlactual** [Helioviewer-Project/helioviewer.org#178]
in a previous version of the movie making feature, one could specify exact start and end times for it
now,m it seems to do so quite randomly.
I have tried this several times now, and despite selecting a day and time for it to start [presumably the screen left control area] and selecting a time frame for it in the movie making panel, it always starts the movie way sooner than I want.
how do you control the start and end time?
it is confusing now when before it was quite simple

**Comment by ddialer** [comment]
New advanced movie generation dialog added. Allowing to control Start/End dates and movie size.
