### ISSUE TITLE
SOLAR FLARE DATA NOT DISPLAYED ON SUN

### ISSUE THREAD

**Issue by acan19** [Helioviewer-Project/helioviewer.org#179]
When using Atmospheric Imaging Assembly – Sun In Time http://sdowww.lmsal.com/suntoday_v2/index.html?suntoday_date=2014-08-01
to record solar flares, the peak time via the Helioviewer.org link has not been available for   29 December 2016, start time B1.3 20:11, 30 December, B1.0 01:30, B2.2 12:22, 31 December B2.4 01:32, B1.8 07:38.  The flare start time is displayed and the flare box ticked, but the flare start, peak and end times are not displayed on the Sun. e.g. Sun In Time B1.3  Start 2016-12-29 T20:11:00 End 2016-12-29 T20:20:00 then click on the Helioviewer.Org link to display Date: 2016/12/29 Time: 20:11:00 UTC Jump: 1  Day,  but the flare reference on the Sun is not displayed. Previously the reference on the Sun appeared immediately after switching to the Helioviewer.

**Comment by ddialer** [comment]
Fixed. Also added job to validate previous days for missing events
