### ISSUE TITLE
Thumbnails are missing

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#189]
in the "movies spanning observation date" tab.

https://helioviewer.org/?date=2017-02-28T05:54:00.000Z&imageScale=2.42044088&centerX=0&centerY=0&imageLayers=%5BSDO,AIA,304,1,100%5D&eventLayers=%5BAR,all,1%5D,%5BCC,all,1%5D,%5BCD,all,1%5D,%5BCH,all,1%5D,%5BCJ,all,1%5D,%5BCE,all,1%5D,%5BCR,all,1%5D,%5BCW,all,1%5D,%5BEF,all,1%5D,%5BER,all,1%5D,%5BFI,all,1%5D,%5BFA,all,1%5D,%5BFE,all,1%5D,%5BFL,all,1%5D,%5BLP,all,1%5D,%5BOS,all,1%5D,%5BPG,all,1%5D,%5BSG,all,1%5D,%5BSP,all,1%5D,%5BSS,all,1%5D&eventLabels=true

**Comment by ddialer** [comment]
Can't reproduce the issue. Possibly network error occurred when tried to load images
