### ISSUE TITLE
Timeline: indicated timeline range is not the same as what you get on the mouseover

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#19]
The two attached images illustrate the problem.  The range covered by the timeline is indicated in the head of the timeline.  However, when you mouseover the last histogram columns, you get different start and end times.  The range indicated in the head of the timeline should be the same as the limits  found when using the mouseover.

![screen shot 2015-12-16 at 9 29 49 am](https://cloud.githubusercontent.com/assets/983575/11848670/71b604c0-a3d8-11e5-957c-92c44ac27d16.png)
![screen shot 2015-12-16 at 9 29 25 am](https://cloud.githubusercontent.com/assets/983575/11848674/7446c88c-a3d8-11e5-8cd4-61f681d51150.png)

**Comment by wafels** [comment]
This bug has popped up again - see screenshot:

![screen shot 2016-03-10 at 9 54 15 am](https://cloud.githubusercontent.com/assets/983575/13673390/c6c48912-e6a6-11e5-97a9-4e3f37003530.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed.
