### ISSUE TITLE
Add Helioviewer.org version number to "About" dialog

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#190]
The helioviewer.org version number should be added to the About dialog.

![screen shot 2017-03-10 at 11 24 50 am](https://cloud.githubusercontent.com/assets/983575/23803375/4e0aaa76-0584-11e7-9907-e101e5057f96.png)

**Comment by wafels** [comment]
Credits should also be extended to include a new mission: Hinode (JAXA/NASA/PPARC) , which should hyperlink to this address: http://www.isas.jaxa.jp/home/solar/ , and also another institution Harvard-Smithsonian Astrophysical Observatory, which should hyperlink to: https://www.cfa.harvard.edu/ .

**Comment by ddialer** [comment]
Added version information and new credits
