### ISSUE TITLE
Polygon bounding box is clickable.

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#191]
The screenshot below illustrates the problem.  The bounding box of the coronal home polygon is clickable, meaning that it is not possible to click on any of the user movies.  The only portion that should be clickable is the pin itself and the label.  This applies to all features/events that have a polygon.
![screen shot 2017-03-21 at 12 29 05 pm](https://cloud.githubusercontent.com/assets/983575/24158205/07372f82-0e32-11e7-88ec-af0533637e89.png)

**Comment by ddialer** [comment]
Fixed

**Comment by wafels** [comment]
Confirmed!
