### ISSUE TITLE
No more data from GSFC https url 

### ISSUE THREAD

**Issue by PabloA-dev-coder** [Helioviewer-Project/helioviewer.org#193]
Hello, 

We cannot get data anymore from GSFC 
<pre>
python /var/www/helioviewer/install/downloader.py -s "2016-09-30 00:00:00"  -e "2016-10-01 00:00:00" -d gsfc_aia
Initializing HVPull
Querying time range 2016-09-30 00:00:00 - 2016-10-01 00:00:00
browsers : [<helioviewer.hvpull.browser.httpbrowser.HTTPDataBrowser instance at 0x3f79878>] 
browser : {'server': <helioviewer.hvpull.servers.gsfc_aia.GSFCDataServer_aia instance at 0x3f36368>}
(GSFC_AIA) Scanning http://helioviewer.org/jp2/AIA/2016/10/01/4500
Inside get_files(): location : http://helioviewer.org/jp2/AIA/2016/10/01/4500 extension : jp2 
toto : <function <lambda> at 0x3f7fb18> 
inside _query
location : http://helioviewer.org/jp2/AIA/2016/10/01/4500 
######Inside httpbrowser.py####
Uri to request : http://helioviewer.org/jp2/AIA/2016/10/01/4500 
urllib_version : 1.17
Traceback (most recent call last):
  File "/var/www/helioviewer/install/downloader.py", line 177, in <module>
    sys.exit(main())
  File "/var/www/helioviewer/install/downloader.py", line 65, in main
    daemon.start(args.start, args.end)
  File "/var/www/helioviewer/install/helioviewer/hvpull/net/daemon.py", line 101, in start
    self.query(starttime, endtime)
  File "/var/www/helioviewer/install/helioviewer/hvpull/net/daemon.py", line 153, in query
    matches = self.query_server(browser, starttime, endtime)
  File "/var/www/helioviewer/install/helioviewer/hvpull/net/daemon.py", line 224, in query_server
    matches = browser.get_files(directory, "jp2")
  File "/var/www/helioviewer/install/helioviewer/hvpull/browser/httpbrowser.py", line 34, in get_files
    print ("location : %s" % self._query(location))
  File "/var/www/helioviewer/install/helioviewer/hvpull/browser/httpbrowser.py", line 63, in _query
    result = url_lister.read(location)
  File "/var/www/helioviewer/install/helioviewer/hvpull/browser/httpbrowser.py", line 86, in read
    usock = urllib.urlopen(uri)
  File "/usr/lib/python2.7/urllib.py", line 86, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 207, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 358, in open_http
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 371, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 666, in http_error_301
    return self.http_error_302(url, fp, errcode, errmsg, headers, data)
  File "/usr/lib/python2.7/urllib.py", line 636, in http_error_302
    data)
  File "/usr/lib/python2.7/urllib.py", line 662, in redirect_internal
    return self.open(newurl)
  File "/usr/lib/python2.7/urllib.py", line 207, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 452, in open_https
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 375, in http_error
    return self.http_error_default(url, fp, errcode, errmsg, headers)
  File "/usr/local/lib/python2.7/dist-packages/pyfits-3.1.2-py2.7-linux-x86_64.egg/pyfits/core.py", line 135, in http_error_default
    raise IOError((errcode, errmsg, url))
IOError: (403, 'Forbidden', '//helioviewer.org/jp2/AIA/2016/10/01/4500')
Can get data anymore from GSFC 
</pre>

idem for lasco 

<pre>
root@helioviewer:/var/www/helioviewer# python /var/www/helioviewer/install/downloader.py -s "2016-09-30 00:00:00"  -e "2016-10-01 00:00:00" -d gsfc_lasco
Initializing HVPull
Querying time range 2016-09-30 00:00:00 - 2016-10-01 00:00:00
browsers : [<helioviewer.hvpull.browser.httpbrowser.HTTPDataBrowser instance at 0x383e830>] 
browser : {'server': <helioviewer.hvpull.servers.gsfc_lasco.GSFCDataServer_lasco instance at 0x37fb368>}
(GSFC) Scanning https://helioviewer.org/jp2/LASCO-C2/2016/10/01/white-light
Inside get_files(): location : https://helioviewer.org/jp2/LASCO-C2/2016/10/01/white-light extension : jp2 
toto : <function <lambda> at 0x3844b18> 
inside _query
location : https://helioviewer.org/jp2/LASCO-C2/2016/10/01/white-light 
######Inside httpbrowser.py####
Uri to request : https://helioviewer.org/jp2/LASCO-C2/2016/10/01/white-light 
urllib_version : 1.17
Traceback (most recent call last):
  File "/var/www/helioviewer/install/downloader.py", line 177, in <module>
    sys.exit(main())
  File "/var/www/helioviewer/install/downloader.py", line 65, in main
    daemon.start(args.start, args.end)
  File "/var/www/helioviewer/install/helioviewer/hvpull/net/daemon.py", line 101, in start
    self.query(starttime, endtime)
  File "/var/www/helioviewer/install/helioviewer/hvpull/net/daemon.py", line 153, in query
    matches = self.query_server(browser, starttime, endtime)
  File "/var/www/helioviewer/install/helioviewer/hvpull/net/daemon.py", line 224, in query_server
    matches = browser.get_files(directory, "jp2")
  File "/var/www/helioviewer/install/helioviewer/hvpull/browser/httpbrowser.py", line 34, in get_files
    print ("location : %s" % self._query(location))
  File "/var/www/helioviewer/install/helioviewer/hvpull/browser/httpbrowser.py", line 63, in _query
    result = url_lister.read(location)
  File "/var/www/helioviewer/install/helioviewer/hvpull/browser/httpbrowser.py", line 86, in read
    usock = urllib.urlopen(uri)
  File "/usr/lib/python2.7/urllib.py", line 86, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 207, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 452, in open_https
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 375, in http_error
    return self.http_error_default(url, fp, errcode, errmsg, headers)
  File "/usr/local/lib/python2.7/dist-packages/pyfits-3.1.2-py2.7-linux-x86_64.egg/pyfits/core.py", line 135, in http_error_default
    raise IOError((errcode, errmsg, url))
IOError: (403, 'Forbidden', '//helioviewer.org/jp2/LASCO-C2/2016/10/01/white-light')
</pre>

I have investigated a lot and found out that we have that problem at IAS since 2013-09-30 
Python2.7 & urllib seems to have some issue with 'https'  
If i use JSOC it is ok (http:///jsoc.stanford.edu/data/aia/images...)
So hopefully we have aia data  

<pre>
root@helioviewer:/var/www/helioviewer# python /var/www/helioviewer/install/downloader.py -s "2016-09-30 00:00:00"  -e "2016-10-01 00:00:00" -d jsoc
Initializing HVPull
Querying time range 2016-09-30 00:00:00 - 2016-10-01 00:00:00
browsers : [<helioviewer.hvpull.browser.httpbrowser.HTTPDataBrowser instance at 0x462b8c0>] 
browser : {'server': <helioviewer.hvpull.servers.jsoc.JSOCDataServer instance at 0x45e9368>}
(JSOC) Scanning http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500
Inside get_files(): location : http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500 extension : jp2 
toto : <function <lambda> at 0x4631b90> 
inside _query
location : http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500 
######Inside httpbrowser.py####
Uri to request : http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500 
urllib_version : 1.17
usock : <addinfourl at 75731528 whose fp = <socket._fileobject object at 0x48353d0>> 
urls : 
['?C=N;O=D', '?C=M;O=A', '?C=S;O=A', '?C=D;O=A', '/data/aia/images/2016/10/01/', '2016_10_01__00_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__01_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__02_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__03_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__04_00_06_69__SDO_AIA_AIA_4500.jp2', '2016_10_01__05_00_06_69__SDO_AIA_AIA_4500.jp2', '2016_10_01__06_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__07_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__08_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__09_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__10_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__11_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__12_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__13_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__14_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__15_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__16_00_06_69__SDO_AIA_AIA_4500.jp2', '2016_10_01__17_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__18_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__19_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__20_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__22_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__23_00_06_68__SDO_AIA_AIA_4500.jp2'] 
result : ['?C=N;O=D', '?C=M;O=A', '?C=S;O=A', '?C=D;O=A', '/data/aia/images/2016/10/01/', '2016_10_01__00_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__01_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__02_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__03_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__04_00_06_69__SDO_AIA_AIA_4500.jp2', '2016_10_01__05_00_06_69__SDO_AIA_AIA_4500.jp2', '2016_10_01__06_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__07_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__08_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__09_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__10_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__11_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__12_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__13_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__14_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__15_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__16_00_06_69__SDO_AIA_AIA_4500.jp2', '2016_10_01__17_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__18_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__19_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__20_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__22_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__23_00_06_68__SDO_AIA_AIA_4500.jp2']
location : ['http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__00_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__01_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__02_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__03_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__04_00_06_69__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__05_00_06_69__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__06_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__07_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__08_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__09_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__10_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__11_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__12_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__13_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__14_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__15_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__16_00_06_69__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__17_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__18_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__19_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__20_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__22_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__23_00_06_68__SDO_AIA_AIA_4500.jp2']
inside _query
location : http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500 
######Inside httpbrowser.py####
Uri to request : http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500 
urllib_version : 1.17
usock : <addinfourl at 75731456 whose fp = <socket._fileobject object at 0x48355d0>> 
urls : 
['?C=N;O=D', '?C=M;O=A', '?C=S;O=A', '?C=D;O=A', '/data/aia/images/2016/10/01/', '2016_10_01__00_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__01_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__02_00_06_68__SDO_AIA_AIA_4500.jp2', '2016_10_01__03_00_06_68__SDO_AIA_AIA_4500.jp2', 
(...)
files : ['http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__00_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__01_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__02_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__03_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__04_00_06_69__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__05_00_06_69__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__06_00_06_68__SDO_AIA_AIA_4500.jp2', 'http://jsoc.stanford.edu/data/aia/images/2016/10/01/4500/2016_10_01__07_00_06_68__SDO_AIA_AIA_4500.jp2', 
(...)
</pre>

in python 3 it is ok if I do the following 

<pre>

~/SitoolsClient/python/github/master/pySitools2_1.0`` [dev-pablo|✚ 3…2] 
18:01 $ ipython3
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
Type "copyright", "credits" or "license" for more information.
IPython 1.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
In [1]: import urllib3
In [2]: url="https://helioviewer.org/jp2/LASCO-C2/2016/10/01/white-light"
In [3]:  http = urllib3.PoolManager()
In [4]: r = http.request('GET', url)
In [6]: print (r.__dict__)
{'reason': 'OK', '_connection': False, '_decoder': None, 'version': 11, 'headers': {'content-length': '32650', 'vary': 'Accept-Encoding', 'date': 'Wed, 22 Mar 2017 17:03:27 GMT', 'strict-transport-security': 'max-age=31536000;', 'content-type': 'text/html;charset=UTF-8', 'server': 'Apache'}, '_fp': <http.client.HTTPResponse object at 0x7f13535dc5f8>, 'decode_content': True, 'status': 200, '_original_response': <http.client.HTTPResponse object at 0x7f13535dc5f8>, 'strict': 0, '_body': b'
(...)
</pre>

We will upgrade our server helioviewer.ias.u-psud.fr soon but if you have a quick solution for us  for lasco we are interested. 

NB :
 I needed to find out where was the problem so you see some of my comments in 
install/helioviewer/hvpull/net/daemon.py
install/helioviewer/hvpull/browser/httpbrowser.py
/usr/lib/python2.7/urllib.py

Best Regards, 
Pablo

**Comment by ddialer** [comment]
@MedocIAS, could you try it again. I changed some apache configs that my resolve this issue.

**Comment by PabloA-dev-coder** [comment]
Hello
I have just tried 

<pre>
root@helioviewer:/var/www/helioviewer# python /var/www/helioviewer/install/downloader.py -s "2016-09-30 00:00:00"  -e "2016-10-01 00:00:00" -d gsfc_lasco
Initializing HVPull
Querying time range 2016-09-30 00:00:00 - 2016-10-01 00:00:00
(GSFC) Scanning https://helioviewer.org/jp2/LASCO-C2/2016/10/01/white-light
404 error No files 
(GSFC) Scanning https://helioviewer.org/jp2/LASCO-C3/2016/10/01/white-light
404 error No files 
(GSFC) Scanning https://helioviewer.org/jp2/LASCO-C2/2016/09/30/white-light
404 error No files 
(GSFC) Scanning https://helioviewer.org/jp2/LASCO-C3/2016/09/30/white-light
404 error No files 
Found no new files.
Sleeping for 3 minutes.
</pre>

try that you will figured out the problem with python2 

import urllib 
url="https://helioviewer.org/jp2/LASCO-C2/2016/10/01/white-light"
usock =urllib.urlopen(url)
print usock.__dict__

=> 403 error 

nb :
python3 is working but I dont' want to rewrite completely download.py I prefer spend time on the upgrade of  the server ...

Best regards, 
Pablo

**Comment by PabloA-dev-coder** [comment]
I have removed my dirty comments in install/helioviewer/hvpull/net/daemon.py 
install/helioviewer/hvpull/browser/httpbrowser.py
/usr/lib/python2.7/urllib.py

**Comment by ddialer** [comment]
I just tried on my computer and it is working and returning list of files:
```
import urllib
url="https://helioviewer.org/jp2/LASCO-C2/2016/10/01/white-light"
usock =urllib.urlopen(url)
print usock.read()
```

**Comment by ddialer** [comment]
Also, https://github.com/Helioviewer-Project/api downloader script already updated to support python 3.5

**Comment by PabloA-dev-coder** [comment]
Have you test with Python2.7 from outside ? 
Because if you test from inside of gsfc it seems normal that you don't reproduce ...
In addition that this code is in production at IAS for years now and we only have the problem for a few months....
We are currenlty pulling aia data at jsoc but if you could help us for lasco it  would be great

**Comment by PabloA-dev-coder** [comment]
The same command gives at IAS 

<pre>
root@helioviewer:/var/www/helioviewer/install# ipython 
Python 2.7.3 (default, Jun 21 2016, 18:38:19) 
Type "copyright", "credits" or "license" for more information.

IPython 0.13.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import urllib

In [2]: url="https://helioviewer.org/jp2/LASCO-C2/2016/10/01/white-light"

In [3]: usock =urllib.urlopen(url)

In [4]: print usock.read()
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /jp2/LASCO-C2/2016/10/01/white-light
on this server.</p>
</body></html>
In [5]: print urllib.__version__
1.17


</pre>

**Comment by ddialer** [comment]
@MedocIAS, tried two different locations outside of GSFC and its working:
```

[root@8fqz-z8sn ~]# python
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib
>>> url="https://helioviewer.org/jp2/LASCO-C2/2016/10/01/white-light"
>>> usock =urllib.urlopen(url)
>>> print usock.read()
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
 <head>
  <title>Index of /jp2/LASCO-C2/2016/10/01/white-light</title>
 </head>
 <body>
<h1>Index of /jp2/LASCO-C2/2016/10/01/white-light</h1>
  <table>
   <tr><th valign="top"><img src="/icons/blank.gif" alt="[ICO]"></th><th><a href="?C=N;O=D">Name</a></th><th><a href="?C=M;O=A">Last modified</a></th><th><a href="?C=S;O=A">Size</a></th><th><a href="?C=D;O=A">Description</a></th></tr>
   <tr><th colspan="5"><hr></th></tr>
<tr><td valign="top"><img src="/icons/back.gif" alt="[PARENTDIR]"></td><td><a href="/jp2/LASCO-C2/2016/10/01/">Parent Directory</a></td><td>&nbsp;</td><td align="right">  - </td><td>&nbsp;</td></tr>
...

>>> print urllib.__version__
1.17
>>> 

```

May be your server is using cached version http://stackoverflow.com/questions/16210233/urllib-urlopen-returns-an-old-page ?

**Comment by PabloA-dev-coder** [comment]
no cache used, bug in python 2.7.3 I think 
with python python 2.7.9 it is ok on our test server 

<pre>
root@dev-helioviewer:/home/palinger# ipython
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
Type "copyright", "credits" or "license" for more information.

IPython 2.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import urllib

In [2]: url="https://helioviewer.org/jp2/LASCO-C2/2016/10/01/white-light"

In [3]:  usock =urllib.urlopen(url)

In [4]: print usock.code
200

</pre>

Test in progress ..
We will update our prod server
