### ISSUE TITLE
Mouseover in feature/event timeline header

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#194]
On mouseover the different feature/event types in the feature/event header (pictured below), the feature/event type that was moused-over should highlight that feature/event type in the timeline and the view window.  This makes it much easier to understand which event types are which in the timeline.

![screenshot from 2017-03-28 14 48 57](https://cloud.githubusercontent.com/assets/983575/24421912/b4518aee-13c5-11e7-9c5f-8249e2321765.png)

**Comment by ddialer** [comment]
Done. Onmouseover over timeline legend item it will highlight selected series including main view window

**Comment by wafels** [comment]
confirmed.
