### ISSUE TITLE
4k x 4k movies

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#2]
NASA now has a 4k TV channel.  It would be good if the Helioviewer Project could create 4k by 4k movies.  Possible enhancements to the source images include radial filtering/enhancement, PSF de-convolution and wavelet filtering.  These enhancements would have to be applied to the JPEG2000 images.

**Comment by wafels** [comment]
This is liable to be a computationally expensive operation.  Perhaps a queuing system could manage this, along with a relatively low priority assigned to this processing.

**Comment by wafels** [comment]
Another user has asked for 4k by 4k movies.

**Comment by Nschanche** [comment]
If specifying during export an image width and height of 4096x4096, will JHelioviewer export the full resolution images or a compressed version that is rebinned to give an image with the larger dimensions?

**Comment by bogdanni** [comment]
@Nschanche : although not the authors, we believe that is correct (full resolution) for JHelioviewer 2.2 and earlier.

**Comment by wafels** [comment]
closed via #172
