### ISSUE TITLE
Hinode image type not reported correctly

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#202]
In the image timeline, the Hinode image type is not correctly reported when an "Any" option is selected, both in the pop-up and in the image header.  The image selector was set to "Any Any" - the image selector choices should be replicated properly in the timelines.

![screenshot from 2017-05-19 11 48 29](https://cloud.githubusercontent.com/assets/983575/26256075/c0ad0132-3c89-11e7-8705-1b9e2127bf14.png)

**Comment by ddialer** [comment]
Fixed

**Comment by wafels** [comment]
confirmed.
