### ISSUE TITLE
Feature/event timeline labels react to mouseover?

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#203]
The feature/event timeline labels

![screenshot from 2017-05-19 12 09 20](https://cloud.githubusercontent.com/assets/983575/26256771/01cd2758-3c8c-11e7-98c9-f3e4883bdda8.png)

have to be clicked to react.  It might be more useful to have them react to mouseover instead of click.  In addition, the reaction on mouseover should change.  When mousing over a feature/event timeline label, only those features/events should appear in the viewer window and in the timeline.  The other feature/events should disappear.

**Comment by ddialer** [comment]
Done. Onmouseover over timeline legend item it will highlight selected series

**Comment by wafels** [comment]
Confirmed.
