### ISSUE TITLE
Image timeline labels to react to mouseover?

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#204]
The image timeline labels

![screenshot from 2017-05-19 12 16 56](https://cloud.githubusercontent.com/assets/983575/26257064/22c09ade-3c8d-11e7-87af-485b844bb8ab.png)

have to be clicked in order to do something.  I think it would be better if the labels reacted to mouseover.  On mouseover all other image types would disappear from the image timeline

**Comment by ddialer** [comment]
Done. Onmouseover over timeline legend item it will highlight selected series

**Comment by wafels** [comment]
Confirmed.
