### ISSUE TITLE
Documentation how to install helioviewer server 

### ISSUE THREAD

**Issue by PabloA-dev-coder** [Helioviewer-Project/helioviewer.org#205]
Hello, 
Can I have more explantation on the documentation README.txt  concerning the installation of the server helioviewer.org please ?

see https://github.com/Helioviewer-Project/helioviewer.org  :
"    
INSTALLATION:

Instructions for installing Helioviewer.org are available online at
http://wiki.helioviewer.org/wiki/index.php?title=Installing_Helioviewer.org
"
But the link leads to : 
There is currently no text in this page. You can search for this page title in other pages, or search the related logs. 

I am trying to install helivoviewer.org from scratch  how to do that ? 
I was expecting "git clone url_something"  to get last version ...

Best regards, 
Pablo 
IAS

**Comment by ddialer** [comment]
Hello @MedocIAS ,
I fixed installation link in readme file. Correct link is http://wiki.helioviewer.org/wiki/Installing_Helioviewer.org

Let me know if you have any other questions

**Comment by PabloA-dev-coder** [comment]
Hello, 
http://wiki.helioviewer.org/wiki/Installing_Helioviewer.org is the former wiki to install the old version we are already running here at IAS, isn't it ?

Are you sure that doc is up to date to download & install last version of helioviewer.org ?

Have a look on the "Downloading"  section :
"
 Downloading

The source-code for Helioviewer.org is hosted on Launchpad and can be downloaded using the Bazaar version control tool. After downloading and installing bazaar, use the following command to fetch the latest version of Helioviewer's source-code:

 bzr branch lp:helioviewer.org

Once you have finished downloading the source-code, place the entire directory contents or the directory itself within your web server's root directory (e.g. /var/www/). You can ignore any warning messages that show up relating to a Launchpad ID, it isn't necessary to be logged in to retrieve a branch from Launchpad. 
"

Why do I have to use bzr, everything is on git,  isn't it ?
I was expecting something like "git clone url_address" 
Can you please confirm that are the steps we have to follow to install last version of helioviewer.org ?

Regards, 
Pablo

**Comment by PabloA-dev-coder** [comment]
I am currently trying the repository "https://github.com/Helioviewer-Project/helioviewer.org_trunk_branch_from_bzr.git " 
is that correct ?

there is also https://github.com/Helioviewer-Project/helioviewer.org.git 

I don't know which one I should take but as I don't see install directory in the second one I assume I have to take the first one. Can you please tell me how should I use  ' https://github.com/Helioviewer-Project/helioviewer.org.git ' ?

**Comment by ddialer** [comment]
Yes, you are right, documentation is outdated and we will update it in next few days. 

Currently, Helioviewer project is hosted here on GitHub. And separated into two separate repositories API (https://github.com/Helioviewer-Project/api) and HTML Client (https://github.com/Helioviewer-Project/helioviewer.org). 

The API have the same structure and have an install folder, and you can use documentation from wiki to complete the installation. 

HTML Client can be installed in any directory and you just need to change config at the end of index.php file.

Also if you have any other questions about installation you can contact me directly at serge.zahniy@nasa.gov

**Comment by PabloA-dev-coder** [comment]
Thank you 
I will contact you directyl if I have more questions 

Best regards, 
Pablo
