### ISSUE TITLE
[ISSUE] Helioviewer 'output=embed'

### ISSUE THREAD

**Issue by guanjiwang2016** [Helioviewer-Project/helioviewer.org#206]
Hello,
I am Guanji, I work with Pablo at IAS.
I would like to interrogate helioviewer.org with the parameter 'output=embed', the current result differs from the old version used at IAS.

old:
http://helioviewer.ias.u-psud.fr/helioviewer/index.php?date=2017-05-18T17:00:53.000Z&imageScale=4.8&centerX=4.8&centerY=0&imageLayers=%5BSDO,AIA,AIA,304,1,100%5D&output=embed

new : 
https://helioviewer.org/index.php?date=2017-05-18T17:00:53.000Z&imageScale=4.8&centerX=4.8&centerY=0&imageLayers=%5bSDO,AIA,AIA,304,1,100%5d&output=embed

output=embed is not taken into account in the newest version. 

see 
![selection_267](https://cloud.githubusercontent.com/assets/16957363/26498597/d7ee3c0c-422f-11e7-86cf-24a36cd4c4ec.jpg)

![selection_266](https://cloud.githubusercontent.com/assets/16957363/26498598/d7ef7cca-422f-11e7-8639-7dc004ce5960.jpg)

https://helioviewer.org/index.php?date=2017-05-18T17:00:53.000Z&imageScale=4.8&centerX=4.8&centerY=0&imageLayers=%5bSDO,AIA,AIA,304,1,100%5d&output=embedhttps://helioviewer.org/index.php?date=2017-05-18T17:00:53.000Z&imageScale=4.8&centerX=4.8&centerY=0&imageLayers=%5bSDO,AIA,AIA,304,1,100%5d&output=embed

Would it be possible to re implement output=embed please in the newest version ?

Thank you.
Regards,
Guanji

**Comment by ddialer** [comment]
Hello Guanji,
Now you can use output=embed option. Everything should work the same way as before.
