### ISSUE TITLE
directory carbon is missing

### ISSUE THREAD

**Issue by PabloA-dev-coder** [Helioviewer-Project/helioviewer.org#207]
Hello, 

Trying to go to inf-helio-test.ias.u-psud.fr I have got in apache error.log :

172.18.60.172 - - [29/May/2017:11:03:10 +0200] "GET /helioviewer/resources/images/carbon/carbonBG3L.png HTTP/1.1" 404 558 "http://inf-helio-test.ias.u-psud.fr/helioviewer/resources/compressed/helioviewer.min.css?v=1495806299" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0"

The directory 'carbon' is missing and I don't see it on git https://github.com/Helioviewer-Project/helioviewer.org either 

Best regards, 
Pablo 
IAS

**Comment by ddialer** [comment]
You just need to rebuild minified versions of helioviewer.min.css and helioviewer.min.js using Apache Ant (http://ant.apache.org/).

Just navigate to helioviewer/resources/build directory and execute command "ant"

**Comment by PabloA-dev-coder** [comment]
Hello, 
execution of the command 'ant' has been done .
I still have the same issue : 
carbonBG3L.png is not found

see screenshot : 
![carbonbg3l](https://user-images.githubusercontent.com/3584929/27534682-2af10f10-5a68-11e7-8dc4-f128b566643d.jpg)

looking for the ref 
<pre>
root@dev-helioviewer:/var/www/helioviewer# grep -R carbonBG3L.png * --exclude-dir jp2 
api/resources/css/carbon.css:html {background: black url(../images/carbon/carbonBG3L.png) repeat-x;}
resources/css/carbon.css:html {background: black url(../images/carbon/carbonBG3L.png) repeat-x;}
resources/compressed/helioviewer.css:html {background: black url(../images/carbon/carbonBG3L.png) repeat-x;}
(...)
</pre>

**Comment by PabloA-dev-coder** [comment]
Workaround found 
Edit those 2 files 
resources/css/carbon.css
resources/compressed/helioviewer.css

Replace 
<pre>
images/carbon/carbonBG3L.png
</pre>
by 
<pre>
images/LEGACY/carbon/carbonBG3L.png
</pre>
