### ISSUE TITLE
Missing events on launch

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#209]
When launching helioviewer.org with events selected, events that should be visible on the disk are not seen.  See the screen shot below.

![screen shot 2017-06-09 at 7 44 03 am](https://user-images.githubusercontent.com/983575/26974023-73029f00-4ce7-11e7-9e9f-98c5782c6df9.png)

On launch, helioviewer.org goes to the most recent image data based on the current time.  However, the events that are present at the current time are not shown.

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
Confirmed!
