### ISSUE TITLE
New day boundaries when hh:mm times are present in timelines.

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#212]
It would be useful to have the date - YYYY/MM/DD - indicated at 00:00.  This would give the user a better idea of what time they are looking at. I think a vertical line at 00:00 with a label YYYY/MM/DD would be best, formatted distinctly from the Carrington rotation and the observation date/time.

![screenshot from 2017-06-19 13 41 13](https://user-images.githubusercontent.com/983575/27298092-5bce7910-54f5-11e7-8838-ea3129c0c42e.png)
![screenshot from 2017-06-19 13 40 48](https://user-images.githubusercontent.com/983575/27298097-60bf7c1c-54f5-11e7-9ebd-5ce79ae948a0.png)

**Comment by ddialer** [comment]
completed
