### ISSUE TITLE
Helioviewer.org on mobile platforms.

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#213]
A user has suggested that helioviewer.org be optimized for mobile usage, such as mobile phones and tablet computers.  This will extend the number and type of devices that helioviewer.org can be used on usefully.

**Comment by wafels** [comment]
A responsive helioviewer.org will be released as helioviewer 4.0.

**Comment by btaylor-sesda** [comment]
First official release was deployed. :-)
