### ISSUE TITLE
ReferenceError: TimeSelector is not defined 

### ISSUE THREAD

**Issue by PabloA-dev-coder** [Helioviewer-Project/helioviewer.org#214]
Hello, 

I am trying to install helioviewer.org on my test server at IAS inf-helio-test.ias.u-psud.fr
Although I do have the file TimeSelector.js I have an error in firebug saying  "TimeSelector is not defined"

<pre>
 root@dev-helioviewer:/var/www/helioviewer# find . -name TimeSelector.js
./resources/js/UI/TimeSelector.js
</pre>

In index.php this file seems to be loaded : 
<pre>
<script src="resources/js/UI/TimeSelector.js?v=<?=$debugTime?>" type="text/javascript"></script>
</pre>

Do you have a clue about that ? 

Best regards, 
Pablo

**Comment by ddialer** [comment]
Could you replace content of /resources/build/build.xml file with https://github.com/Helioviewer-Project/helioviewer.org/blob/master/resources/build/build.xml

I just made some changes. There was missing TimeSelector reference.

**Comment by PabloA-dev-coder** [comment]
Hello, 

Done.
Sorry to bother but I ve tried to launch 'ant '
<pre>
root@inf-helio-test:/var/www/helioviewer/resources/build# ant
Buildfile: /var/www/helioviewer/resources/build/build.xml

BUILD FAILED
/var/www/helioviewer/resources/build/build.xml:8: Unexpected element "{}html" {antlib:org.apache.tools.ant}html

Total time: 0 seconds
</pre>

Best regards, 
Pablo 
IAS

**Comment by PabloA-dev-coder** [comment]
solved my fault doing a wget 
Solved thank you
