### ISSUE TITLE
No data since 2017-06-28 on helioviewer.org/jp2

### ISSUE THREAD

**Issue by PabloA-dev-coder** [Helioviewer-Project/helioviewer.org#215]
Hello,

I have just tested image ingestion and I don't find recent jp2  
on https://helioviewer.org/jp2/AIA/2017/06/  the last day where there are data is 2017-06-28

<pre>
root@inf-helio-test:/var/www/api/install/helioviewer/hvpull/servers#  python /var/www/api/install/downloader.py -s "2017-07-05 14:00:00" -e "2017-07-05 17:00:00" -d gsfc
WARNING: AstropyDeprecationWarning: Config parameter 'name_resolve_timeout' in section [coordinates.name_resolve] of the file '/root/.astropy/config/astropy.cfg' is deprecated. Use 'remote_timeout' in section [utils.data] instead. [astropy.config.configuration]
WARNING: AstropyDeprecationWarning: Config parameter 'remote_timeout' in section [utils.data] of the file '/root/.astropy/config/astropy.cfg' is given by more than one alias (astropy.utils.data.remote_timeout, coordinates.name_resolve.name_resolve_timeout). Using the first. [astropy.config.configuration]
WARNING: AstropyDeprecationWarning: astropy.utils.compat.odict.OrderedDict is now deprecated - import OrderedDict from the collections module instead [astropy.utils.compat.odict]
Initializing HVPull
Querying time range 2017-07-05 14:00:00 - 2017-07-05 17:00:00
(GSFC) Scanning http://helioviewer.org/jp2/AIA/2017/07/05/4500
(GSFC) Scanning http://helioviewer.org/jp2/AIA/2017/07/05/304
(GSFC) Scanning http://helioviewer.org/jp2/AIA/2017/07/05/171
(GSFC) Scanning http://helioviewer.org/jp2/AIA/2017/07/05/1600
(GSFC) Scanning http://helioviewer.org/jp2/AIA/2017/07/05/1700
(GSFC) Scanning http://helioviewer.org/jp2/AIA/2017/07/05/193
(GSFC) Scanning http://helioviewer.org/jp2/AIA/2017/07/05/211
(GSFC) Scanning http://helioviewer.org/jp2/AIA/2017/07/05/335
(GSFC) Scanning http://helioviewer.org/jp2/AIA/2017/07/05/131
(GSFC) Scanning http://helioviewer.org/jp2/AIA/2017/07/05/94
(GSFC) Scanning http://helioviewer.org/jp2/HMI/2017/07/05/continuum
(GSFC) Scanning http://helioviewer.org/jp2/HMI/2017/07/05/magnetogram
Found no new files.
Sleeping for 3 minutes.
</pre>

But the helioviewer.org shows data for 304 for today 2017-07-05 so I don't understand .

Best regards, 
Pablo 
IAS

**Comment by ddialer** [comment]
fixed
