### ISSUE TITLE
Problem with displaying image in Helioviewer

### ISSUE THREAD

**Issue by Hard2017** [Helioviewer-Project/helioviewer.org#217]
I have just come back to the Helioviewer.Org website after a break of a few weeks . I find that it won't display an image of the sun for the current time ( or in the past) for any observatory / instrument or measurement . I am using a MacBook Pro running on MacOsSierra(10.12.4) . Any help with this would be much appreciated

**Comment by solargeek** [comment]
I'm having the same issue. No main image when using Firefox or Google Chrome on Windows 10 since yesterday.

**Comment by ddialer** [comment]
Hello,
Thank you for submitting the ticket. We a working on a solution. Full functionality should be restored shortly.

**Comment by ddialer** [comment]
Problem with displaying images fixed. Helioviewer back to normal functionality. 
Sorry for any inconvenience.
