### ISSUE TITLE
Planets as seen from SOHO

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#218]
It should be possible to calculate the locations of planets in the LASCO C2 and C3 fields of view.  This can probably be calculated using a combination of spiceypy, the position of SOHO and sunpy.  It is probably calculable using SSWIDL.  These need only be calculated once and can be stored in a table somewhere.  This information can then be used to label planets in LASCO C2 and C3 field of view.

An extension of this would be to calculate the position of planets in STEREO COR1 and COR2

**Comment by bogdanni** [comment]
Please use https://github.com/Helioviewer-Project/GeometryService
There is an instance running out of swhv.oma.be.

**Comment by bogdanni** [comment]
Demo: http://swhv.oma.be/demo/euhforia.mov

**Comment by wafels** [comment]
See also https://github.com/Helioviewer-Project/hvorgobjects

**Comment by wafels** [comment]
Just to record the idea, we could have forward and backwards buttons for each planet that move the observation time to the next and previous transit for that planet.
