### ISSUE TITLE
Move difference selector to be below measurement

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#220]
The newly implemented difference selector is right below the opacity slider.  After using helioviewer for so long, it is too easy to mistakenly click on the difference selector when intending "Observatory".  The difference selector should be below the final selector so users - including me - are not confused.

![screen shot 2017-09-12 at 3 06 05 pm](https://user-images.githubusercontent.com/983575/30343469-ba56c528-97cb-11e7-86e7-a92f6e228aca.png)

**Comment by ddialer** [comment]
Done. Difference selector moved below measurement dropboxes.

**Comment by wafels** [comment]
confirmed and thanks!
