### ISSUE TITLE
Simple modes for helioviewer

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#223]
Helioviewer presents a lot of options to the user.  One thing we could do is provide simple modes that define which data is shown, the FOV and the features/events.  For example, one mode could show LASCO C2, LASCO C3, a disk image and coronal mass ejection/eruption information.  Another mode could show magnetograms, active region information and flares.  Other modes could show the views from STEREO A and STEREO B.  Another mode could show the high temperature Sun - Hinode, RHESSI and AIA 94 data.  We could also allow users to define their own modes, simply by pressing a button that records their selections and prompts them to provide a name for it.

**Comment by wafels** [comment]
Here are four suggested presets,

(a) name of presets
(b) source data
(c) features and events

1
(a) NOAA flares and active regions
(b) AIA 171
(c) Active Regions > NOAA SWPC AR Observer , Flares > SWPC

2
(a) Eruption Monitor
(b) AIA 304 / LASCO C2 / LASCO C3
(c) Filaments , Filament Eruptions , Filament Activation , Eruptions , Coronal Mass Ejections , Sigmoids

3
(a) Magnetic flux Monitor
(b) HMI magnetogram
(c) Sunspots / Emerging Flux

4
(a) Coronal hole Monitor
(b) AIA 211
(c) Coronal holes

**Comment by wafels** [comment]
I think the icon for the presets should show the pop-up menu on mouse-over.

**Comment by ddialer** [comment]
completed. but not on the production site. the button to open simple modes is commented. Just need to fix popup window overflow styles

**Comment by wafels** [comment]
Now implemented on the main website
