### ISSUE TITLE
Drop down menus have same background colour as text

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#224]
A user has reported that the text and background color of the drop down menus in his version of Firefox have the same color.  This means the text cannot be read.
![bug-helioviewer](https://user-images.githubusercontent.com/983575/30746136-b9e95288-9f76-11e7-8f43-2d19bbf1f645.gif)

**Comment by ddialer** [comment]
@wafels, Should be fixed. But his Firefox version can help me to double check it.

**Comment by wafels** [comment]
Firefox 55.0.3 and Windows7 64bit

**Comment by ddialer** [comment]
Fixed
