### ISSUE TITLE
For simplified versions of hv.org: automated switching of sources depending on request time

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#225]
There are HV sources which are approximately equivalent in terms of the part of the atmosphere they serve, but were operational in different time ranges.  For example, EIT 304 and AIA 304.  It is worthwhile to automatically switch between these sources for simplified websites.  Here are the equivalents

earlier / later / switch over time
EIT 304 / AIA 304 / 2010/07/30
EIT 171 / AIA 171 / 2010/07/30
EIT 195 / AIA 193 / 2010/07/30
MDI continuum / HMI continuum / 2011/01/21
MDI magnetogram / HMI magnetogram / 2011/01/21

**Comment by ddialer** [comment]
done

**Comment by wafels** [comment]
Fully implemented.
