### ISSUE TITLE
Difference (Running difference) is ko on IAS test server 

### ISSUE THREAD

**Issue by PabloA-dev-coder** [Helioviewer-Project/helioviewer.org#231]
Hello, 
We would like to implement the difference capability on our test server inf-helio-test.ias.u-psud.fr

We have the last helioviewer , last api, last esajpip from git 
Is there something to configure somewhere ?
I don't see any error in log files (apache, helioviewer or api)  ...

for ex :
https://inf-helio-test-api.ias.u-psud.fr/?action=getTile&id=2320934&imageScale=2.42044088&x=0&y=0&difference=1&diffCount=1&diffTime=2&baseDiffTime=2018-02-09T09%3A16%3A21.000Z returns a black square 

It does work with jhelioviewer with 
web_root_url     = https://inf-helio-test-api.ias.u-psud.fr
jp2_root_url     = https://inf-helio-test.ias.u-psud.fr/jp2
jpip_root_url    = jpip://inf-helio-test.ias.u-psud.fr:8080
client_url       = https://inf-helio-test-api.ias.u-psud.fr

Best regards, 
Pablo 
IAS

**Comment by wafels** [comment]
This appears to be working now on IAS, so closing for now.
