### ISSUE TITLE
Glossary embedded YouTube videos don't play

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#232]
Helioviewer.org Youtube embed links that are in the glossary don't work anymore.  We need to follow the YouTube instructions for embedding YouTube videos in the glossary

**Comment by dgarciabriseno** [comment]
Fixed in 59b66b4d7d5acd0b384a444e7f161a2bdabc1e84 and cherry-picked on helioviewer.org
