### ISSUE TITLE
the layer ("Difference") not change with the first chance

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/helioviewer.org#233]
My example: https://imgur.com/a/OJgzz
Is it just me or does it happen to you?

**Comment by wafels** [comment]
I don't understand what you mean.  The image looks like a difference image.  What is the issue?  Does the difference image not change as expected?

**Comment by Anthrwpos** [comment]
When i'm on the SDO AIA 304 and i change the layer from "No Difference" to "Running difference" , the 304 layer doesn't change directly, need to change the Measurement first and then it's ok to see another layer except 304.
I tried with Mozilla and Opera, but it's the same.
What browser you use?

**Comment by wafels** [comment]
Confirmed.  Thanks for the bug report.  This will be worked on in the next few weeks.

**Comment by wafels** [comment]
See also #234

**Comment by Helioviewer-Kirill** [comment]
Fixed. Thanks!
