### ISSUE TITLE
the layer ("Difference") not change with the first chance (2) - STEREO-A, COR2

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/helioviewer.org#234]
GIF example: https://i.imgur.com/F2gqjat.gifv

**Comment by wafels** [comment]
So, you changed to a running difference image and nothing happened to the image on screen?  I do not encounter this problem using helioviewer.org

**Comment by Anthrwpos** [comment]
"So, you changed to a running difference image and nothing happened to the image on screen?"
Yes, until i choose "NEWEST" to change the layer, like it has a bug and the selection "NEWEST" is an instant update.
I don't know why.
You use Chrome?

**Comment by Anthrwpos** [comment]
?

**Comment by Anthrwpos** [comment]
Sorry, but no answer 9 day later?

**Comment by Anthrwpos** [comment]
Still no answer?

**Comment by wafels** [comment]
Confirmed this bug.  This will be worked on in the next few weeks.

**Comment by wafels** [comment]
See #233 also.

**Comment by Helioviewer-Kirill** [comment]
Fixed. Thanks for reporting this issue!
