### ISSUE TITLE
Weird Thing Happened on Helioviewer

### ISSUE THREAD

**Issue by samjhunt** [Helioviewer-Project/helioviewer.org#235]
So I was looking at some CMEs and active regions on Helioviewer. Specifically looking at the Sun on 28th March 2018 when I noticed this:
https://youtu.be/ax91dDsmHxA

Does anybody know why this happened or what is happening?
Can't stop laughing

**Comment by wafels** [comment]
On March 28th the Solar Dynamics Observatory rotated in order to do some testing.  You can read about it here : http://sdoisgo.blogspot.com/2018/03/on-orbit-testing-of-sdo-march-28april.html

**Comment by samjhunt** [comment]
Fab, thank you!
