### ISSUE TITLE
Feature/event pop up window on right hand side makes it difficult to mouseover events

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#238]
See attached screenshot.  When a user selects an event close to the right hand side of the feature/event timeline the pop-up window makes it difficult to select other events at that part of the timeline.  This is caused by the pop-up window popping up under the cursor and not to its left, as it should (there is enough space between mouse pointer and pop-up window when the pop-up appears to the right of the mouse pointer).

<img width="1231" alt="screen shot 2018-05-16 at 7 43 41 am" src="https://user-images.githubusercontent.com/983575/40114987-ea903e2c-58dc-11e8-813d-ce2e723ac6f6.png">

**Comment by Helioviewer-Kirill** [comment]
Fixed. Thanks!
