### ISSUE TITLE
Timeline: mouse wheel zoom in/out

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#24]
When using the mouse wheel to zoom in and out, the timeline currently zooms in/out to the center of the time range shown.  It is more intuitive to zoom in/out based on where the mouse pointer is in the timeline.

**Comment by ddialer** [comment]
Implemented intuitive zoom in/out base on mouse pointer location

**Comment by wafels** [comment]
fixed
