### ISSUE TITLE
Wrong number of images reported at daily bin sizes for a recent period of time

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#240]
If you look at the image timeline for AIA 171, there is definitely something wrong about how the system is calculating the number of images we have.  In the period indicated in the image below, if you zoom out on the timeline until each histogram bin is one day then you get only 400 images per day roughly.  
![screen shot 2018-06-26 at 10 57 43 am](https://user-images.githubusercontent.com/983575/41921076-068b346a-7930-11e8-8cde-9bf0521f74b8.png)

But if you zoom in to an hourly level you get about 100 images/hour for each hour in the day, which is more like what we expect.  
![screen shot 2018-06-26 at 10 58 04 am](https://user-images.githubusercontent.com/983575/41921094-1311ebfc-7930-11e8-92c7-ba4ab5bb8153.png)

Therefore we should have 2400 images at the one day level.  There must be an error in how some of the statistics at different bin sizes are being calculated.

**Comment by Helioviewer-Kirill** [comment]
Fixed. Thanks!
