### ISSUE TITLE
"Earth Scale" window starts underneath the right sidebar

### ISSUE THREAD

**Issue by brennan-pilcher** [Helioviewer-Project/helioviewer.org#241]
When you open Helioviewer for the first time, the "Earth Scale" window is partially hidden underneath the right sidebar.

macOS 10.13.4
Chrome Version 67.0.3396.99 (Official Build) (64-bit)

![screen shot 2018-07-06 at 10 10 07 am](https://user-images.githubusercontent.com/19158259/42383641-cb454110-8105-11e8-9e1d-e0c8d7e13f76.png)

**Comment by Helioviewer-Kirill** [comment]
Fixed. Thanks!
