### ISSUE TITLE
After completing the Interactive Tutorial, it does not dismiss the modal until you refresh

### ISSUE THREAD

**Issue by brennan-pilcher** [Helioviewer-Project/helioviewer.org#242]
When you first open Helioviewer, you are prompted to complete the Interactive Tutorial. If you go through all the steps and complete the tutorial, the original prompt does not go away until you refresh the page.

macOS 10.13.4
Chrome Version 67.0.3396.99 (Official Build) (64-bit)

Video: [https://streamable.com/m2wtq](https://streamable.com/m2wtq)

**Comment by Helioviewer-Kirill** [comment]
Fixed. Thanks!
