### ISSUE TITLE
Searching arXiv

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#243]
It should be possible to click on NOAA active region labels and search for that NOAA AR number on arXiv.  It did not work for me today. Perhaps the search API has changed?

**Comment by Helioviewer-Kirill** [comment]
Fixed on https://beta3.helioviewer.org

**Comment by wafels** [comment]
This seems not to work, in that the query does not return any results when it should.  A good test example is to use NOAA 10486.  There should be a large number of results.  If you go to arXiv.org and do a search for NOAA 10486 then there are a lot of results.  These results should be available.

**Comment by Helioviewer-Kirill** [comment]
Thanks. I took a look and I was missing an additional url parameter. I've adjusted the search and the events which contain relevant entries now show up when you click search on arXiv. 

For example try NOAA 12192 [located on the bottom right of this viewport](https://beta3.helioviewer.org/?date=2014-10-26T13:29:09.000Z&imageScale=2.42044088&centerX=-56.88036068&centerY=12.102204400000002&imageLayers=%5BSDO,AIA,171,1,100,0,60,1,2018-07-23T09:25:20.000Z.000Z%5D&eventLayers=%5BAR,NOAA_SWPC_Observer,1%5D&eventLabels=true)

However, it would appear that not every NOAA event observation has an arXiv record. There are only 546 articles that contain the term "NOAA" on arXiv. The search link now works as expected, but arXiv may not contain a record of a paper/abstract which mentions a specific event by number. This is the case if you try any of the other NOAA events located in the viewport link provided above.

**Comment by wafels** [comment]
I think choosing the full text option for arXiv makes more sense.  When I do this on arXiv.org I get 101 papers, which is much more along the lines for this famous active region (some active regions are famous! among solar physicists anyway ;) )

**Comment by Helioviewer-Kirill** [comment]
After contacting the admins at arXiv on 08/13/18 about the internal server error when searching for certain events in "full text" mode, I was informed by Jake Weiskoff that the full text search is an experimental feature. Jake also assisted me in fixing another bug related to searching for HMI SHARP. This fix uses standard search for both NOAA active regions and HMI SHARP on arXiv. Since "full text" search is experimental with an unclear timeline, it should not be used on helioviewer.
