### ISSUE TITLE
ArXiv and ADS search for HMI SHARP

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#245]
Active region HMI SHARP numbers should be searchable on arXiv and ADS, just the same as we do for NOAA AR numbers.  See the attached screenshots.

![screen shot 2018-08-10 at 1 37 09 pm](https://user-images.githubusercontent.com/983575/43972561-c01cd8a8-9ca2-11e8-8c20-bd7e853818a1.png)
![screen shot 2018-08-10 at 1 38 07 pm](https://user-images.githubusercontent.com/983575/43972563-c188550a-9ca2-11e8-9dd2-d576bdcf7fa2.png)

**Comment by Helioviewer-Kirill** [comment]
Added to https://beta3.helioviewer.org
