### ISSUE TITLE
Parker Solar Probe as seen from Earth

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#246]
It would be useful to create a new UI element that allows users to plot the location of the Parker Solar Probe (PSP) as seen from Earth in the viewer window.  This will need knowledge of the PSP orbit, its projection as seen from Earth, plotting in the viewer window, plotting in screenshots, and plotting in movies.

**Comment by wafels** [comment]
See also #218.

**Comment by wafels** [comment]
Eventually this will be supported by https://github.com/Helioviewer-Project/hvorgobjects

**Comment by wafels** [comment]
Initial support in  https://github.com/Helioviewer-Project/hvorgobjects has been committed.

**Comment by wafels** [comment]
Each Parker Solar Probe encounter should be labelled with the "encounter number".  This will help people understand which encounter they are a looking at. For example, for encounter number 12 the pop-ups and mouseovers should have a line that says "Encounter 12"
![Screen Shot 2019-03-22 at 11 15 23 AM](https://user-images.githubusercontent.com/983575/54833117-d9d48d80-4c93-11e9-9678-8fa060e2f312.png)

![Screen Shot 2019-03-22 at 11 16 45 AM](https://user-images.githubusercontent.com/983575/54833272-29b35480-4c94-11e9-9338-03c8b2279049.png)

**Comment by Helioviewer-Kirill** [comment]
The encounter number is a great idea and will provide great visual feedback to the user. 
Could we add this to the PSP dataset as a new field for each timestep?
Such as ```"encounter" : 12```

**Comment by wafels** [comment]
Yes, that works.  I will adapt the code to count encounters.  I will also generalize this so that we can allow for different names, as we may want to count all kinds of transits.  So maybe one field of `trajectory_name` and another one of `trajectory_count`.  So for PSP we can have `trajectory_name: "encounter"` and for planetary transits `trajectory_name: "transit"`

**Comment by wafels** [comment]
Closing this issue since the PSP trajectory code is now operational
