### ISSUE TITLE
Few SDO data since 2018-09-04

### ISSUE THREAD

**Issue by PabloA-dev-coder** [Helioviewer-Project/helioviewer.org#247]
Hello, 
On helioviewer.org they are very few SDO data available are from 2018-09-04 until 2018-09-10.
Do you have difficulties to produce jp2 files ? 

Best regards,
Pablo 
IAS

**Comment by ebuchlin** [comment]
Seems to be solved now... (at least at the GSFC helioviewer.org, we still have to catch up). However there are several other periods where the number of AIA images in the image timeline is suspiciously low, like 2016-05-27 to 2016-06-05 in all wavelengths, while there are AIA data. Is there a systematic search for data gaps?
