### ISSUE TITLE
Corrupted images from SDO in HMI continuum spectrum

### ISSUE THREAD

**Issue by fliker09** [Helioviewer-Project/helioviewer.org#248]
The problem appeared on 23rd of September and extends to current day:

https://screenshots.firefox.com/bMArUculm6Yhglu5/www.helioviewer.org

**Comment by wafels** [comment]
Thanks for the report.  We'll take a look and see what's going on.

**Comment by wafels** [comment]
There was only one corrupted image.  New images are now available.
