### ISSUE TITLE
What are the time ranges for warning about late data on the status page for KCor?

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#259]
KCor (as of now) is showing red on the [status page](https://api.helioviewer.org/status/).  What are the time ranges for triggering red?  I would suggest the following time ranges:

yellow - more than one day
orange - more than 3 days
red - more than 7 days

This accommodates the fact that KCor is ground based.

**Comment by Helioviewer-Kirill** [comment]
Time ranges are bespoke to the individual detector.
Default value for triggering red is 12 hrs.
I've implemented your desired time ranges for COSMO Kcor.
