### ISSUE TITLE
Missing AIA 171 data

### ISSUE THREAD

**Issue by shessweb** [Helioviewer-Project/helioviewer.org#260]
There is a data gap in the AIA 171 channel data from 2015-Jul-15 12:00 through 2015-Jul-17 00:00, although the data are available in the JSOC database and seem fine at a cursory glance. The other wavelength channels have data available during that period, albeit fewer observations than normal.

**Comment by wafels** [comment]
Confirmed.  Looks like all files from 2015-Jul-16 AIA 171 is completely missing.

**Comment by Helioviewer-Kirill** [comment]
I have backfilled this time range to catch up with the data available from JSOC.
Thanks for the report.

**Comment by wafels** [comment]
Confirmed as fixed. Thanks for the report and the fix!
