### ISSUE TITLE
Broken links when Data download window is set to open, then revisited later

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#261]
I went to helioviewer.org, opened up the data download window, summary images appeared as expected, then closed helioviewer.org (destroyed the tab), then re-opened again.  The links to the summary images were broken.

<img width="1409" alt="Screen Shot 2019-07-30 at 5 56 52 PM" src="https://user-images.githubusercontent.com/983575/62168539-c72e2d00-b2f3-11e9-9698-95dff5cad311.png">

**Comment by Helioviewer-Kirill** [comment]
Fixed

**Comment by wafels** [comment]
Confirmed
