### ISSUE TITLE
"About helioviewer.org"

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#263]
Should include a reference to SunPy in the section "Helioviewer.org makes use of the following tools"
[SunPy](sunpy.org) - Python-based solar physics software
<img width="511" alt="Screen Shot 2019-08-19 at 4 17 30 PM" src="https://user-images.githubusercontent.com/983575/63296586-729c2300-c29d-11e9-8cfa-e93faffc5089.png">

**Comment by btaylor-sesda** [comment]
This appears to be resolved.
