### ISSUE TITLE
Why don't you have a patreon?!!

### ISSUE THREAD

**Issue by mirabehnn** [Helioviewer-Project/helioviewer.org#264]
Thank you for making this! I use this site a LOT, and would love to support you, but there is no link to do so. Can you make a patreon so we can help you continue development or at least help pay for site hosting?

**Comment by wafels** [comment]
Thank you for the expression of support, but we are unable to accept donations.  The Helioviewer Project is supported by funding from ESA and NASA.

The best way to support helioviewer.org is to continue to use it, and to let us know how we can make it better.  We are always interested in user feedback.

If you don't mind, could you share how you use Helioviewer?

Thanks,

Jack

**Comment by mirabehnn** [comment]
I am fascinated with plasma and heliophysics, and so I use the helioviewer site to get a closer look at interesting solar events. I share what I find on youtube, facebook, and twitter together with academic papers that describe what is happening on the day. 

Thank you for making the site so easy to use. I would say that the only thing that may be an issue is the persistent caching, since sometimes when I go from movie mode to picture mode, or vice versa, it doesn't work until I refresh the page.
