### ISSUE TITLE
STEREO-A and SOHO

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/helioviewer.org#266]
Hi, why these images don't have any updates for almost 2 months?
I read [this](http://blog.helioviewer.org/2019/09/09/delay-to-lasco-c2-and-c3-images/), with STEREO-A, is the same? Thanks

**Comment by Helioviewer-Kirill** [comment]
We apologize for the delay to SOHO LASCO and STEREO-A images caused by an issue in the conversion pipeline.
We hope to restore service as quickly as possible, but are currently unable to give an estimate.
Thank you for your patience as we work on a fix to resolve this issue.

**Comment by Anthrwpos** [comment]
Just curious, thanks for update.

**Comment by wireeye** [comment]
Almost 2020 now and  SOHO LASCO and STEREO-A images has not updated since November. Can't this issue be resolved?
