### ISSUE TITLE
Typo in User Guide 3.1.0

### ISSUE THREAD

**Issue by Derflinger-Bruce** [Helioviewer-Project/helioviewer.org#267]
You have a typo; Events spelled Evetns

Helioviewer.org User Guide 3.1.0
Getting to Know Helioviewer.org
Elements of Helioviewer.org
Panel 12 - Events Timeline
third paragraph: Events Timeline Navigation
You have Events spelled Evetns - you might want to check and correct that

**Comment by wafels** [comment]
User guide will be re-written - see #324
