### ISSUE TITLE
Images lag behind SDO Sun Now web.

### ISSUE THREAD

**Issue by simplio** [Helioviewer-Project/helioviewer.org#268]
There is a serious lag in time especially with tha AIA 171 and AIA 304 images. All others are delayed. Very cumbersome for this web service.

**Comment by simplio** [comment]
Helioviewer.org is behind 6 hours.

**Comment by Helioviewer-Kirill** [comment]
Thanks for your report. We've investigated this issue and resolved it.
Images on Helioviewer should be much more up to date.
