### ISSUE TITLE
helioviewer.org is open but can't create a movie

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/helioviewer.org#273]
helioviewer.org is open but can't create a movie, why?

**Comment by ebuchlin** [comment]
Hello, could you be more specific? Which instance of the helioviewer.org app, what have you tried to do, what happened? Is the movie marked as "Queued" in the list? I just tested on https://helioviewer.ias.u-psud.fr/ and movies can be created.

**Comment by wireeye** [comment]
Thanks for your reply, I just seen your email and went directly to Helioviewer web page and LASCO C2 & C3 are still  not updating from 11/13/2019 15:31:42 UTC. and stereo-A cor2 is still showing 11/10/2019 both of these  when you click the newest button function won't update to the latest images. All other filters will update to present day.
