### ISSUE TITLE
Helioviewer Behing Current SDO Images

### ISSUE THREAD

**Issue by simplio** [Helioviewer-Project/helioviewer.org#274]
Last images from SDO on Helioviewer is at 12/06/2019 23:59 GMT at 055GMT 12/7/2019. Latest SDO Images from SDO Sun Now is at that time 11:45 GMT 12/7/2019. You're 5 hours behind. This is a reoccurring issue every month.

**Comment by simplio** [comment]
Again, here it is March 16 2020. Helioviewer is 3 days behind showing data from March 13 2020. Why is this happening? A nice active region moving over the Northeast limb right now in SDO The sun now webpage. Please fix helioviewer.

**Comment by wafels** [comment]
Fixed.
