### ISSUE TITLE
SOHO, LASCO 

### ISSUE THREAD

**Issue by wireeye** [Helioviewer-Project/helioviewer.org#275]
Good day to you, I was wondering if SOHO, LASCO is ever going to be fixed it has not been updated since Nov. 2019 it is now Jan. 5th 2020.
Thanks for your time in advance.

**Comment by wafels** [comment]
Many apologies for the lack of SOHO LASCO data.  SOHO LASCO data will return.  We are still implementing the fix.

**Comment by wafels** [comment]
Images are back.  Apologies again for the delay.
