### ISSUE TITLE
Helioviewer Queue Issue & Mobile optimization

### ISSUE THREAD

**Issue by simplio** [Helioviewer-Project/helioviewer.org#277]
I tap on ok to create movie then it stays in queue despite it saying 3 minutes to make a movie. This is using Chrome on Android latest version updated from Play Store. Also please optimize it for mobiles because trying to expand the sun by two finger method doesn't work. We have to use the zoom -/+ buttons. Needs alot of work or make a new Android app version of Jhelioviewer please. Old Helios just doesn't cut it.

Thanks
Simplio
Oklahoma

**Comment by wafels** [comment]
We are planning on making version 4.0 of helioviewer.org fully responsive.
