### ISSUE TITLE
Minimum movie length is 10s, despite field decription says 5-100s

### ISSUE THREAD

**Issue by helioshk** [Helioviewer-Project/helioviewer.org#284]
When defining a movie duration of less than 10s, the movie will be 10s long.
(tried it with HMI continuum)

**Comment by dgarciabriseno** [comment]
Not a bug anymore. I'm able to create 5 second videos.
![image](https://user-images.githubusercontent.com/94071409/147778831-cdd56884-b341-4feb-abd2-97c33c477e37.png)
