### ISSUE TITLE
Carrington rotation in the time step selector

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#286]
A user has pointed out that helioviewer.org has a 28 day time step selection, but not one that is one solar rotation.  The standard for a solar rotation is the mean synodic Carrington rotation time, 27.2752612 days.  The option of stepping by this time step should be included in helioviewer.org

**Comment by wafels** [comment]
This is equivalent to  2356582.56768 seconds (=27.2752612*24*60*60).  A good label for it in the drop-down is "Carrington rotation" and it should be selectable between the "1 week" and "28 days" options.

**Comment by Helioviewer-Kirill** [comment]
Feature Added to [Helioviewer.org](https://helioviewer.org)
