### ISSUE TITLE
STEREO-B COR2 images not showing

### ISSUE THREAD

**Issue by johan12345** [Helioviewer-Project/helioviewer.org#288]
Hi, I have noticed that STEREO-B COR2 images don't seem to work at the moment. The web interface simply does not display the image, the API response looks like this:

```
{"error":"Unable to process XML Header for \/var\/www\/api.helioviewer.org\/docroot\/jp2\/COR2-B\/2014\/05\/13\/white-light\/2014_05_13__13_39_28_096__STEREO-B_SECCHI_COR2_white-light.jp2: File does not exist.  Check cache directory permissions.","errno":13}
```

**Comment by Helioviewer-Kirill** [comment]
Hi, 
Thanks for bringing this issue to our attention.
It seems you have uncovered a larger issue with COR2-B data availability and we have disabled this data source on helioviewer for now. 
We're working on re-generating these images.

**Comment by johan12345** [comment]
Thanks!

**Comment by Helioviewer-Kirill** [comment]
We've re-generated all STEREO-B COR2 images and they are now available on [https://www.Helioviewer.org](https://www.Helioviewer.org)!

**Comment by johan12345** [comment]
Indeed, COR2-B works now. Thank you!
