### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by wireeye** [Helioviewer-Project/helioviewer.org#289]
Question, I noticed that the LASCO C3 hasn't updated since Nov. 5th. Why is that?  Thank you for your time in advance.

![Screenshot_2020-12-06 Helioviewer org](https://user-images.githubusercontent.com/35879228/101283666-e40d2700-37a9-11eb-9390-f03568693317.png)

**Comment by wafels** [comment]
Recent data is available now.
