### ISSUE TITLE
No display?

### ISSUE THREAD

**Issue by sdaval** [Helioviewer-Project/helioviewer.org#291]
I may just be an idiot, but I have been trying to use this tool for a lesson today and cannot get anything to display within the program. It was working fine when I tested the tool yesterday, my only guess is that servers are down.
![HVissue](https://user-images.githubusercontent.com/78810027/107389762-ad5ed000-6abc-11eb-9ef1-4b5a7e386796.png)

**Comment by wireeye** [comment]
It isn't working on my computer either. On https://sohowww.nascom.nasa.gov/data/Theater/  website there isn't a problem with making movies with their tools. So maybe https://www.helioviewer.org/ is just updating.

**Comment by ebuchlin** [comment]
The people responsible of the site are aware of the problem and are trying to solve it. In the meantime, you can try https://helioviewer.ias.u-psud.fr/ , we have (normally) a full mirror of the GSFC data. Known issues: HEK queries and Youtube movie upload don't work.
