### ISSUE TITLE
from the https://helioviewer.ias.u-psud.fr/ , cant upload videos

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/helioviewer.org#292]
Hi, from this site https://helioviewer.ias.u-psud.fr/, i cant upload videos, it shows error:

"Authorization error
Error 400: redirect_uri_mismatch
The redirect URI in the request, https://helioviewer-api.ias.u-psud.fr/?action=uploadMovieToYouTube&html=true, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/${your_client_id}?project=${your_project_number}"

any solution? thanks

**Comment by Anthrwpos** [comment]
why from the specific website, cannot upload movies?

**Comment by ebuchlin** [comment]
Video upload to YouTube should work now, however Google imposes these videos to remain private (it is impossible to share them). There is some procedure we need to do with Google. @GSFC, any advice on this? (see #270).

**Comment by dgarciabriseno** [comment]
We don't plan to update the youtube process as it stands. Users who can upload already will be able to upload. Users who can't upload will have to manually download and upload to youtube.
