### ISSUE TITLE
No images

### ISSUE THREAD

**Issue by wireeye** [Helioviewer-Project/helioviewer.org#293]
https://www.helioviewer.org/  isn't showing any images, none of the satellite filters show an image. SDO, SOHO, stereo-A and so on. is there a bug still not fixed?
![Screenshot_2021-02-16 Helioviewer org](https://user-images.githubusercontent.com/35879228/108108512-b4f31b80-705e-11eb-83d5-6703a6573b86.png)

**Comment by wafels** [comment]
Recent solar images should now be available.  Apologies for the delay in getting our services back up and running.
