### ISSUE TITLE
Images but can't make movie

### ISSUE THREAD

**Issue by wireeye** [Helioviewer-Project/helioviewer.org#294]
Greetings, I had written before about Helioviewer no showing images, That problem is fixed now, But the moviemaker is unable to make movies now. After selecting the desired time frame it will start loading for a few seconds then say "We are unable to create in the  time  you requested. Please select a different time range and try again. (max number of clients reached) The image timeline shows there are images for those dates. I'll send two screen captures for you to view to help explain what I'm talking about
![Screenshot_2021-02-18 Helioviewer org(1)](https://user-images.githubusercontent.com/35879228/108419394-74cb9e80-7200-11eb-892a-0ba012e8cc5a.png)
![Screenshot_2021-02-18 Helioviewer org](https://user-images.githubusercontent.com/35879228/108419401-75fccb80-7200-11eb-8e3f-f680cd83800b.png)

**Comment by wafels** [comment]
Apologies for the issues with Helioviewer.org in the past few days.  I believe that movie creation is now working again.  Please let us know if the issues continue.
