### ISSUE TITLE
Sorry, still not able to create movie

### ISSUE THREAD

**Issue by wireeye** [Helioviewer-Project/helioviewer.org#295]
Greetings, The problem still lingers. I am getting the same message as before. I have made many movies for about five or six years, so I know I am doing the right procedure and yet the movie creator won't create a movie. I am sending the screen shot. 
![Screenshot_2021-02-19 Helioviewer org](https://user-images.githubusercontent.com/35879228/108557004-e0c40a80-72c5-11eb-9e6b-c92db7cdbc0a.png)

**Comment by wafels** [comment]
Thanks again for the report.

I just tried helioviewer.org myself and I see that some of the same problems from last week and earlier this week are re-asserting themselves. I think I know what is causing the issues, and have performed a temporary fix that should permit movie making. I was able to make a movie as a test.

Solving the problem more thoroughly will require some more diagnosis.  My apologies for the continuing problems.

**Comment by Anthrwpos** [comment]
still not able to create movie?

**Comment by Hesselen** [comment]
I and my students are seeing this error message tonight as well (March 21, 2021).  I am both unable to create a movie and unable to load previously created movies.  For example, I previously uploaded a movie to youtube at https://youtu.be/2U9TSa98l2k , the link back to the movie within helioviewer in the youtube description is no longer working.  Other video link examples no longer loading for me: 
https://helioviewer.org/?movieId=lxr75 
 https://bit.ly/3knJZC7
 https://helioviewer.org/?movieId=kxr75
https://helioviewer.org/?movieId=HVP75
https://helioviewer.org/?movieId=rZP75


![Screenshot 2021-03-21 213418](https://user-images.githubusercontent.com/81126822/111929626-4bb35d80-8a8d-11eb-920f-e537fb432713.png)

**Comment by wafels** [comment]
Thank you for the error report and the specific links to movies.  I was not able to get to those movies either.  I will file an issue.

**Comment by wafels** [comment]
Movies are able to be made.
