### ISSUE TITLE
Youtube quota error trying to upload a video

### ISSUE THREAD

**Issue by ichibanrob** [Helioviewer-Project/helioviewer.org#297]
{"error":"Failed to start the resumable upload (HTTP 403: youtube.quota, The request cannot be completed because you have exceeded your quota<\/a>.)","errno":0}

I assume this happened because you are an awesome website and have more people using it. If not, then maybe it needs to be fixed.
--Rob

**Comment by ichibanrob** [comment]
Upload is working again. I uploaded yesterday and just a few minutes ago successfully at helioviewer.org.

**Comment by wafels** [comment]
Thank you for reporting back. Sorry for the earlier issues.
