### ISSUE TITLE
Features and Events

### ISSUE THREAD

**Issue by tksteed** [Helioviewer-Project/helioviewer.org#302]
The features and events tab does not seem to be working.  Can you please help?

**Comment by wafels** [comment]
The website was down then. Are you still having problems?

**Comment by tksteed** [comment]
Thank you for replying.  My summer course has ended but I am gearing up for the fall semester.  Is the site back up now?


   [cid:4f56dc8c-5ae4-4b0a-9970-8f17ba37cd20]
   Karen Steed
   UAHT Math and Science Instructor,
   ***@***.***
   870-722-8272
[cid:a7fdc514-311f-4527-b971-32a69eb7b268]



________________________________

**Comment by wafels** [comment]
Yes, it's back, but with a reduced AIA and HMI data cadence. This will be fixed in the coming months. There is also another version of helioviewer at https://helioviewer.ias.u-psud.fr/ should helioviewer.org have problems.

**Comment by tksteed** [comment]
Thank you.  In earlier semesters, I could assign a student a date and they could go to the active regions and it would have them labeled.  Is this something that will be available again at some point?  I just went to the site and the feature is still listed but does not flag and label the areas.

Just so you know, your helioviewer is a favorite of the students in my classes.


   [cid:ab2463bf-10d3-43bf-981e-100508ae091d]
   Karen Steed
   UAHT Math and Science Instructor,
   ***@***.***
   870-722-8272
[cid:d10c785d-2c87-4c06-bac6-0e4f1d8b0df7]



________________________________

**Comment by wafels** [comment]
Thanks! I am glad your students enjoy the website.  I apologize for the recent problems with our services.

The labeling of active regions is still available.  If you can't use it, please let me know.

**Comment by dgarciabriseno** [comment]
Events are available today.
![image](https://user-images.githubusercontent.com/94071409/147780730-262f2668-4d31-45ed-9263-fdb0e7eba133.png)

@tksteed Let us know if you're running into any issues.

**Comment by dgarciabriseno** [comment]
Closing for now as events are currently working
