### ISSUE TITLE
helioviewer.org is down for the long time

### ISSUE THREAD

**Issue by vit1-irk** [Helioviewer-Project/helioviewer.org#309]
The website and API are down for a whole week (or even more), is there anyone to explain why?

**Comment by UeliDeSchwert** [comment]
Still down... any news?

**Comment by PabloA-dev-coder** [comment]
Maybe you can use helioviewer.ias.u-psud.fr in the meantime (movie generation won't work)

**Comment by wafels** [comment]
I managed to bring helioviewer.org back online. I think it is working OK, but I am keeping an eye on it. In the meantime, please keep  helioviewer.ias.u-psud.fr bookmarked!
