### ISSUE TITLE
More information in the celestial body pop-up

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#310]
The attached screenshot shows the calculated position of Mars (indicated by the text "Mars"), whereas the image shows that the planet is at a different location. The difference is because the image data is from an earlier time compared to the requested observation time. When clicking on the pop-up, the pop-up should show the observation time. This should be the relevant time for the position of the celestial object as shown on the screen.

![Screen Shot 2021-09-30 at 10 20 35](https://user-images.githubusercontent.com/983575/135473263-ab824ad6-8785-4975-b0f0-8a2ddaf0c512.png)

**Comment by dgarciabriseno** [comment]
The observation date is already in the top left corner which the user selects.

Helioviewer uses colors on the image dates to show that an image may not be current, so all the information is there.

Recommended that this info be added to a user guide.
