### ISSUE TITLE
Helioviewer website is not accessible 2021-JUNE-26

### ISSUE THREAD

**Issue by DawnMarieMueller** [Helioviewer-Project/helioviewer.org#312]
Hello.  I, and others in the U.S.A., are unable to access the Helioviewer website.  Error msg:  "This page isn't working right now."

I looked up Heliophysics.org website on DomainTools.com WHOIS search engine.  The site appears registered to NASA/GreenbeltMD.  I am unable to reach anyone at NASA to find out why the website is not accessible.

     https://whois.domaintools.com/helioviewer.org

AR12835 is rotated into view & needs to be monitored for flares, so help in resolving this issue would be appreciated by many.

I may be contacted by cellphone at 00 1 (779) 713-3893 and Twitter @Ancestralist and email dawnmm@mc.net for additional info.

**Comment by wafels** [comment]
Helioviewer.org is now back up, so closing this issue.
