### ISSUE TITLE
More information for Parker Solar Probe

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#314]
Parker Solar Probe (PSP) encounters are numbered. It would aid use of the Parker Solar Probe trajectories in helioviewer if the encounters were numbered. Since all the encounters are different, this would aid scientists in understanding which encounter they are looking at

**Comment by wafels** [comment]
Would also be good to make it easy to skip from one encounter to another. This will make it easier to navigate to the PSP encounter times quickly. Note that a similar feature for Solar Orbiter data would also be good - once Solar Orbiter data is available in helioviewer.org

**Comment by wafels** [comment]
Helioviewer release 3.3.4 puts the Encounter number on the on-screen display:
![Screen Shot 2022-02-23 at 15 23 49](https://user-images.githubusercontent.com/983575/155402100-54901ba1-fb9e-47bb-b8af-0baad5b902ff.png)
 
It would be useful if the Celestial Body menu also showed the current, next and previous encounter numbers

![Screen Shot 2022-02-23 at 15 24 35](https://user-images.githubusercontent.com/983575/155402408-5fae8089-c1ce-4a42-ba11-4de925baac5b.png)

The encounter number to be displayed will depend on the observation time.

**Comment by btaylor-sesda** [comment]
@wafels I've added the update to Beta.

![image](https://user-images.githubusercontent.com/87322123/157299922-5449e47a-2f34-4fd9-a4fa-fbbe3cf009c3.png)
