### ISSUE TITLE
Spurious re-centering when zoomed in

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#315]
When zoomed in to the solar limb, and then when clicking forwards and backwards in time, the application appears to re-center the view. This is not desirable when attempting to examine what is happening on the limb. No re-centering should occur at all.

**Comment by dgarciabriseno** [comment]
This appears to be resolved. When I zoom into the edge of the sun and move forward/backward in time, my viewport stays where it should be.
