### ISSUE TITLE
Re-write the Helioviewer User Guide

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#324]
The Helioviewer.org User Guide should be re-written. I am considering writing it using LibreOffice and then using [Pandoc](pandoc.org) to convert it into other formats. Thoughts?

**Comment by bogdanni** [comment]
Why not write it directly in Markdown and use pandoc to convert to other formats?

**Comment by wafels** [comment]
Is that how the JHelioviewer docs are written?

**Comment by bogdanni** [comment]
Yes.

**Comment by dgarciabriseno** [comment]
#310

**Comment by wafels** [comment]
There is now a basic user guide in markdown - see https://github.com/Helioviewer-Project/helioviewer-project.github.io/blob/master/user_guide.md . I am going to close this issue. However the link to it from helioviewer.org needs to be updated.
