### ISSUE TITLE
Movie Player not popping up when I go to movie link

### ISSUE THREAD

**Issue by dgarciabriseno** [Helioviewer-Project/helioviewer.org#325]
https://helioviewer.org/?movieId=2YNN5

With movieId=<ID> the movie player is supposed to popup with that movie.

**Comment by btaylor-sesda** [comment]
https://helioviewer.org/?movieId=2YNN5
Currently, the pop-up from that URL only works for me in FireFox. 

I wrote a patch that I'll need a way to test if we can replicate the same circumstance in Helioviewer Beta. I'll let you know what I find after adding it.

**Comment by dgarciabriseno** [comment]
Movie player opens for movie links
