### ISSUE TITLE
Student Helioviewer Movie Error

### ISSUE THREAD

**Issue by dzarro** [Helioviewer-Project/helioviewer.org#326]
student.helioviewer.org hangs when making movies.

![Capture](https://user-images.githubusercontent.com/3813813/149204532-425acd67-eb50-4c5a-a64a-44838f5a733d.jpg)

**Comment by dgarciabriseno** [comment]
Can you send me the Movie IDs that are failing?

You can hover over AIA 171 in Movie History and do a "copy link" and the link contains the movie ID.

**Comment by dgarciabriseno** [comment]
Will need more info to debug this. It is working for me

![image](https://user-images.githubusercontent.com/94071409/152039251-04cbf988-ec45-421c-b64e-7e747ba9055a.png)

**Comment by dgarciabriseno** [comment]
@dzarro Any update on this?

**Comment by dgarciabriseno** [comment]
Got an update from @dzarro offline that this is working now. Closing.
