### ISSUE TITLE
helioviewer not working on apple, chromebook devices

### ISSUE THREAD

**Issue by sweetlemon1025** [Helioviewer-Project/helioviewer.org#327]
Hello,

I'm an Astronomy teacher using helioviewer in my classroom. Yesterday the website was loading data, today it is not working on 75% of our devices. 

I'm not sure why this would be - we have restarted, tried different browsers, updated browswers, etc. and it is still not working. 

Specifically it loads the website, but doesn't show any data/images of the sun. The rest of the tools/etc. are there, just no data? Adding new layers, doesnt' do anything.

**Comment by dgarciabriseno** [comment]
Thanks, looks like something we need to look into, this is a problem with recent images.

You can move the date back to 1/18/22 or earlier and those dates should work.

**Comment by dgarciabriseno** [comment]
This should be resolved now.
@sweetlemon1025 can you confirm?

**Comment by dgarciabriseno** [comment]
Closing since the problem was issues with the downloader.
