### ISSUE TITLE
No updating

### ISSUE THREAD

**Issue by wireeye** [Helioviewer-Project/helioviewer.org#331]
Greetings, All three Helioviewer pages, beta.helioviewer.org, helioviewer.ias.u-psud.fr, and helioviewer.org haven't updated past Jan. 29th, on the SOHO, LASCO filters. Today is Feb. 2nd, I just wanted to make you aware of this problem, so you can address it at your convenience. Thanks for your time in advance

Sincerely, wireeye

**Comment by dgarciabriseno** [comment]
This has been resolved.
