### ISSUE TITLE
sdo.gsfc.nasa.gov/data/aiahmi/ full data video but helioviewer.org not

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/helioviewer.org#333]
Hi, why sdo.gsfc.nasa.gov/data/aiahmi/  have full data video, but helioviewer.org not? From the same source they collect data?

**Comment by dgarciabriseno** [comment]
Same source, yes. But for the helioviewer application to work, we mirror a subset of the image data available.

**Comment by wafels** [comment]
It is true that the ultimate source of the images seen in helioviewer.org and do.gsfc.nasa.gov/data/aiahmi/ is the same. However, the data processing pipelines that produce the images on either site are not the same. As was mentioned above, helioviewer.org provides a subset of all the image data available.
