### ISSUE TITLE
Regular 'About' text is dark

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#334]
The text in the 'About' pop-up is very dark in contrast to the background - see attached. It should be much brighter.
![Screen Shot 2022-02-23 at 17 06 23](https://user-images.githubusercontent.com/983575/155417255-7d857811-cb0b-4c0a-ad7f-6aef0685cf78.png)

**Comment by btaylor-sesda** [comment]
This should be fixed now.
https://beta.helioviewer.org/

![image](https://user-images.githubusercontent.com/87322123/156247031-61640a2d-04e0-40ea-949a-70c09682853b.png)
