### ISSUE TITLE
Icons don't show in interactive tutorial

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#335]
When you get to the Navigation Menu in the interactive tutorial the icons in the pop up don't show - see attached screenshot

![Screen Shot 2022-02-23 at 17 07 11](https://user-images.githubusercontent.com/983575/155417521-36f88c07-8710-4d6d-9eeb-c3ab7f0e3d3f.png)

**Comment by btaylor-sesda** [comment]
@wafels do you know where the icon image files are stored? The ones that aren't appearing, were previously hosted on the wiki server.

Example of a broken icon image:
https://wiki.helioviewer.org/w/images/c/c7/Icon-rss.png

**Comment by wafels** [comment]
Ah, so that's the cause of the bug. There are some images here

https://github.com/Helioviewer-Project/helioviewer.org/tree/master/resources/images

but perhaps a better solution would be to refer to them the same way they are referred to in the main application?

**Comment by btaylor-sesda** [comment]
It should be fixed now.
https://beta.helioviewer.org/

![image](https://user-images.githubusercontent.com/87322123/156239253-1d9037e0-61f0-4770-8d55-222e693e48cc.png)
