### ISSUE TITLE
Update about new player in the new server

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/helioviewer.org#336]
Hi, with new player, the bar below (1), doesn't disappear when a video plays (only if it's full screen), and when i click on "play" (triangle) to play, i can't stop it with spacebar as with the previous player. It's easy to change that? Thanks
![Untitghled](https://user-images.githubusercontent.com/20747347/155804251-a6276d5d-0bf6-45a8-9a51-701415dac999.png)

**Comment by dgarciabriseno** [comment]
Thanks for the report! This is fixed on helioviewer.org & beta.helioviewer.org now.
The control bar will disappear and you can play/pause with spacebar.

**Comment by Anthrwpos** [comment]
Thank you.

**Comment by Anthrwpos** [comment]
Hi, about the player in the new server, again the same. the bar (1), doesn't disappear when a video plays (only if it's full screen), and when i click on "play" (triangle) to play, i can't stop it with spacebar as with the previous player. It's easy to change that? Thanks

**Comment by dgarciabriseno** [comment]
Hello, this was a mistake on my part, front end wasn't updated to latest. This feature is back now.

**Comment by Anthrwpos** [comment]
> Hello, this was a mistake on my part, front end wasn't updated to latest. This feature is back now.

Thanks
