### ISSUE TITLE
Some text and icons are dark

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#338]
At the top of the included screenshot, the text "AIA 1700" is dark against the background. Also, the "down triangle" next to it is also dark. Similarly on the left, "LASCO C3 " plus down triangle, "HEK", and "SOHO" are all too dark. In addition, the "H" icon and "image" icon on the right are too dark against the background.

![Screen Shot 2022-03-01 at 16 07 44](https://user-images.githubusercontent.com/983575/156249130-7579d6ff-3b0f-4c45-9ae3-cb2471ae8d55.png)

**Comment by btaylor-sesda** [comment]
This looks like the result of when jQuery UI was updated from 1.12.1 to 1.13.1

A couple of icon files are being called that don't exist anymore. I'll play around with the existing files, create a few new ones with the correct colors, and hopefully that'll fix the issue.

**Comment by btaylor-sesda** [comment]
@wafels I updated these in beta. I'll keep this ticket open for a week in case we find more examples.
https://beta.helioviewer.org/

**Comment by dgarciabriseno** [comment]
@btaylor-sesda Do you know which commit fixes this so I can cherry-pick it to helioviewer.org?

**Comment by btaylor-sesda** [comment]
@dgarciabriseno The following are files/folders that need to be updated to the production server for this issue. 
As a result of inconsistencies from the jQuery UI upgrade to 1.13.1, I'm expecting more unknown icon/text style issues may need to be resolved. 

**File:** dialogs.css
**Last commit for this issue:** ddb3965773ae1632e8dc1975a3f487f22c046b95

-----
**File:** dot-luv.css
**Last commit for this issue:** 929d5871b9510df9b770272cccd3f9b034c3e774

-----
**Folder:** resources/lib/jquery-ui-1.13.1/images/
**Last commit for this issue:** 9a3b8c29cce0dfc8206a76de36ab7d1bfbd093d8
**Note:** These are uploaded images

**Comment by dgarciabriseno** [comment]
Pulled onto helioviewer.org
