### ISSUE TITLE
About the player in the new server

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/helioviewer.org#344]
Hi, about the player in the new server, again the same. the bar (1), doesn't disappear when a video plays (only if it's full screen), and when i click on "play" (triangle) to play, i can't stop it with spacebar as with the previous player. It's easy to change that? Thanks

_Originally posted by @Anthrwpos in https://github.com/Helioviewer-Project/helioviewer.org/issues/336#issuecomment-1116411629_

**Comment by dgarciabriseno** [comment]
This is working now.
