### ISSUE TITLE
SPoCA feature outlines are not being shown for recent SPoCA detections

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#348]
SPoCA features should have a shape attached which shows the the shape of the feature detected by SPoCA. The 2012 image below shows these features - see the big yellow shape in the image below for the coronal hole (CH).

![2012_05_06_22_02_49_AIA_211](https://user-images.githubusercontent.com/983575/169878271-e383db56-8137-4cc5-aa4a-03923f81c475.png)

SPoCA active regions (AR) are shown using pink shapes.

The 2022 image shows the existence of SPoCA CHs and ARs but does not show the corresponding shapes.

![Screen Shot 2022-05-23 at 13 45 13](https://user-images.githubusercontent.com/983575/169878315-54a4150e-4e9a-40f3-adf6-70836b0893ad.png)

**Comment by btaylor-sesda** [comment]
@wafels The recent PNG images that are supposed to show the shapes, are not found on the server for some reason. @dgarciabriseno can we check to see where the disconnect may be?

Not showing (new):
https://helioviewer.org/cache/events/2022/05/22/ivo%253A%252F%252Fhelio-informatics.org%252FCH_SPoCA_20220523_161033_20220522T190005_5.png

Is showing (old)
https://helioviewer.org/cache/events/2012/05/22/ivo%253A%252F%252Fhelio-informatics.org%252FCH_SPoCA_20120522_195146_20120522T193620_0.png

**Comment by dgarciabriseno** [comment]
Let me check

**Comment by dgarciabriseno** [comment]
It looks like this is something that was missed in the migration. @wafels do you know what script downloads these pngs? They're there up until May 2nd, looks like I missed this.

**Comment by dgarciabriseno** [comment]
Looks like it's from event_cache.sh but it's missing the json files that it uses to get the pngs. Working on this now.

**Comment by dgarciabriseno** [comment]
The problem was permissions on that events directory. I fixed this and ran the import script and these pngs should be back now.
