### ISSUE TITLE
I can not center the image from STEREO-A with the button, only manually

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/helioviewer.org#349]

**Comment by dgarciabriseno** [comment]
@Anthrwpos can you share the date/time/instrument that you're looking at? Use the share viewport button on the top right.

**Comment by btaylor-sesda** [comment]
@Anthrwpos Unfortunately I'm having trouble replicating the issue. 

Along with @dgarciabriseno's inquiry of the date, time, and instruments selected, what device type/version (smartphone, tablet, or PC/laptop) and browser are you using?

**Comment by Anthrwpos** [comment]
> @Anthrwpos Unfortunately I'm having trouble replicating the issue. 
> 
> Along with @dgarciabriseno's inquiry of the date, time, and instruments selected, what device type/version (smartphone, tablet, or PC/laptop) and browser are you using?

Hi, maybe you can't, because I can center the image from STEREO-A now. Does anyone change something or it was for that moment? I don't know.

**Comment by Anthrwpos** [comment]
> @Anthrwpos can you share the date/time/instrument that you're looking at? Use the share viewport button on the top right.

Hi, it's fine now. But, what have to do the time and date with the instrument about my question? Thanks

**Comment by dgarciabriseno** [comment]
Closing since it seems to be fine now.

@Anthrwpos since I couldn't reproduce the issue myself, the next step with debugging would be to get helioviewer as close to what you were running when the issue happened. Hence the time/date/instrument.
