### ISSUE TITLE
Length scale indicator

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#35]
It would be good to have an additional scale indicator along with the Earth scale indicator.  Perhaps there could be a toggle like the co-ordinate toggle.  One of the toggles would show the current 'Earth Scale' box, and the other one would show "km" for kilometers.

**Comment by ddialer** [comment]
Completed. 
<img width="144" alt="screen shot 2016-02-26 at 4 39 58 pm" src="https://cloud.githubusercontent.com/assets/403007/13366173/a2104ace-dca7-11e5-98fe-f40d805a2fbc.png">

Also Scale Bar displayed on generated screenshots and movies

**Comment by wafels** [comment]
Nice!  Thanks!
