### ISSUE TITLE
Change the contact address

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#350]
The "Contact" email address in the "?" pop-up menu should go to my regular work address. The change should be online before June 20, 2022.

**Comment by btaylor-sesda** [comment]
The current plan is to update the /resources/js/Utility/Config.js file, so that the **contact_email** parameter is changed from contact@helioviewer.org to HelioViewerDevelopment@nasa.onmicrosoft.com

**Comment by btaylor-sesda** [comment]
This change has been added to the live server.
