### ISSUE TITLE
Helioviewer & France mirror stalled loading current images

### ISSUE THREAD

**Issue by DawnMarieMueller** [Helioviewer-Project/helioviewer.org#352]
Hello to whomever is managing the Helioviewer project these days!

Beginning yesterday 2022-May-28, I am able to access Helioviewer.org and the IAS mirror, but I am able load & manipulate images only up to 16:51:41 UTC on Helioviewer.org and 17:21:41 on mirror https://helioviewer.ias.u-psud.fr/ , for example, for SDO AIA 304.

Helioviewer is not loading images more current than those approximate timestamps for SDO AIA & HMI, nor for SOHO LASCO C1/C2, & other spacecraft instruments.

Would you very kindly look into & let me know what the problem is?

Some of us  Helioviewer users on Twitter are wondering if this is a Helioviewer problem, or a NASA-related problem, or other.

I do not know if JHelioviewer is experiencing the same problem, as I am at present obliged to access images via a non-Linux desktop computer with not enough memory on board to run JHelioviewer smoothly while having a zillion other windows & tabs open, under Windows 10.  Some other folks out there in the wild are also working from computers that are not allowed to download & install JHelioviewer or other software without necessary privileges.

I am also sending this message via email to both

   HelioViewerDevelopment@nasa.onmicrosoft.com
   contact@helioviewer.org

as well as posting to Helioviewer GitHub issues page,

as I see from the most recent post that changes are being made to Helioviewer's contact address coding.

Please contact me if I may be of assistance.

Thank you very kindly for your help.

Dawn Marie Mueller 
email: dawnmm AT mc.net 
Twitter:  @MagnetoDawn

**Comment by wafels** [comment]
Hello, and thank you for the report.

At the moment, LASCO images appear to be arriving at Helioviewer within expectations. STEREO images are also arriving within expectations (STEREO images can be days behind real time).

SDO images are still delayed.  I am looking into the cause of this.

**Comment by DawnMarieMueller** [comment]
Thank you, Jack. 

I greatly appreciate it. 

I realize it's a holiday
weekend. 

Things happen. 

:) 

Kind regards, 

Dawn


-------------------------

On Mon, 30 May 2022 04:10:44 -0700, Jack
Ireland  wrote:  

Hello, and thank you for the report. 

At the moment,
LASCO images appear to be arriving at Helioviewer within expectations.
STEREO images are also arriving within expectations (STEREO images can be
days behind real time). 

SDO images are still delayed. I am looking into
the cause of this. 

--
Reply to this email directly, view it on GitHub
[1], or unsubscribe [2].
You are receiving this because you authored the
thread.Message ID:   
-------------------------
  

Links:
------
[1]
https://github.com/Helioviewer-Project/helioviewer.org/issues/352#issuecomment-1141023981
[2]

**Comment by wafels** [comment]
SDO images are now catching up. It may take some time for the more recent images to appear.

**Comment by DawnMarieMueller** [comment]
Very good, Jack! 

Thank you for letting me know. 

My apologies for
bugging you on a federal holiday weekend. 

Have a sunny week! :) 

Kind
regards 

Dawn 

Dawn Marie Mueller 

Crystal Lake, Illinois 

phone: (779)
713-3893 

email: ***@***.*** 

Twitter: @MagnetoDawn


-------------------------

On Tue, 31 May 2022 09:22:21 -0700, Jack
Ireland  wrote:  

SDO images are now catching up. It may take some time
for the more recent images to appear. 

--
Reply to this email directly,
view it on GitHub [1], or unsubscribe [2].
You are receiving this because
you authored the thread.Message ID:   
-------------------------
 


Links:
------
[1]
https://github.com/Helioviewer-Project/helioviewer.org/issues/352#issuecomment-1142345956
[2]

**Comment by wafels** [comment]
Closed since images are back to close to real-time.
