### ISSUE TITLE
Re-centering button

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#353]
It's easy to move the sun or any image out of the viewer window. A re-centering button would allow the view to snap back to the center of the Sun. helioviewer.org has this function

**Comment by wafels** [comment]
This is still useful as it is easy to get lost when zoomed in on LASCO data far off-disk.

**Comment by btaylor-sesda** [comment]
@wafels The re-centering button is in the hamburger menu. 

Currently when clicked, the behavior closes the menu and then returns to the viewport with the desired effect. 
Do we need to move the button or is it good where it is?
