### ISSUE TITLE
Need a "Jump" dialog

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#356]
This a feature request for mobile. At the moment the mobile version of helioviewer allows you to jump forward and backwards by one day. The desktop version of helioviewer.org allows you to specify how much forwards and backwards in time you can jump. A small number of jumps are selectable. This jump dialog should be in the mobile version too.

**Comment by btaylor-sesda** [comment]
The added "Jump" functionality has been added to develop.helioviewer.org
