### ISSUE TITLE
Movie Making on Mobile

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#357]
After playing around with the movie creation I think we can drop the ability to "Select Area" and always use full viewport. The reason to do this is that it the user is always going to be looking at something interesting on a small screen so the user has already selected an area of interest.

Movie creation seems to work just fine. A couple of things 1. I didn't get a notification that the movie was ready and 2. the movie player was awkward to use

-------

The controls, buttons, and window all need to be reformatted for mobile design.

**Comment by wafels** [comment]
The movie I made took one minute to make. That's pretty fast, but maybe that was due to me being the only person trying to make a movie. I downloaded the movie and then uploaded it to a friend on Instagram. So making it easy to download movies and share them might be a good way to go.

**Comment by btaylor-sesda** [comment]
@wafels Specifically with Instagram, I'm not sure there is an easier way than directly uploading movies from your device.

**Comment by btaylor-sesda** [comment]
I imagine that the movie-making feature could be updated further as new releases are added but for now, the callouts were rectified in the type of view option allowed and after testing, it looks like the notifications should appear as well - once downloaded.
