### ISSUE TITLE
Timeline: plurals in the number of images

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#36]
The text that shows the number of images should be sensitive to whether there is 1 image or not.  The image below illustrates the issue.

<img width="488" alt="screen shot 2016-01-13 at 8 45 39 am" src="https://cloud.githubusercontent.com/assets/983575/12296031/16bce6fe-b9d3-11e5-8392-ed7418860e41.png">

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
fixed
