### ISSUE TITLE
Continuously zoomable images

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#360]
This image:

https://www.sidc.be/EUI/pictures/20220307_hrieuv_mosaic/

is continuously zoomable and relies on this library:

http://openseadragon.github.io/

Should this be implemented in Helioviewer, and if it is, how would this affect the screenshot and movie making capability? And positioning of features and events....

**Comment by wafels** [comment]
Features and events are doable:

http://openseadragon.github.io/examples/ui-overlays/

**Comment by wafels** [comment]
A typical helioviewer viewer window would include multiple layers, features and events and labels. Transparency also needs to be included in order to make sure that the Sun is visible in the center of coronagraph images.

**Comment by dgarciabriseno** [comment]
Since we have code to handle this for mobile, I can likely leverage the same code for handling zoom but connect it to the mouse wheel.

**Comment by dgarciabriseno** [comment]
We could also still explore openseadragon. I think I have some notes from playing with openseadragon before.

**Comment by dgarciabriseno** [comment]
We have continuous zoom now.
