### ISSUE TITLE
Remove link to "legacy.helioviewer.org"

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#365]
The "?" icon pops up a menu with a link to "legacy.helioviewer.org". This should be removed from the menu. Not really a bug I suppose but legacy.helioviewer.org does not exist.

**Comment by btaylor-sesda** [comment]
The update has been made to https://beta.helioviewer.org/ in the resources/js/CustomHandling/CustomHandling.js file. 

@dgarciabriseno can you push the file to prod?

**Comment by dgarciabriseno** [comment]
@btaylor-sesda Wouldn't it be better to delete the html rather than just set it to `display: none`?

**Comment by btaylor-sesda** [comment]
@dgarciabriseno  Ideally. Do you know where that HTML lives? I looked in the index and many of the files in /resources/js but maybe I wasn't lucky enough to run across it.
