### ISSUE TITLE
I have lots of movie history, but can't scroll down.

### ISSUE THREAD

**Issue by dgarciabriseno** [Helioviewer-Project/helioviewer.org#369]
https://user-images.githubusercontent.com/94071409/177348013-3e447249-6d80-45e4-9604-df56134e4f8b.mov

**Comment by btaylor-sesda** [comment]
@dgarciabriseno I added an overflow and max-height to the div in develop.helioviewer.org so it should give a default scrollbar when this happens.

Update made to:
resources/css/media-manager.css

**Comment by dgarciabriseno** [comment]
I saw you made the change on beta, I'll update it on prod.

On a side note, not a big deal but you have some trailing whitespace in the file.
You can set up your editor to automatically trim trailing whitespace.
