### ISSUE TITLE
HMI SHARP labels should be more informative

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#37]
Currently the HMI SHARP labels just say "Active Region" - see attached screenshot.  These should be much more informative.  I recommend replacing the current label with "HMI SHARP n" where "n" is the feature recognition method identifier.  

![screen shot 2016-01-21 at 3 53 30 pm](https://cloud.githubusercontent.com/assets/983575/12494339/925bf3ec-c057-11e5-8ec3-8cc8f7fb314c.png)

**Comment by ddialer** [comment]
Done. Now when server return event from server without "hv_labels_formatted" parameter label name will be displayed using parameters "frm_name" and "frm_specificid"

**Comment by wafels** [comment]
Confirmed fixed!
