### ISSUE TITLE
Helioviewer should alert the user that no data is available

### ISSUE THREAD

**Issue by dgarciabriseno** [Helioviewer-Project/helioviewer.org#372]
When you use the base diff option on the source selector, you can enter a date that we don't have images for.
When this happens the sun disappears without any further information.

https://user-images.githubusercontent.com/94071409/182615178-46a3762f-61cd-4c77-9e21-96a00e29586e.mov

**Comment by dgarciabriseno** [comment]
The error message is sent back with the API request. We should use the alert feature we have to display the message.

**Comment by wafels** [comment]
See also Helioviewer-Project/api#241

**Comment by dgarciabriseno** [comment]
Going to resolve this with Helioviewer-Project/helioviewer.org#428
