### ISSUE TITLE
SDO one day behind

### ISSUE THREAD

**Issue by wireeye** [Helioviewer-Project/helioviewer.org#375]
Greetings, 
I noticed that your Images for the SDO is a day behind, thus I am unable to make an up-to-date video from this option. Is this issue being addressed? I just wanted to bring this matter to your attention, Have a good day :)
![Helioviewer org - Solar and heliospheric image visualization tool 2022-08-18](https://user-images.githubusercontent.com/35879228/185480503-41658338-d3b6-4bc9-b414-1bb7b8027111.png)

**Comment by dgarciabriseno** [comment]
Sorry about that, it's catching up now.
