### ISSUE TITLE
Adding a layer causes the Sun to shift

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#38]
Adding a layer causes the Sun to shift

Before
![before](https://cloud.githubusercontent.com/assets/983575/12495730/5f4d4d22-c05f-11e5-9877-6e84a604cbd7.png)

After
![after](https://cloud.githubusercontent.com/assets/983575/12495739/6ce36ce6-c05f-11e5-9333-3131f91bee00.png)

**Comment by ddialer** [comment]
this issue should be fixed already. I just uploaded beta3.helioviewer.org web site and better to try test it again

**Comment by wafels** [comment]
fixed
