### ISSUE TITLE
Can't exit viewing HEK data

### ISSUE THREAD

**Issue by dgarciabriseno** [Helioviewer-Project/helioviewer.org#383]
To Reproduce:
- Touch an event
- Touch view HEK data
- See inescapable element

<img width="520" alt="image" src="https://user-images.githubusercontent.com/94071409/191328127-b66c99d0-a925-4ec0-8361-43665aeb4426.png">

**Comment by dgarciabriseno** [comment]
Also the data table looks pretty bad here too.

**Comment by btaylor-sesda** [comment]
Fixed
