### ISSUE TITLE
Feature/event pop-ups: "Hide empty rows" always in HEK window pop-up

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#386]
In the HEK feature/event pop-up, the "Hide empty rows" hides the empty rows. But on pressing it, the "Hide empty rows" text remains. The text should toggle between "Hide empty rows" and "Show empty rows" as appropriate. This issue affects the mobile and desktop versions of hv.org. The screenshots below demonstrate the issue.

![Screen Shot 2022-10-21 at 13 52 48](https://user-images.githubusercontent.com/983575/197258986-9996b163-5fc3-4df0-b431-e27412c7c4c0.png)
![Screen Shot 2022-10-21 at 13 52 39](https://user-images.githubusercontent.com/983575/197259000-b2ad8c1f-6c7f-4cbd-b228-6ca0f38f3bc3.png)

**Comment by btaylor-sesda** [comment]
I've made this update to https://develop.helioviewer.org/
