### ISSUE TITLE
Timeline: occasional creation of un unnecessary third band of observations

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#39]
Occasionally, when zoomed in to see individual file times, a third band of observations is created.  This appears to be caused by files from two different instruments having the same observation time.  Obviously this third band is not required.  The attached images illustrates the issue.
![screen shot 2016-01-22 at 9 29 06 am](https://cloud.githubusercontent.com/assets/983575/12513588/8ccadaf2-c0ec-11e5-9f2e-7e0065e02a1d.png)
![screen shot 2016-01-22 at 9 41 22 am](https://cloud.githubusercontent.com/assets/983575/12513586/8cc926a8-c0ec-11e5-8b0c-3a4557f50faf.png)
![screen shot 2016-01-22 at 9 41 15 am](https://cloud.githubusercontent.com/assets/983575/12513589/8ccc535a-c0ec-11e5-92b2-2113e8cc36c0.png)
![screen shot 2016-01-22 at 9 29 17 am](https://cloud.githubusercontent.com/assets/983575/12513587/8cca639c-c0ec-11e5-9994-4df67a59fb45.png)

**Comment by ddialer** [comment]
Fixed. Fix submitted to the API repository

**Comment by wafels** [comment]
Fixed.
