### ISSUE TITLE
Shared to YouTube on mobile does not work

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#390]
This might be because there are no movies shared from the development site.

In any case, the desktop version has two categories of shared movies. The first is movies that span the observation date, and the second is the recently shared. Neither of these categories appear in the mobile version. The fact that the categories don't even appear may point to a flaw in the logic of how the sharing menu works as I expect that even if no movies meet the criteria to be shown (which is ok) the categories should be displayed.

**Comment by btaylor-sesda** [comment]
These two categories should appear now on mobile.
https://develop.helioviewer.org/
