### ISSUE TITLE
Feature/event pop-ups : jumping to start end times don't work on mobile

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#392]
Feature and event pop-ups have start/end times that allow users to jump to start/end of an event.  They look like `|<-` and `->|` - see screenshot.

![Screen Shot 2022-10-21 at 17 06 37](https://user-images.githubusercontent.com/983575/197288760-51fa16c1-2188-4151-96d1-0b8a11ccd931.png)

These work on desktop, and should work on mobile.

**Comment by btaylor-sesda** [comment]
@wafels This should be fixed now. I noticed on develop.helioviewer.org, i had to navigate to 10/18/2022 before it started to work. But I think that may just be a data issue involving the developer server. Let me know if the arrow links are now working for you or not.

**Comment by wafels** [comment]
Confirmed as working.
