### ISSUE TITLE
Manually entering a date on mobile does not result in data from that time being displayed

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#394]
A user manually entering a date on mobile wants to see the Sun at that date. hv.org on mobile should show data from that date. This functionality works on the desktop version.

**Comment by btaylor-sesda** [comment]
The original behavior in the desktop version, lets the user change the date in the calendar and then once clicked-off of the calendar, the viewport changes accordingly. This should be fixed now.
https://develop.helioviewer.org/
