### ISSUE TITLE
Zoom in - can't see top and bottom of Sun

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#41]
When zoomed in as much as allowed, it is not possible to see the top and bottom of the Sun.  Note that only AIA data has been selected using the image selector.  The images below illustrate the issue.

![screen shot 2016-02-02 at 11 36 37 am](https://cloud.githubusercontent.com/assets/983575/12756525/2537316a-c9a2-11e5-91f2-0d4f038927df.png)
![screen shot 2016-02-02 at 11 42 39 am](https://cloud.githubusercontent.com/assets/983575/12756524/2381fc88-c9a2-11e5-99ad-f45d9773c003.png)

**Comment by ddialer** [comment]
Fixed

**Comment by wafels** [comment]
Fixed.
