### ISSUE TITLE
Some tooltips are off-screen

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#42]
A user has reported that some of the help tooltips pop-up with most of the tooltip not visible.  The use originally reported this issue using Chrome on a Windows OS, and has been confirmed using Chrome on OSX.  The attached images illustrate the issue.  The tooltips are barely visible as a small grey/white column on the right hand side just under the (?) of the help.  It appears that all the help tooltips on the right hand side of the drop down UI elements of screenshot, movies, news, etc (all the operations available on the right hand side of helioviewer.org) are affected.  In Firefox, no part of the tooltip is visible at all.

![screen shot 2016-02-03 at 2 08 23 pm](https://cloud.githubusercontent.com/assets/983575/12793772/193953aa-ca80-11e5-9fad-3d986cc520ef.png)
![screen shot 2016-02-03 at 2 07 58 pm](https://cloud.githubusercontent.com/assets/983575/12793775/1be9ecc2-ca80-11e5-9f9c-8cd7501357da.png)
![screen shot 2016-02-03 at 2 07 42 pm](https://cloud.githubusercontent.com/assets/983575/12793777/1e7c4c28-ca80-11e5-8ce5-eef82c925b97.png)

**Comment by ddialer** [comment]
Fixed.
The only one place I found where Tooltip is still doesn't work is Earth-Scale toggle. I didn't go deeper to find the issue because this button will be refactored and added Length scale indicator as described in "Length scale indicator #35"

**Comment by wafels** [comment]
Fixed.
