### ISSUE TITLE
Pasting links leads to off center images

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#43]
Generated this link in Firefox:

http://beta3.helioviewer.org/?date=2014-02-04T16:00:01.000Z&imageScale=2.4204409&centerX=0&centerY=0&imageLayers=%5BSDO,HMI,magnetogram,1,100%5D&eventLayers=%5BAR,all,1%5D,%5BCC,all,1%5D,%5BCD,all,1%5D,%5BCH,all,1%5D,%5BCJ,all,1%5D,%5BCE,all,1%5D,%5BCR,all,1%5D,%5BCW,all,1%5D,%5BEF,all,1%5D,%5BER,all,1%5D,%5BFI,all,1%5D,%5BFA,all,1%5D,%5BFE,all,1%5D,%5BFL,all,1%5D,%5BLP,all,1%5D,%5BOS,all,1%5D,%5BPG,all,1%5D,%5BSG,all,1%5D,%5BSP,all,1%5D,%5BSS,all,1%5D&eventLabels=true

The view in my browser is:
![screen shot 2016-02-04 at 3 41 40 pm](https://cloud.githubusercontent.com/assets/983575/12830026/27a1f402-cb5b-11e5-8fa7-80573888eb0a.png)

Pasting the link in Safari results in this view:

![screen shot 2016-02-04 at 3 42 36 pm](https://cloud.githubusercontent.com/assets/983575/12830041/365c0cb2-cb5b-11e5-8621-4b36fc947330.png)

**Comment by ddialer** [comment]
can't reproduce.

**Comment by wafels** [comment]
Perhaps fixed by other fixes?
