### ISSUE TITLE
From phone can't move the Earth scale box or it doesn't include it when take screenshot

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/helioviewer.org#431]
Hi, I noticed that I can't move the Earth box and when I take screenshot the it doesn't include the box of Earth. 
From phone.
Thanks

**Comment by Anthrwpos** [comment]
Hi, is there any update about the question?
Thanks

**Comment by wafels** [comment]
Keeping the Earth box in one place while on mobile devices is by design, but it should appear in a screenshot. Which type of phone are you using?

**Comment by Anthrwpos** [comment]
When I take a screenshot from the option the page gives the box with the earth does not appear, only if I take a screenshot with the mobile mode it appears.


________________________________

**Comment by Anthrwpos** [comment]
Οκ, but why is it by design that the box does not move from view to mobile?

**Comment by Anthrwpos** [comment]
No, in screenshot ( from the option of the website) doesn't appear the icon of Earth. why?
but with a screenshot when I do it from the mobile phone, the Earth is visible.

**Comment by Anthrwpos** [comment]
Can the design be changed so we can move the box with the Earth? Thanks

**Comment by dgarciabriseno** [comment]
Yes, I can work on this now.

The other issue I see here is that the earth scale will appear in screenshots, but only when the viewport is in the right spot. The problem that needs to be fixed is the position of the earth scale widget you see in the mobile view is different than the position used when a screenshot is taken, and that's a problem that I need to fix.

Once I fix that I'll look into making it moveable.

**Comment by dgarciabriseno** [comment]
The earth scale box can now be moved.
Fixed in 77a0f9a839c3760ce907c272a97978c4d30e5fdb

The position of the earth scale box in the viewport is now mostly aligned with what you see in a screenshot.
There is a slight offset, but hopefully this isn't too much of an issue.
Positioning fixed in 4843f07702373a3503f6cb895f3d4f91658ef4b8
