### ISSUE TITLE
GDPR compliance

### ISSUE THREAD

**Issue by helioshk** [Helioviewer-Project/helioviewer.org#432]
Websites that are used by EU citizen are required to ask for permission to process personal data.
I think in this case it's storing cookies, collecting IP-addresses, user agent data.

I'm afraid, the website needs a "cookie banner"

**Comment by dgarciabriseno** [comment]
Helioviewer doesn't process personal data. It doesn't use cookies. Videos and screenshots are not stored with any user data attached to them.
Your screenshots and videos that show in your browser are stored locally in your browser.

**Comment by helioshk** [comment]
At least my browser has 3 cookies from helioviewer.org
I guess it's for the image search parameters

**Comment by dgarciabriseno** [comment]
What browser are you using? I looked a little more, helioviewer will try to use cookies to try to store videos/screenshots you've created if your browser doesn't support the localStorage API. But again, we don't process any of this on the server.

You can view the database tables we have in https://github.com/Helioviewer-Project/api/blob/master/install/helioviewer/db.py

**Comment by helioshk** [comment]
Chrome; I deleted the cookies, opened helioviewer.org without doing anything and got 4 cookies according to chrome.
Could be a chrome issue ¯\_(ツ)_/¯

**Comment by helioshk** [comment]
Nevermind, I tried it on a basically blank page and it still shows a cookie. Perhaps it's one of the addons. 
Sorry for the confusion.
