### ISSUE TITLE
It's easy to change the way we set time? (PC)

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/helioviewer.org#440]
Because with new change, we only can with mouse and it's not helping. From PC need to click for every number to change the exact time you need, and not possible to go directly to the time you want. Can you change it to the way it worked before? Thanks

**Comment by dgarciabriseno** [comment]
Thanks for the feedback, let me see what I can do.
I intended to change the appearance, I didn't want to make it more difficult to navigate

**Comment by dgarciabriseno** [comment]
@Anthrwpos With this patch you will be able to manually type in the desired dates on PC.
You might need to clear cache to pick up the changes.
