### ISSUE TITLE
"Images" title below where it should be

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#450]
The screenshot below shows the issue. The down arrow and the text "Images" are on a line below where they should be. These should be in the same line as the line above showing a 3x3 grid and "+Add Layer".

![Screen Shot 2023-03-06 at 13 18 49](https://user-images.githubusercontent.com/983575/223557432-64e1d9ce-6326-42f2-84a9-f3a5a08745d8.png)

**Comment by btaylor-sesda** [comment]
This should be fixed now. 
https://helioviewer.org/
