### ISSUE TITLE
SDO Behind

### ISSUE THREAD

**Issue by wireeye** [Helioviewer-Project/helioviewer.org#452]
Greetings, I noticed the last week or so, that SDO filter has been five days behind. Is this a problem with the satellite, or maybe a problem with the coding? As always, thanks for your time, and effort concerning this matter.

Sincerely, wireeye

**Comment by wafels** [comment]
Updates on this issue are being tracked here: https://github.com/Helioviewer-Project/api/issues/276 .

Note that GOES-R SUVI images are up-to-date and overlap with those provided by SDO AIA.

**Comment by wafels** [comment]
Closing since we are back up-to-date.
