### ISSUE TITLE
Selected HEK features/events not showing up in the mobile client

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#458]
Selected HEK features/events do not show up on the mobile client. However, selected CCMC results are displayed. The expected behavior is that the HEK features/events should be displayed.

The browser used was Safari on an iPhone.

**Comment by wafels** [comment]
Also, the HEK "check all" and "check none" buttons do not work.

**Comment by btaylor-sesda** [comment]
@wafels This looks to be from the CCMC project that @dgarciabriseno is currently working on. 

https://github.com/Helioviewer-Project/helioviewer.org/commit/d354f7d4fc1e424dfd26615fcff4314459e41887

The "Loading Data" keeps spinning now, none of the non-CCMC pins are working on HEK, and none of the tools in the top right tray are clickable.

The console error says, "properties of undefined (reading 'concat')". 
It mentions that it has a problem with this **line 123** from resources/js/Events/EventTree.js

`saved = self.getSavedEventLayers().concat(this._selectedEventCache.get());`

**Comment by dangarbri** [comment]
Hey @btaylor-sesda thanks for triaging this.
I'm not seeing the error myself so I'll need your help. Let's talk

**Comment by dgarciabriseno** [comment]
The features/events not working is mobile specific. I'll look into it once we fix #407

**Comment by dgarciabriseno** [comment]
Loading issue fixed, now looking into these checkboxes

**Comment by dgarciabriseno** [comment]
This might actually have had the same root cause as the "loading data" issue. It appears to be working for me on my own phone and several phones on browserstack

**Comment by wafels** [comment]
Works on Safari / iPhone . Closing.
