### ISSUE TITLE
Small white rectangles sometimes appear on drop menus on right hand side

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#46]
Using Chrome on Windows, an occasional white bar can be seen somewhere between the drop down menu and the menu bar across the top.

**Comment by ddialer** [comment]
Fixed in cb05d93bc4102a52abb72cab6927542933c3ff2a commit

**Comment by wafels** [comment]
Example from user: included for clarity

![Uploading Screenshot 2016-02-04 10.02.13.png…]()

**Comment by ddialer** [comment]
fixed. validated thru browserstack.

**Comment by wafels** [comment]
ok.
