### ISSUE TITLE
User guide link in helioviewer.org needs to be updated.

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#462]
With the closing of the [user guide issue](https://github.com/Helioviewer-Project/helioviewer.org/issues/324), it remains to update the link in helioviewer.org to point to the user's guide.

![Screen Shot 2023-04-14 at 11 59 02](https://user-images.githubusercontent.com/983575/232095557-2eb0e5fc-05eb-4ebb-995d-23376477b3a9.png)

**Comment by btaylor-sesda** [comment]
In the master branch, I updated this link to point to https://helioviewer-project.github.io/user_guide/
