### ISSUE TITLE
Tables in html generated from markdown should be improved

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#463]
The [user guide](https://helioviewer-project.github.io/user_guide/) contains two tables - see the screenshots below. They really don't look good. I think the CSS for the tables should be updated so that at a minimum there is a border around every cell in the table. That would increase the legibility of the table and the user guide. Other changes to increase legibility should also be considered.

![Screen Shot 2023-04-14 at 12 00 53](https://user-images.githubusercontent.com/983575/232096211-812fb639-49f7-4be1-b000-cbaa1415b268.png)

![Screen Shot 2023-04-14 at 12 00 45](https://user-images.githubusercontent.com/983575/232096223-3f0e49db-a9c2-474f-828a-263b67508a4a.png)

**Comment by btaylor-sesda** [comment]
I've added a max-width of 450 pixels for images and a default bordering for all tables going forward.
