### ISSUE TITLE
Zoom in causes centering to shift

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#47]
If you zoom in, and then press the center button, the image moves, presumably re-centering.  If the original image was at the correct center positioning, then the zoomed in images should also be at the correct place.  The issue affects the old and new versions of helioviewer.org.

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
A tiny fractional shift is still evident at the highest zoom level, but since this is much improved compared to previous behavior, this issue is marked as closed.
