### ISSUE TITLE
Shorten tweet text

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#48]
This is a typical tweet as created by the Tweet link

"Helioviewer.org - Solar and heliospheric image visualization tool http://bit.ly/1Lf2Syv"

Perhaps this should be shortened to

"from helioviewer.org http://bit.ly/1Lf2Syv @helioviewer"

**Comment by ddialer** [comment]
Fixed

**Comment by wafels** [comment]
The fix has "#helioviewer".  Most users seem to write "@helioviewer" in their tweets, so please could you change it to that for just now.

**Comment by ddialer** [comment]
I made requested changes:

```
from Helioviewer.org http://bit.ly/1LfeGAE via @helioviewer
```

**Comment by wafels** [comment]
fixed.
