### ISSUE TITLE
SOHO is behind two days

### ISSUE THREAD

**Issue by wireeye** [Helioviewer-Project/helioviewer.org#480]
Greetings, the past few days SOHO is two days behind, has this been brought to your attention?
Thanks in advance for addressing this issue 
 
Have a good day ;)

**Comment by dgarciabriseno** [comment]
Yes, thank you. We were having some issues on our data acquisition which have been resolved.
We're back up-to-date now.
https://api.helioviewer.org/status/

**Comment by dgarciabriseno** [comment]
Oh sorry, I was looking at SDO. SOHO will be updated shortly.

**Comment by dgarciabriseno** [comment]
SOHO is back up-to-date
