### ISSUE TITLE
Can anyone reproduse, "Full view" and ''Select area" is not working?

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/helioviewer.org#488]
Hi, from PC and phone, i can't select any area to create movie from upper right options "Full view" and ''Select area". It's only me or it's general problem? Thanks

**Comment by nbizien** [comment]
I have the same problem

**Comment by dgarciabriseno** [comment]
Sorry about this, looking into this now.

**Comment by dgarciabriseno** [comment]
This is fixed. The movie buttons work again.

**Comment by Anthrwpos** [comment]
Thank you.


________________________________
