### ISSUE TITLE
VSO: View does not update

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#49]
The first image shows the VSO image request at the most recent time.  Note that there is an ill-formatted date in yellow in the drop down on the right.
![screen shot 2016-02-09 at 4 38 42 pm](https://cloud.githubusercontent.com/assets/983575/12931679/ed83b5e4-cf4c-11e5-91aa-d2dd552128a4.png)

The second image shows what happens after jumping back 28 days.  The VSO thumbnails have not updated, and neither have the times.  Note that changing from AIA 304 to AIA 335 does work.  Adding or subtracting a layer from the data selector does also cause the VSO thumbnails to react.
![screen shot 2016-02-09 at 4 39 16 pm](https://cloud.githubusercontent.com/assets/983575/12931689/f91e8cda-cf4c-11e5-9ab9-4420762910c5.png)

**Comment by ddialer** [comment]
Fixed

**Comment by wafels** [comment]
Confirmed
