### ISSUE TITLE
Films are made duplicated

### ISSUE THREAD

**Issue by wydojeCie** [Helioviewer-Project/helioviewer.org#490]
Hello,
I don't know if it's some recent changes or a bug.
When I create any video from 1 hour to 12 hours, setting it to 1440p/30 fps, the end result is the same clip twice. 
So, for example,
if we set the movie to 1 hour, we get a clip with a length of +/- 3.3 seconds. 
Currently, these are the same two clips, and the whole thing lasts +/- 6.6 seconds.
:(
PS.
I forgot to add, it's about SDO
Best Regards

**Comment by dgarciabriseno** [comment]
I'll look into this and see what I can find out.

Can you share links to the movies you made that are coming out like this?

**Comment by dgarciabriseno** [comment]
This is fixed now. Thanks for letting me know!
This was due to a recent change, the frames selected for the movie were getting added to the movie twice. So each movie was itself 2 times.

**Comment by wydojeCie** [comment]
Hello
Sorry for the silence, I was away.
Thanks for fast reaction.
Unfortunately, I couldn't share the final effect of the films because they were all cut in half.

Here you can see in general:
[https://youtube.com/@wydojeCie_](url)

Best Regards
