### ISSUE TITLE
"Media error: Format(s) not supported or source(s) not found"

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/helioviewer.org#491]
Hi, today i noticed this: "Media error: Format(s) not supported or source(s) not found" when i try to play videos. You know why? Thanks

**Comment by dgarciabriseno** [comment]
Can you send me a link to the video you're seeing this on?

**Comment by Anthrwpos** [comment]
> Can you send me a link to the video you're seeing this on?

Sorry, it was my mistake, and i can't find a way to delete this. Is there any option?

**Comment by dgarciabriseno** [comment]
No problem, closed.

**Comment by Anthrwpos** [comment]
Hmm, i thought it was my mistake but this is second video that error appears, and the video doesn't play. (up left) You know that error?
![Untitled](https://github.com/Helioviewer-Project/helioviewer.org/assets/20747347/220048b9-70a2-4d36-84eb-91a1afcc8fbd)

[Link](https://helioviewer.org/?movieId=gb3n5), can you reproduce the error?

**Comment by dgarciabriseno** [comment]
Yea I see a problem. Let me look into it.

**Comment by dgarciabriseno** [comment]
Can you try playing the movie now? It should work.

**Comment by Anthrwpos** [comment]
> Can you try playing the movie now? It should work.

Now it's playing. Thanks. 

But another problem is (i don't know if it's from Helio page), i uploaded one video and then, i tried another one. While the other video it seems uploaded from the loading page ("your video should appear on YT in 1-2 mins"), it doesn't appear in my YT Creator Studio page. You know what is this?

**Comment by dgarciabriseno** [comment]
It may be related to this issue, it wasn't grabbing the right file name for some movies.

You can try uploading it again and see if it works.

**Comment by dgarciabriseno** [comment]
This is resolved.
