### ISSUE TITLE
SOHO is three days behind

### ISSUE THREAD

**Issue by wireeye** [Helioviewer-Project/helioviewer.org#492]
Greetings, I noticed today that the SOHO LASCO C2, and C3 filters are lagging three days behind. I will send an image capture from today, which is the 7th and when clicking the newest button beside the date and time at the top left of the screen, the date stays at 2023/10/4, I don't know if you are aware of this problem, or not. 

Thanks for your time in advance
![Helioviewer org - Solar and heliospheric image visualization tool 2023-10-07](https://github.com/Helioviewer-Project/helioviewer.org/assets/35879228/ba938ea7-f060-45d2-87bc-a7d48424459b)

**Comment by dgarciabriseno** [comment]
@wafels

**Comment by wafels** [comment]
Should be back up to date now.
