### ISSUE TITLE
Screen Capture yields an error 

### ISSUE THREAD

**Issue by GeminEyes** [Helioviewer-Project/helioviewer.org#493]
When trying to download a screen capture, the following comes up:

Helioviewer logo
Error: Invalid value for id. Please specify an integer value.
Last Updated: 1 January 1970

Not sure what this is, but it does NOT allow any downloading. The IAS-Helioviewer site is NOT affected by this.

**Comment by GeminEyes** [comment]
By the way, this just started a few days ago - not sure why. Runnng Edge browser with Win 11

**Comment by dgarciabriseno** [comment]
Thanks for reporting this. Looking into it now.

**Comment by dgarciabriseno** [comment]
There was a strange database issue causing this.

New screenshots taken from this point forward should be working again. Unfortunately the previous screenshots taken that gave this error aren't recoverable. I'll be pushing a change shortly that removes the broken screenshots from the list.

**Comment by GeminEyes** [comment]
Working now!

Sent from Mail for Windows

**Comment by dgarciabriseno** [comment]
Thanks for confirming
