### ISSUE TITLE
Datepicker for advanced movie options blocks out dates that it shouldn't

### ISSUE THREAD

**Issue by dgarciabriseno** [Helioviewer-Project/helioviewer.org#498]
<img width="495" alt="image" src="https://github.com/Helioviewer-Project/helioviewer.org/assets/94071409/d9320d1d-e2e6-4ba2-a061-cd4b40e7d35c">

This is using flatpickr, I think it's set to black out dates beyond the end date, but that makes it feel clunky.

Just need to remove the `maxDate` option on the flatpickr instance on `#movie-start-date` in `MovieManagerUI.js`.

**Comment by aayushtmG** [comment]
Hey, l will like to be assigned on this issue

**Comment by dgarciabriseno** [comment]
@aayushtmG all yours.
I'll send some info in a minute about running helioviewer on your pc. Still working on the docs.

**Comment by dgarciabriseno** [comment]
@aayushtmG Try following the instructions in the readme [here](https://github.com/Helioviewer-Project/helioviewer.org-docker/tree/compose) for running hv locally for testing.

**Comment by raptor-07** [comment]
Is this resolved? can I PR?

**Comment by dgarciabriseno** [comment]
Not resolved yet, you can PR

**Comment by raptor-07** [comment]
![image](https://github.com/Helioviewer-Project/helioviewer.org/assets/99596007/d888aa9f-570a-4bac-b4e4-298db8d694cf)

Not able to reproduce this!


EDIT:

![image](https://github.com/Helioviewer-Project/helioviewer.org/assets/99596007/8a5045ed-7e13-42af-a477-5637bfae16fa)

Reproduced it!

**Comment by raptor-07** [comment]
https://github.com/Helioviewer-Project/helioviewer.org/pull/512

Review PR please!

**Comment by dgarciabriseno** [comment]
This was completed with PR #512
