### ISSUE TITLE
SunPy VSO script is out of date

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#5]
SunPy's VSO client has changed, and so the automatically generated SunPy/VSO script should also change.

After the sunpy import statement the following import should be added

import astropy.units as u

After all the imports please add

if sunpy.**version**  < '0.6':
    raise ValueError('SunPy version 0.6 or higher is required to run this script.')

The Wave attribute is now unit-aware, and so has to have the appropriate unit.  In the script, the requested measurement should be multiplied by u.Angstrom.  An example is below.

vso_result_aia_304 = vso_client.query(vso.attrs.Time(tstart, tend), \
    vso.attrs.Instrument('aia'), vso.attrs.Wave(304 \* u.Angstrom, 304\* u.Angstrom))

**Comment by ddialer** [comment]
Fix was submitted to the Helioviewer.org API repository (Commit: 78b5537f76af681013687ad3b863a0a08effb47e)
