### ISSUE TITLE
Direct VSO link often produces no results.

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#50]
The VSO query that is meant to lead users to the exact image shown in the helioviewer window often does not result in any data (the image below shows the portion of the interface that displays this links).  Using the Solarsoft VSO client with the exact image time as shown yields precisely one dataset as expected

IDL> q = vso_search('2015/02/18 09:46:55', '2015/02/18 09:46:55', instrument='aia', wavelength='304')
Records Returned : JSOC : 1/1
Records Returned : SDAC_AIA : 0/0

I suspect that the difference between the two results is that the query to the VSO launched by beta3.helioviewer.org does not specify the number of seconds.  I think that VSO defaults to some value for seconds in the beta3.helioviewer.org launched query, and this leads to the wrong query being made.  It may be that the web interface to the VSO does not offer a query field - this should be checked.  If it does, then seconds should be passed in beta3.helioviewer.org launched query.  If not, then this should be brought to the attention of the VSO developers.  In the meantime, we could change the end search time in our query by adding on one minute.  This will ensure that the VSO query time range includes the time we are interested in.

![screen shot 2016-02-18 at 10 51 07 am](https://cloud.githubusercontent.com/assets/983575/13148984/89f18564-d62d-11e5-8913-0e395eb72a6d.png)

**Comment by ddialer** [comment]
Fixed. Unfortunately VSO links do not support seconds in parameters. Solution was to add 1 minute to the end date

**Comment by wafels** [comment]
Tested with AIA data, and the fix is confirmed using the link below.  The VSO query returns results, and the desired dataset is available in those results.

http://beta3.helioviewer.org/?date=2015-02-19T11:19:49.771Z&imageScale=0.60511022&centerX=-0.2723069855993652&centerY=-0.3328032344006348&imageLayers=%5BSDO,AIA,211,1,100%5D&eventLayers=%5BAR,all,1%5D,%5BCC,all,1%5D,%5BCD,all,1%5D,%5BCH,all,1%5D,%5BCJ,all,1%5D,%5BCE,all,1%5D,%5BCR,all,1%5D,%5BCW,all,1%5D,%5BEF,all,1%5D,%5BER,all,1%5D,%5BFI,all,1%5D,%5BFA,all,1%5D,%5BFE,all,1%5D,%5BFL,all,1%5D,%5BLP,all,1%5D,%5BOS,all,1%5D,%5BPG,all,1%5D,%5BSG,all,1%5D,%5BSP,all,1%5D,%5BSS,all,1%5D&eventLabels=true
