### ISSUE TITLE
Automatically generated SunPy download script

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#51]
The SunPy data download script will crash as in its current format.  I have included an original script and another script that details the edits that should be made to improve it.
[original.py.txt](https://github.com/Helioviewer-Project/helioviewer.org/files/136574/original.py.txt)
[edited.py.txt](https://github.com/Helioviewer-Project/helioviewer.org/files/136575/edited.py.txt)

**Comment by ddialer** [comment]
Fixed in https://github.com/Helioviewer-Project/api/commit/00b499c82f8218d80af4d3bec45421606ad4c790

**Comment by wafels** [comment]
I got the local path definition wrong.  Please change the existing definition to this below

local_path = '{:s}{:s}'.format(os.path.expanduser('~/'), '{file}')

**Comment by wafels** [comment]
Also, the section "Executing the script" needs to change from the existing form to the one attached
[execute_edit.txt](https://github.com/Helioviewer-Project/helioviewer.org/files/145486/execute_edit.txt)

**Comment by wafels** [comment]
Also, there appears to be an issue with SunPy itself.  The VSO downloader fails silently when data is not available. See https://github.com/sunpy/sunpy/issues/1331.  It may be that the SunPy script generation ability will have to be deprecated until the SunPy issue is fixed.

**Comment by ddialer** [comment]
Updated local_path definition and "Executing the script" section

**Comment by wafels** [comment]
I think data downloading via SunPy is not reliable enough at present to be included via helioviewer.org.  Also, SunPy 0.7 - which will probably be released in the next month - will implement some major changes to their data search and retrieval capability.  I think it is worth deprecating automated SunPy script generation until SunPy's data capabilities are stable.
