### ISSUE TITLE
Start of Interactive tutorial seems to be based on the position of the center of the Sun

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#510]
**Describe the bug**
If you start the interactive tutorial when the center of the Sun is outside the viewer window, then you can't step forward in the tutorial. The screen dims but you can't go anywhere else.

**To Reproduce**
1. Load an image
2. Move the center of the Sun outside the viewer window
3. Click on the "?" in the top right
4. Start the interactive tutorial

**Expected behavior**
The interactive tutorial should be independent of the location of the Sun center.

**Screenshots**
Sun center at center of viewport
![Screen Shot 2023-11-29 at 14 19 30](https://github.com/Helioviewer-Project/helioviewer.org/assets/983575/1045652a-cb62-4042-90ac-a03a7dd7c324)

Sun center outside viewport
![Screen Shot 2023-11-29 at 14 20 33](https://github.com/Helioviewer-Project/helioviewer.org/assets/983575/6d584013-e089-4e09-b620-c0a3103033d3)

**Comment by dgarciabriseno** [comment]
I shall do the simplest solution, move the sun to the center when the tutorial starts.
