### ISSUE TITLE
Is this safe or just a bug?

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/helioviewer.org#511]
""**Google has not verified this app 

The app requests access to sensitive information in your Google Account. Do not use this app until the developer (contact@helioviewer.org) has verified it with Google. Advanced settings**"

The image original is in Greek:
![Untitled](https://github.com/Helioviewer-Project/helioviewer.org/assets/20747347/09fa7977-c841-43be-a495-cfb3faa2f7db)

Thanks

**Comment by dgarciabriseno** [comment]
It's safe. Kind of a bug, but one that's not going to be fixed any time soon.

As it says, we haven't gone through google's verification process for the linking with youtube. I think there was a time that it worked correctly before I joined the team, but whatever verification was done probably expired. There are some other organizational things we have to deal with before we could work on this, so it'll be like this for a while.

You can try to proceed, but it might not let you upload anything.

**Comment by Anthrwpos** [comment]
Ok, thank you.
