### ISSUE TITLE
Why data from here is up to date: helioviewer.ias.u-psud.fr/, but helioviewer.org has stoped at 13.12.23?

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/helioviewer.org#515]
Hi, I noticed several times that the .org link sometimes has no data for some days but psud.fr is functional almost every day.  Are they different servers running the same page?  
Thanks

**Comment by dgarciabriseno** [comment]
Yes, they are different servers running Helioviewer.

The .org page has the latest changes and usually reflects the tip of this repository.
The psud.fr updates source changes less often.

**Comment by dgarciabriseno** [comment]
So to answer the title, I broke it here 😕 https://github.com/Helioviewer-Project/api/commit/a76607d4d26d9eec7382e74b8da4c05b79ee5681

**Comment by Anthrwpos** [comment]
What do you mean "you broke it here"?
________________________________
Από: Daniel Garcia Briseno ***@***.***>
Στάλθηκε: Δευτέρα, 18 Δεκεμβρίου 2023 5:34 μμ
Προς: Helioviewer-Project/helioviewer.org ***@***.***>
Κοιν.: Anthrwpos ***@***.***>; Author ***@***.***>
Θέμα: Re: [Helioviewer-Project/helioviewer.org] Why data from here is up to date: helioviewer.ias.u-psud.fr/, but helioviewer.org has stoped at 13.12.23? (Issue #515)


So to answer the title, I broke it here 😕 ***@***.***<https://github.com/Helioviewer-Project/api/commit/a76607d4d26d9eec7382e74b8da4c05b79ee5681>

**Comment by Anthrwpos** [comment]
And if there is such a frequent problem with .org, why isn't it merged with psud.fr? (I ask as an ignoramus on this matter.) You may know when there be new data form .org?
But what i don't understand, is why .fr has new data and not dot .org.
If one server makes changes less often and the other more often, why does one not have data and the other does? What's the difference between the two servers?

Thanks

________________________________
Από: Daniel Garcia Briseno ***@***.***>
Στάλθηκε: Δευτέρα, 18 Δεκεμβρίου 2023 5:31 μμ
Προς: Helioviewer-Project/helioviewer.org ***@***.***>
Κοιν.: Anthrwpos ***@***.***>; Author ***@***.***>
Θέμα: Re: [Helioviewer-Project/helioviewer.org] Why data from here is up to date: helioviewer.ias.u-psud.fr/, but helioviewer.org has stoped at 13.12.23? (Issue #515)


Yes, they are different servers running Helioviewer.

The .org page has the latest changes and usually reflects the tip of this repository.
The psud.fr updates source changes less often.

**Comment by dgarciabriseno** [comment]
> What do you mean "you broke it here"?

The code change I made caused the program which downloads new data to stop working. This is why helioviewer.org to fell behind the psud.fr page.

Helioviewer.org gets application updates first. For example helioviewer.org allows you to open movies in JHelioviewer. It also shows helioprojective (x, y) coordinates for your mouse. Both of these features are not available on the psud.fr version yet.

**Comment by dgarciabriseno** [comment]
Ironically, I made this breaking change while working on the system that's meant to make sure I don't break things.

**Comment by Anthrwpos** [comment]
What I want to ask is, on the .fr page, there is data before December 20th, but on the .org page, there are several hours of data missing in total. Can these hours of lost data be made up in some way or were lost forever?

Thanks
________________________________
Από: Daniel Garcia Briseno ***@***.***>
Στάλθηκε: Δευτέρα, 18 Δεκεμβρίου 2023 6:59 μμ
Προς: Helioviewer-Project/helioviewer.org ***@***.***>
Κοιν.: Anthrwpos ***@***.***>; Author ***@***.***>
Θέμα: Re: [Helioviewer-Project/helioviewer.org] Why data from here is up to date: helioviewer.ias.u-psud.fr/, but helioviewer.org has stoped at 13.12.23? (Issue #515)


What do you mean "you broke it here"?

The code change I made caused the program which downloads new data to stop working. This is why helioviewer.org to fell behind the psud.fr page.

Helioviewer.org gets application updates first. For example helioviewer.org allows you to open movies in JHelioviewer. It also shows helioprojective (x, y) coordinates for your mouse. Both of these features are not available on the psud.fr version yet.

**Comment by dgarciabriseno** [comment]
They are not lost, the missing data will be added shortly.

You can view coverage of what we have [here](https://api.helioviewer.org/statistics/bokeh/coverages/SDO_coverage.html)

**Comment by Anthrwpos** [comment]
When you say they will be added soon, what do you mean? Several times in quite old videos, the data doesn't exist (or lost) for long time.

Thanks
________________________________
Από: Daniel Garcia Briseno ***@***.***>
Στάλθηκε: Τετάρτη, 20 Δεκεμβρίου 2023 7:20 μμ
Προς: Helioviewer-Project/helioviewer.org ***@***.***>
Κοιν.: Anthrwpos ***@***.***>; Author ***@***.***>
Θέμα: Re: [Helioviewer-Project/helioviewer.org] Why data from here is up to date: helioviewer.ias.u-psud.fr/, but helioviewer.org has stoped at 13.12.23? (Issue #515)


They are not lost, the missing data will be added shortly.

You can view coverage of what we have here<https://api.helioviewer.org/statistics/bokeh/coverages/SDO_coverage.html>

**Comment by dgarciabriseno** [comment]
The data around 13.12.23 is available in helioviewer.org now.

For older dates, we would like to fill in any missing data. I just haven't prioritized it... If there is any specific time you're interested that is missing, let me know and I will make sure it gets added.
