### ISSUE TITLE
webpage *.org don't work

### ISSUE THREAD

**Issue by wydojeCie** [Helioviewer-Project/helioviewer.org#516]
Hello !
Is there any reason why the website helioviewer.org is not working? 
This has been going on since Saturday, maybe it's something serious? 
Perhaps only Europe - Poland does not see the site.

q=]
Regards

**Comment by wydojeCie** [comment]
omg i love You q=]

**Comment by dgarciabriseno** [comment]
We were having some issues with our server that was throwing us through a loop.

**Comment by dgarciabriseno** [comment]
It's back up now. data seems to have been coming in fine even though the page was inaccessible.
It might be a bit for HEK events to update.
