### ISSUE TITLE
Smooth zoom on helioviewer.org desktop

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#519]
Currently the desktop version of helioviewer.org zooms in through steps. You click on the zoom buttons and you zoom in and out.

More modern mapping applications allow for a smooth zoom (the mobile version of helioviewer.org has this). The desktop version does not have a smooth zoom. A smooth zoom on desktop would allow uses finer control over the images in the viewer window, presumably through a mouse wheel.

On moving to a smooth zoom some questions become apparent
- What happens to the current zoom in/out buttons?
- Can the movie/screenshot back-end handle this? (Apparently it already can based on the mobile experience)
- Do features and events move correctly, including celestial bodies and trajectory tracks?

**Comment by dgarciabriseno** [comment]
> What happens to the current zoom in/out buttons?

They do an animated zoom in/out. And they will still zoom in/out by 2x.

> Can the movie/screenshot back-end handle this? (Apparently it already can based on the mobile experience)

Yes, the front end just has to compute the viewport range properly, taking into account the current zoom. There was also an issue with positioning the bar/earth scale box which I'm fixing with this patch.

> Do features and events move correctly, including celestial bodies and trajectory tracks?

Features and events move correctly, celestial bodies TBD. They're not showing for me on Helioviewer.org, this might be a separate issue.

I'll have the zoom changes up on beta soon.

**Comment by dgarciabriseno** [comment]
Smooth zoom is available on https://beta.helioviewer.org/ for testing.

**Comment by Anthrwpos** [comment]
> > What happens to the current zoom in/out buttons?
> 
> They do an animated zoom in/out. And they will still zoom in/out by 2x.
> 
> > Can the movie/screenshot back-end handle this? (Apparently it already can based on the mobile experience)
> 
> Yes, the front end just has to compute the viewport range properly, taking into account the current zoom. There was also an issue with positioning the bar/earth scale box which I'm fixing with this patch.
> 
> > Do features and events move correctly, including celestial bodies and trajectory tracks?
> 
> Features and events move correctly, celestial bodies TBD. They're not showing for me on Helioviewer.org, this might be a separate issue.
> 
> I'll have the zoom changes up on beta soon.

Hi, 

1: The keyboard button ("-" and ''+'') doesn't work anymore to zoom in and out (was an easy way, at least for me). (as it is [here](https://helioviewer.ias.u-psud.fr/))
2:, The wheel (on mouse) for zoom out not working, only for zoom in.
3: The center button sometimes doesen't center the image.
4: Why the smooth way to zoom in and out for desktop? (i mean, what the purpose?) This feature is permant?

Thanks

**Comment by dgarciabriseno** [comment]
> 1: The keyboard button ("-" and ''+'') doesn't work anymore to zoom in and out (was an easy way, at least for me). (as it is [here](https://helioviewer.ias.u-psud.fr/))

Thanks, I didn't notice there were keyboard shortcuts for this, I'll add them back in.

> 2: The wheel (on mouse) for zoom out not working, only for zoom in.

That's strange, what browser are you using? And just a plain mouse?

> 3: The center button sometimes doesen't center the image.

I think this might happen if zoom in near the edges of the sun, it's an issue I'll have to look into.

> 4: Why the smooth way to zoom in and out for desktop? (i mean, what the purpose?) This feature is permant?

The purpose is to give HV a more modern feel.

I'll roll back the change for now and try to do some more testing. If the mouse wheel doesn't zoom out I think that's a pretty big problem.

**Comment by Anthrwpos** [comment]
Hi,

2. I'm using Google Chrome and yes, plain mouse. In the other website helioviewer ".fr" the wheel zoom in, it's working. Test it there to see it if you want.

4. About the smooth zoom, I just asked this because I don't feel (it's only my opinion of course), there is purpose for this (I mean the step by step zoom is more direct, the smooth zoom at least for me it's take more *seconds* to zoom). But if I noticed right, this smooth zoom it zoomed more into the Sun or the more zoom is a different thing?

But if this helps, try to test the .fr website first for what I'm saying.

Thank you.

________________________________
Από: Daniel Garcia Briseno ***@***.***>
Στάλθηκε: Σάββατο, 27 Ιανουαρίου 2024 6:50 μμ
Προς: Helioviewer-Project/helioviewer.org ***@***.***>
Κοιν.: Anthrwpos ***@***.***>; Comment ***@***.***>
Θέμα: Re: [Helioviewer-Project/helioviewer.org] Smooth zoom on helioviewer.org desktop (Issue #519)


1: The keyboard button ("-" and ''+'') doesn't work anymore to zoom in and out (was an easy way, at least for me). (as it is here<https://helioviewer.ias.u-psud.fr/>)

Thanks, I didn't notice there were keyboard shortcuts for this, I'll add them back in.

2: The wheel (on mouse) for zoom out not working, only for zoom in.

That's strange, what browser are you using? And just a plain mouse?

3: The center button sometimes doesen't center the image.

I think this might happen if zoom in near the edges of the sun, it's an issue I'll have to look into.

4: Why the smooth way to zoom in and out for desktop? (i mean, what the purpose?) This feature is permant?

The purpose is to give HV a more modern feel.

I'll roll back the change for now and try to do some more testing. If the mouse wheel doesn't zoom out I think that's a pretty big problem.

**Comment by dgarciabriseno** [comment]
@Anthrwpos Can you clarify some things?

> 2:, The wheel (on mouse) for zoom out not working, only for zoom in.

I am testing with a different mouse, when I scroll down to zoom out, it does zoom out, but not as much as zooming in. Is this what you experienced?

> 3: The center button sometimes doesn't center the image.

Did the sun move and appear off-center, or did it not move at all?

You can test it here: [beta.helioviewer.org](https://beta.helioviewer.org)

**Comment by Anthrwpos** [comment]
> @Anthrwpos Can you clarify some things?
> 
> > 2:, The wheel (on mouse) for zoom out not working, only for zoom in.
> 
> I am testing with a different mouse, when I scroll down to zoom out, it does zoom out, but not as much as zooming in. Is this what you experienced?
> 
> > 3: The center button sometimes doesn't center the image.
> 
> Did the sun move and appear off-center, or did it not move at all?
> 
> You can test it here: [beta.helioviewer.org](https://beta.helioviewer.org)

2. Yes, and sometimes It doesn't make zoom in at all.

3. Both, when it's off center, and trying to center it, sometimes the sun is in center, but not all the time.

**Comment by dgarciabriseno** [comment]
@Anthrwpos Can you test [beta.helioviewer.org](https://beta.helioviewer.org/)? The problems should be fixed.

- Zooming in and out with the mouse wheel works and is fast.
- Zooming with + and - work.
- Centering does not leave the sun off-center.

**Comment by Anthrwpos** [comment]
> @Anthrwpos Can you test [beta.helioviewer.org](https://beta.helioviewer.org/)? The problems should be fixed.
> 
> * Zooming in and out with the mouse wheel works and is fast.
> * Zooming with + and - work.
> * Centering does not leave the sun off-center.

Hi, now it's like before. 

''Zooming in and out with the mouse wheel works and is fast (step by step as it was).''✅
''Zooming with + and - .''✅
''Centering does not leave the sun off-center.''✅

Is this gonna stay like this or you will change it again?

Thanks

**Comment by dgarciabriseno** [comment]
I expect it to stay like this unless other issues are reported.

**Comment by dgarciabriseno** [comment]
This update is live.

**Comment by Anthrwpos** [comment]
> I expect it to stay like this unless other issues are reported.

Hi, did you change to smooth zoom again?

**Comment by dgarciabriseno** [comment]
Yes, sorry. I think I misread your response before. I intend for smooth zoom to be norm.

**Comment by Anthrwpos** [comment]
> Yes, sorry. I think I misread your response before. I intend for smooth zoom to be norm.

With this: "I expect it to stay like this unless other issues are reported." You meant that you wanted to change it to smooth or step by step?
Smooth zoom, it's not very usefull (for me at least), i mean, the step by step it's more direct, ''smooth'' it's slower.

**Comment by dgarciabriseno** [comment]
I meant I wanted to change it to smooth. There were some issues with the first update that are fixed now.
The mouse wheel issue is fixed and the +/- keyboard shortcuts are back.

Having it be more continuous gives you more accuracy in controlling the viewport, and it shouldn't really be any slower than before.

**Comment by Anthrwpos** [comment]
> I meant I wanted to change it to smooth. There were some issues with the first update that are fixed now.
> The mouse wheel issue is fixed and the +/- keyboard shortcuts are back.
> 
> Having it be more continuous gives you more accuracy in controlling the viewport, and it shouldn't really be any slower than before.

First, smooth zoom is slower than step by step, and I think it loses centering during the zoom process, before the zoom is complete (during), if you move the image, it goes off center and you lose it. 
And I also noticed something else, when you zoom out enough (and center before zooming again), zooming with the mouse or keys doesn't zoom to the center of the Sun image you have, but to a dark spot for some reason. Honestly, for me it is not a good experience with smooth zoom, either from a PC or a phone.
In general, this change that has been made, seems heavier in the process.

Thanks.

**Comment by dangarbri** [comment]
> if you move the image, it goes off center and you lose it.

Would you be able to provide some screenshots of how you lose it? I'm not sure I understand what you mean.

The off-centering during zoom that you see is because it is zooming in wherever your mouse is pointing. If you hover the pointer over a specific spot and zoom with the mouse wheel, that becomes the focal point even if it is not on the disc of the sun. So if you place your mouse off of the sun and zoom, you will zoom into an area off of the sun.

**Comment by Anthrwpos** [comment]
> > if you move the image, it goes off center and you lose it.
> 
> Would you be able to provide some screenshots of how you lose it? I'm not sure I understand what you mean.
> 
> The off-centering during zoom that you see is because it is zooming in wherever your mouse is pointing. If you hover the pointer over a specific spot and zoom with the mouse wheel, that becomes the focal point even if it is not on the disc of the sun. So if you place your mouse off of the sun and zoom, you will zoom into an area off of the sun.

And what exactly is the point of zooming to where the mouse is pointing and not to the command given by the user by pressing the center icon?  With the previous settings before the smooth zoom, by pressing the center icon to center the sun, wherever I had the mouse and choosing + or - or the wheel, it zoomed right into the sun.

**Comment by dangarbri** [comment]
When you press the center icon, it will always center the sun to the center of the viewport.

If you are zoomed out so you can see the full disc, then you can point anywhere and zoom to that point, you don't need to drag the region of interest to the center of the screen before zooming.

**Comment by dgarciabriseno** [comment]
@Anthrwpos This one's for you. You can re-enable the previous step zoom behavior by doing the following:

1. Click the settings cog in the upper right corner
<img src="https://github.com/Helioviewer-Project/helioviewer.org/assets/94071409/ea7c85fc-93d7-43bc-ba44-ee6815275d43" width="400"/>

2. Change Zoom Type to "step" and Zoom Focus to "Focus on center"

<img src="https://github.com/Helioviewer-Project/helioviewer.org/assets/94071409/07d937aa-062b-49ef-8b06-97d9be3dd094" width="400"/>

**Comment by Anthrwpos** [comment]
> @Anthrwpos This one's for you. You can re-enable the previous step zoom behavior by doing the following:
> 
> 1. Click the settings cog in the upper right corner
> 
> <img alt="" width="400" src="https://private-user-images.githubusercontent.com/94071409/304221034-ea7c85fc-93d7-43bc-ba44-ee6815275d43.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTA1NzgsIm5iZiI6MTcwODMxMDI3OCwicGF0aCI6Ii85NDA3MTQwOS8zMDQyMjEwMzQtZWE3Yzg1ZmMtOTNkNy00M2JjLWJhNDQtZWU2ODE1Mjc1ZDQzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAyMzc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMWYwY2JhNzJmZWU1YjBhYTFkN2I1OWExYjI0ZDlhNjFkODMzODQ1Y2Y3NGY0MGFiMmYzZjc4ZTA0ZWFmNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mLeJqbEPwwkYUr1le14hewgl2_j1aJh_wYpJqi83TFk">
> 2. Change Zoom Type to "step" and Zoom Focus to "Focus on center"
> 
> <img alt="" width="400" src="https://private-user-images.githubusercontent.com/94071409/304221001-07d937aa-062b-49ef-8b06-97d9be3dd094.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTA1NzgsIm5iZiI6MTcwODMxMDI3OCwicGF0aCI6Ii85NDA3MTQwOS8zMDQyMjEwMDEtMDdkOTM3YWEtMDYyYi00OWVmLThiMDYtOTdkOWJlM2RkMDk0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAyMzc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMDYyZjkzM2QxYTZkMTMwNzZkNzU1NDQ4M2M5YjYzY2Y0MDQ2ZDdiNWQ3ZDE4MjhlNTAxYzA2YzU1MGM2Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.01HoNnVltoS1pShMRRn0JRqeyF-yqVaWVNRxx9Aa3Vw">

Hi, thanks for this. I this was an old setting or you add it recently?

**Comment by dgarciabriseno** [comment]
This is a new setting.

**Comment by dgarciabriseno** [comment]
Closing as complete
