### ISSUE TITLE
Need an 'About' notification

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#53]
Helioviewer.org version 2.4.0 has an "About" notification that is a useful place to give some very basic details about helioviewer.org and credits for support.  An about notification should be included in helioviewer.org version 3.0.  The text should be amended as follows.  Note that all the institutions/missions under the "Credits" section should have links, and these can be found in version helioviewer.org 2.4.0.  As other services and support are used, this about notification will be updated.  The "About" text should also be included in the "README.txt" file of https://github.com/Helioviewer-Project/helioviewer.org.

Text is as follows:

Helioviewer.org is part of the [Helioviewer Project](https://github.com/Helioviewer-Project), an open-source project for the visualization of solar and heliospheric data. The Helioviewer Project is funded by ESA and NASA. For more information, please visit our [wiki](http://wiki.helioviewer.org/wiki/Main_Page).

Credits:
SDO (NASA), SOHO (ESA/NASA), STEREO (NASA), PROBA2 (ESA), Yohkoh (JAXA/NASA/PPARC), GSFC, Royal Observatory of Belgium, LMSAL, SDAC, Stanford University, MSU/SDO-FFT.

**Comment by wafels** [comment]
Whoops!  There is an 'About' already.  I think having an explicit 'About' link at the same level as "User's Guide" etc would make it easier to find basic information about helioviewer.org and the Helioviewer Project.

**Comment by ddialer** [comment]
Fixed

**Comment by wafels** [comment]
Confirmed.
