### ISSUE TITLE
Warn the user when the observation time is outside the time range the instrument was operating

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#535]
Helioviewer.org color codes image times to indicate when an image was taken. Red denotes that the observation time is very different from the image time. This feature can be enhanced by popping up a warning to the user that tells them that the observation time is outside the time range the instrument was operating. This will help prevent the misinterpretation of images.

For full flexibility, every source ID would have to have its own start time and end time.

**Comment by wafels** [comment]
We should probably use the times used in the status page - https://api.helioviewer.org/status/ . This would be easiest since we have this information already.  Messages we could be something like "Earliest available Helioviewer image for SDO AIA 94 is at 2020/06/02 00:05:33" and "Most recent Helioviewer image for SDO AIA 94 is at 2024/02/26 15:01:11"

**Comment by dgarciabriseno** [comment]
Would this popup just be for when the observation time is outside that range?

If the observation time is within the operation range, but we don't have data, the popup should not appear, right?

**Comment by wafels** [comment]
> Would this popup just be for when the observation time is outside that range?
> 
> If the observation time is within the operation range, but we don't have data, the popup should not appear, right?

Yes, that is correct.

**Comment by dgarciabriseno** [comment]
Implemented in v4.4.0
