### ISSUE TITLE
Timeline: Carrington number labels mistakenly appear above timeline information pop-up

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#54]
The attached screenshot illustrates the problem.  The timeline information pop-up should appear above the Carrington number labels.

![screen shot 2016-02-18 at 2 00 39 pm](https://cloud.githubusercontent.com/assets/983575/13154683/292a87ec-d648-11e5-8f1d-f76eb29287f2.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed
