### ISSUE TITLE
Screenshots have the Earth in the wrong place

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#55]
The first screenshot illustrates where I put the Earth

<img width="1258" alt="screen shot 2016-02-24 at 2 13 27 pm" src="https://cloud.githubusercontent.com/assets/983575/13297622/384bb06c-db01-11e5-81bd-53c0e315e9ee.png">

The second illustrates where the helioviewer.org app put the Earth using the Screenshot function.  The Earth is in the wrong place.

![2016_02_11_13_06_06_aia_304-1](https://cloud.githubusercontent.com/assets/983575/13297658/62b23092-db01-11e5-9af8-b59f4fe1ed65.png)

**Comment by wafels** [comment]
The above screenshots were taken using the "Full Viewport" functionality.  The same issue occurs when using the "Select Area" functionality - see attached.

(1) request

<img width="1147" alt="screen shot 2016-02-24 at 3 57 51 pm" src="https://cloud.githubusercontent.com/assets/983575/13300729/83b851f0-db0f-11e5-8f89-14e1ea43aeab.png">

(2) what was returned

![2016_02_24_20_50_45_aia_304 1](https://cloud.githubusercontent.com/assets/983575/13300737/8cdbc348-db0f-11e5-8121-229049c6e0fb.png)

**Comment by ddialer** [comment]
Fixed

**Comment by wafels** [comment]
Confirmed
