### ISSUE TITLE
CCMC DONKI notifications in the wrong place

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#553]
**Describe the bug**
The CCMC DONKI notifications look to be in the wrong place:

**To Reproduce**
See the attached screenshot

**Expected behavior**
The DONKI notifications are in the right place. They should not be close to the meridian.

**Screenshots**
<img width="1250" alt="Screen Shot 2024-05-11 at 5 54 32 PM" src="https://github.com/Helioviewer-Project/helioviewer.org/assets/983575/729136e0-b92e-41ae-8fbd-95b91641c4b9">

**Comment by dgarciabriseno** [comment]
Is this still happening now?

**Comment by dgarciabriseno** [comment]
This is working now.
