### ISSUE TITLE
[User Bug Report] - Google blocking Helioviewer - unable to upload to Youtube

### ISSUE THREAD

**Issue by Not-Sure-Whats-Going-On** [Helioviewer-Project/helioviewer.org#554]
**Describe the bug**
Unable to upload videos created by Helioviever to Youtube because Google blocks access "for my security."
Using Linux Mint 21.3 and Librewolf browser on desktop to access helioviewer[dot]org.  Blocking happens both with and without using a VPN and with and without browser plugins enabled. 

**To Reproduce**
1. Create a video.
2. Click on 'Upload video to Youtube'
3. Choose Google account in popup window.
4. See error popup "This app is blocked.  This app tried to access sensitive info in your Google Acount.  To keep your account safe Google blocked this access"

**Expected behavior**
The video is published on my Youtube channel and shared with other Helioviewer users.  This used to work although I haven't done it for a while.

**Screenshots**
![blocked](https://github.com/Helioviewer-Project/helioviewer.org/assets/93087918/cc9cf1c4-b14d-4dd5-b7a0-8740da106101)

**Comment by dgarciabriseno** [comment]
This is a problem on our side. We have to work with the google to unblock this.

**Comment by Not-Sure-Whats-Going-On** [comment]
OK thanks - good luck!
