### ISSUE TITLE
Feature/event pins not in actual feature

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#56]
Occasionally the feature/event pin is not in the area of the feature.  This is probably due to the algorithm used to calculate where the pin should be.  The screenshots below illustrate the issue

![2016_02_11_13_06_06_aia_304](https://cloud.githubusercontent.com/assets/983575/13297907/9d3e81ba-db02-11e5-9b7d-91fb13e1f409.png)

<img width="1258" alt="screen shot 2016-02-24 at 2 13 27 pm" src="https://cloud.githubusercontent.com/assets/983575/13297837/5480cd2a-db02-11e5-865b-2748b48988a6.png">

**Comment by ddialer** [comment]
Implemented as a PHP library based on https://github.com/mapbox/polylabel. 
A fast algorithm for finding polygon pole of inaccessibility, the most distant internal point 
from the polygon outline, 
Useful for optimal placement of a text label on a polygon.

Improvements can be seen on the screenshot (displaying event from original post):
<img width="562" alt="screen shot 2017-06-13 at 4 22 09 pm" src="https://user-images.githubusercontent.com/403007/27102823-9fe921d6-5054-11e7-9c50-cf730968e3f3.png">

**Comment by wafels** [comment]
Very nice! Confirmed for ARs and CHs, sunspot detections and filament detections.
