### ISSUE TITLE
Current movies being processed do not show a "Processing" status

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#57]
The most recent request to make a movie do not show a "processing" status.  Earlier movies that are incomplete do show a "processing" status.  The lack of status is confusing to the user.  See attached screenshot
<img width="1234" alt="screen shot 2016-02-24 at 2 37 30 pm" src="https://cloud.githubusercontent.com/assets/983575/13298345/686b5cc2-db04-11e5-8d65-b2ac20b84a95.png">

**Comment by wafels** [comment]
refreshing the page yields the "Processing" status
<img width="1174" alt="screen shot 2016-02-24 at 2 42 03 pm" src="https://cloud.githubusercontent.com/assets/983575/13298473/e293721e-db04-11e5-8f7b-d2c26e594992.png">

**Comment by ddialer** [comment]
Fixed

**Comment by wafels** [comment]
confirmed
