### ISSUE TITLE
Movies have Earth scale in the wrong place

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#59]
Just like the screenshot issue #55 , the Earth scale is in the wrong place.  Created using the "Full Viewport" option.  

Here is where I put the Earth
<img width="1221" alt="screen shot 2016-02-24 at 4 55 13 pm" src="https://cloud.githubusercontent.com/assets/983575/13302948/79d219fe-db1a-11e5-99de-5482559623ea.png">

And the attached movie illustrates the issue (I had to compress it from the original large version, and put it in a zip file to get it uploaded to github).
[ipod touch version 2014_02_24_07_43_31_2014_02_24_10_42_55_AIA_304-hq.m4v.zip](https://github.com/Helioviewer-Project/helioviewer.org/files/145543/ipod.touch.version.2014_02_24_07_43_31_2014_02_24_10_42_55_AIA_304-hq.m4v.zip)

**Comment by ddialer** [comment]
Fixed

**Comment by wafels** [comment]
Fixed

**Comment by wafels** [comment]
Re-opening because does not seem to be fixed:  see screen shots
actual:
![screen shot 2016-02-29 at 10 51 34 am](https://cloud.githubusercontent.com/assets/983575/13399662/78ee55dc-ded2-11e5-860e-2add4ffe21c3.png)
after asking for screenshot
![2016_02_29_15_51_13_aia_211](https://cloud.githubusercontent.com/assets/983575/13399677/8bb4a540-ded2-11e5-8a29-6f0b368366ff.png)

**Comment by wafels** [comment]
Can't reproduce, so closing.

**Comment by wafels** [comment]
Looks like this has come back:

<img width="1277" alt="screen shot 2016-03-24 at 7 30 52 pm" src="https://cloud.githubusercontent.com/assets/983575/14034192/56e5076e-f1f7-11e5-9a4d-352cc74b66be.png">
![2016_03_24_17_15_24_aia_304](https://cloud.githubusercontent.com/assets/983575/14034202/6420790e-f1f7-11e5-9d18-8c6da82c863f.png)

**Comment by wafels** [comment]
no complaints after one week of helioviewer.org 3.0, so closing
