### ISSUE TITLE
[User Bug Report] - Can't upload movies throught Helioviewer. (for 9 days)

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/helioviewer.org#592]
Hi, for 9 days now, i can't, and as i see noone can't upload any movie from helioviewer. Is the page down for uploading or soemthing else? Thanks

**Comment by dgarciabriseno** [comment]
Thanks for reporting this, it is tentatively fixed.
You should be able to upload to youtube now.

**Comment by Anthrwpos** [comment]
> Thanks for reporting this, it is tentatively fixed. You should be able to upload to youtube now.

Thanks for this. 

One question: You are not able to see if there is a problem on the page? I mean, why need to mention it before you fixed it? There is no something like ''auto notification'' when something is wrong? It was 9 days without any news about it. Just asking. Thanks

**Comment by dangarbri** [comment]
Great question. The fastest way to get us to notice an issue is to email us or open an issue here.

There's no auto notification to tell us something is wrong. The server does log errors, but a lot of the errors it logs aren't real errors (this is something we need to fix). This makes it hard to find real problems just from looking at logs. But when you report something, we use the logs to identify and fix the problem.

We have started working on more automated testing, but we don't have a test for the youtube feature. I will add a test when I check in the patch for this.

**Comment by dgarciabriseno** [comment]
@Anthrwpos are you able to upload movies?

**Comment by Anthrwpos** [comment]
> @Anthrwpos are you able to upload movies?

Yes. I just tried it. All good. Thanks.
