### ISSUE TITLE
Movie Processing Stuck at 0%

### ISSUE THREAD

**Issue by pereznn** [Helioviewer-Project/helioviewer.org#594]
**Describe the bug**
Attempting to make a video of the SDO HMI magnetogram for any time period in 2014 will result in a video that is permanently stuck at 0% (rarely 2%), and then after a few hours a warning will pop up saying that there is not information for that timespan (which is not true, as there are observations for the timespans selected). 

**To Reproduce**
1. Select SDO as your observatory, HMI as your instrument, and magnetogram as your measurement.
2. Attempt to make a movie for any time period of any length during 2014.
3. See error.

**Expected behavior**
Videos for 2010-2013 have been made without any issues. 2014 should be the same.

**Comment by dgarciabriseno** [comment]
Hi @pereznn, can you use the share viewport button to make a link I can test with?

I was able to make an HMI magnetogram video in 2014. It might have something to do with the selected events or other options set.

**Comment by pereznn** [comment]
Here's the link. https://helioviewer.org/load/92567c7911b1e09fb6f6bd4a2af29133a30acfc109e9ad6d86f126c0da1c550c

**Comment by dgarciabriseno** [comment]
@pereznn  This should be working now, can you try again?

**Comment by pereznn** [comment]
It works now! Thank you so much.

**Comment by dgarciabriseno** [comment]
Great!
