### ISSUE TITLE
SSL certificate expired?

### ISSUE THREAD

**Issue by dwarrilow** [Helioviewer-Project/helioviewer.org#595]
Hi,
I'm getting this error from your site:
Your connection is not private
Attackers might be trying to steal your information from helioviewer.org (for example, passwords, messages or credit cards). [Learn more](chrome-error://chromewebdata/#)
net::ERR_CERT_DATE_INVALID

![image](https://github.com/user-attachments/assets/93c2e5bf-9cf9-4313-b2ea-2eeaaf3317be)

**Comment by dangarbri** [comment]
Go directly to https://helioviewer.org and it should work.

We had (have?) some issues with search engines pointing to a partial page in our site.

**Comment by dgarciabriseno** [comment]
Closing since I'm not sure this is a general issue.
Our cert hasn't changed recently. The current cert is valid between July 1 - Sep 29.
I do think it is weird that you got this error.
@dwarrilow please re-open this if you're still having this problem.

**Comment by dwarrilow** [comment]
Thanks; I'll check. It seems to be OK on this computer, but I need to look at my other one where I identified the issue. I'll let you know if there's still a problem.

Cheers,

David.


David Warrilow

     On Thursday 1 August 2024 at 03:53:59 am AEST, Daniel Garcia Briseno ***@***.***> wrote:  
 
 


Closing since I'm not sure this is a general issue.
Our cert hasn't changed recently. The current cert is valid between July 1 - Sep 29.
I do think it is weird that you got this error.
@dwarrilow please re-open this if you're still having this problem.
