### ISSUE TITLE
Weird extra colours appearing in scale tools

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#60]
If you look closely where the scale (Earth/bar) tools are, you can see that there are some extra colours appearing.  They should not be there.

![2016_02_22_15_07_01_aia_211-5](https://cloud.githubusercontent.com/assets/983575/13398615/206e77f2-decd-11e5-86c0-d74c37ae03be.png)
![2016_02_22_15_07_01_aia_211-6](https://cloud.githubusercontent.com/assets/983575/13398616/20733e40-decd-11e5-924c-f8df20edb11f.png)

**Comment by ddialer** [comment]
Fixed in #63

**Comment by wafels** [comment]
Confirmed.
