### ISSUE TITLE
No image. File list refers to the JSON page... looks like a maintenance break?

### ISSUE THREAD

**Issue by wydojeCie** [Helioviewer-Project/helioviewer.org#601]
Hello,
I would like to ask if you are on a maintenance break?
If it turns out that you are, how long will it take, more or less?
I was just about to download the files and then poof and it disappeared.
There is no image, but the list of files to download still exists, only that after clicking we get a redirect and the following message:

" /var/www/api.helioviewer.org/docroot/index.php:151 - Uncaught Error: Class "Redis" not found in /var/www/api.helioviewer.org/docroot/index.php:151\nStack trace:\n#0 /var/www/api.helioviewer.org/docroot/index.php(65): loadModule()\n#1 {main}\n thrown "

Best regards

**Comment by wydojeCie** [comment]
Thank You :)

**Comment by dgarciabriseno** [comment]
Hello, sorry about that. Everything is operational again.

**Comment by dgarciabriseno** [comment]
Doing some maintenance, yes. We weren't expecting it to break 👀
