### ISSUE TITLE
movies are not processing completely

### ISSUE THREAD

**Issue by wydojeCie** [Helioviewer-Project/helioviewer.org#602]
Sorry to write again but I think the movies are not processing completely.
That is, I select the date/time, press "ok".
The file is "queued" jumps to process 0% and stays that way.
I'm afraid it's on my side, something is wrong. But I restarted the browser and still the same.
Regards :)

**Comment by wydojeCie** [comment]
I forgot to write, it's about SDO with a combination of three layers AIA 94/193/304, if that makes any difference.

**Comment by dgarciabriseno** [comment]
Don't be sorry, it's not on your side.

**Comment by dgarciabriseno** [comment]
Try making another movie now. The ones stuck at 0 will probably stay at 0, or error out.

**Comment by wydojeCie** [comment]
I ran the two files again and something started working

**Comment by wydojeCie** [comment]
ohh :) 
Mr Garcia You Are The Best 
@Edit Works !!

**Comment by wydojeCie** [comment]
It works... Thank you very much, you can close the topic. 
Regards
