### ISSUE TITLE
HV does not process files

### ISSUE THREAD

**Issue by wydojeCie** [Helioviewer-Project/helioviewer.org#603]
Hello, and sorry to report something again.

The thing is that HV behaves as if it has lost access to the databases, because every time I queue another movie, I get an error after a while. A moment earlier I was creating movies from the same time frame and everything worked.

Sorry to bother you on a Sunday.

**Comment by wydojeCie** [comment]
by the way, is there a place where you post planned outages, maintenance, etc.? 
Where I could read what's going on so I don't have to write unnecessarily.
Regards

**Comment by mudhoney** [comment]
Hi @wydojeCie 

Thank you for reporting this issue. We are currently working on a fix and will update you here once it's resolved.

For information on planned outages and maintenance, please refer to the following URL: 
[Helioviewer Project - Planned Outages and Maintenance](https://helioviewer-project.github.io/).

**Comment by wydojeCie** [comment]
Yes sir,
Thank you for your answer.
PS.
I forgot about the time difference, and I got a little carried away with this ticket.

**Comment by mudhoney** [comment]
@wydojeCie, 
We apologize for any inconvenience this issue may cause. 
Unfortunately, we won't be able to resolve the issue until Monday, August 12th, 2024 (EDT). We will provide an update here as soon as it is fixed.

**Comment by wydojeCie** [comment]
Ok, no point in wasting Sunday.
In that case, I keep my fingers crossed that you will be able to solve the problem at the beginning of the week.
Have a peaceful day. q=]

**Comment by mudhoney** [comment]
Thank you very much, you too have a great day!

**Comment by wydojeCie** [comment]
Haha... works ...
Thank You 
Thank You 
Thank You


PS.
I've launched three files, I'll see if they process. The percentages are rising, so I guess it's good.

*works, it makes clips

**Comment by wydojeCie** [comment]
![great job](https://github.com/user-attachments/assets/aa9ad45c-27bd-4ac1-b8c7-95becbe7ca44)
Great Job 
q=]

**Comment by mudhoney** [comment]
Thank you for the validation @wydojeCie 
We apologize if this issue cause any inconvenience for you. 
Have a great day!

**Comment by wydojeCie** [comment]
![Tło YT  Bender with beast](https://github.com/user-attachments/assets/86952fb9-400f-4505-8080-2bcc57a65ea6)
For you folks. With the best wishes. q=]
