### ISSUE TITLE
[User Bug Report] - <issue title> 3/4 of image goes missing

### ISSUE THREAD

**Issue by wireeye** [Helioviewer-Project/helioviewer.org#607]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
When I zoom in, or out of an image, only 1/4 of the image is shown. I have to refresh the page to get the whole image again, which means if I have already set the parameters, to record a video, I then will need to go back in to reset them. 
Thanks for your time, and effort in this matter
![Helioviewer org - Solar and heliospheric image visualization tool 2024-09-08](https://github.com/user-attachments/assets/c6d4e99a-ebde-4bf9-aa86-7aebd25af60a)

**Comment by dgarciabriseno** [comment]
I will investigate

**Comment by dgarciabriseno** [comment]
@wireeye I just deployed an update which should fix this. Please re-open if you're still experiencing this.
