### ISSUE TITLE
Movie link feature returns viewport link instead of actual movie link

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#61]
I made a movie, and wanted to copy the link - see attached screenshot.  Doing Command-C to copy the link I got the link to the viewport instead:

http://beta3.helioviewer.org/?date=2016-02-22T15:07:01.916Z&imageScale=1.21022044&centerX=-289.24268516&centerY=-87.13587168000001&imageLayers=%5BSDO,AIA,211,1,100%5D&eventLayers=%5BAR,all,1%5D,%5BCC,all,1%5D,%5BCD,all,1%5D,%5BCH,all,1%5D,%5BCJ,all,1%5D,%5BCE,all,1%5D,%5BCR,all,1%5D,%5BCW,all,1%5D,%5BEF,all,1%5D,%5BER,all,1%5D,%5BFI,all,1%5D,%5BFA,all,1%5D,%5BFE,all,1%5D,%5BFL,all,1%5D,%5BLP,all,1%5D,%5BOS,all,1%5D,%5BPG,all,1%5D,%5BSG,all,1%5D,%5BSP,all,1%5D,%5BSS,all,1%5D&eventLabels=true

![screen shot 2016-02-29 at 10 17 08 am](https://cloud.githubusercontent.com/assets/983575/13398741/ac3a6264-decd-11e5-8a96-b316fc7d6fb5.png)

**Comment by ddialer** [comment]
Fixed.

**Comment by wafels** [comment]
Confirmed.
