### ISSUE TITLE
Export movies as animated gifs?

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#62]
Short animated gifs are popular.  We could add the ability to export movies as animated gifs of fixed duration.  It appears that vine videos are 6.5 seconds long.  Whatever the expected length is, that is what should be exported. Comments?

**Comment by wafels** [comment]
Perhaps given as an extra download option when the video comes uP?

**Comment by ddialer** [comment]
Added option to convert mp4 movies to animated GIF images. But for now it will stay as undocumented functionality and will not be available on production server due to movie length and size of final GIF image.

**Comment by ehsteve** [comment]
I would love this as well. When will this be available?

**Comment by wafels** [comment]
Do you have a use case?  I thought this might be useful because animated gifs are popular.

**Comment by ehsteve** [comment]
@wafels much easier to add to presentations than movies.

**Comment by wafels** [comment]
Ok.  The original concept was to make fixed duration movies, with the vine duration as a guide.  Providing gifs needs a little more thought on our side to allow us to make animated gifs of a reasonable size in a reasonable amount of time.   When we tried making gifs of normal-looking hv movies they ended up being hundreds of megabytes in size, many times the size of the original movies.

**Comment by ddialer** [comment]
I may be have solution for GIF generation. We can use online service for GIF generation like http://imgur.com/vidgif.

For example: http://imgur.com/vidgif/video?url=http%3A%2F%2Fapi.helioviewer.org%2F%3Faction%3DplayMovie%26id%3D7Qkd5%26format%3Dmp4%26hq%3Dtrue

**Comment by wafels** [comment]
So, we would have to create the video first using hv.org, and then perhaps a link in the player next to the other ones which would push the movie to imgur?  @ehsteve, would that work for you?  

The link you sent also allows you to share movies on imgur, and that might be a good thing too, although we really just want the video to gif conversion functionality.  You are not obliged to upload your movie to imgur.

![screen shot 2016-04-08 at 2 35 44 pm](https://cloud.githubusercontent.com/assets/983575/14393887/46bb928a-fd97-11e5-9112-c913181dc532.png)

**Comment by wafels** [comment]
That link you sent also allows you to share movies on imgur, and that might be a good thing too.

**Comment by ddialer** [comment]
Added new button "Create GIF". Button will open new tab with Imgur service with already pre-filled video url

**Comment by wafels** [comment]
Tried it and it works.  Great!  Confirmed.

**Comment by ehsteve** [comment]
Where can I try this?

**Comment by wafels** [comment]
We've been rolling out a lot of tweaks to helioviewer, but with little fanfare as yet.  I plan to advertise them once we start work on 3.1.

But to get to the gif export, reload helioviewer.org (command-r). Make a movie as normal, and at the
bottom of the player window there is a an export to gif option.  Let me know what you think.
