### ISSUE TITLE
Could not take a screen shot

### ISSUE THREAD

**Issue by dgrass23** [Helioviewer-Project/helioviewer.org#626]
I was trying to take a screen shot and got a an error message that stated unable to create screenshot

![Screenshot 2024-09-29 125606](https://github.com/user-attachments/assets/1b02558f-a559-4282-bda9-9bac0c880996)

**Comment by dgarciabriseno** [comment]
Thanks for the report.
I was able to debug and find the problem and I'll have a patch out for it soon.

If you uncheck all events (Coronal Hole here), then the screenshot will work.
If you change to a different day also, then the screenshot most likely will work.

**Comment by dgarciabriseno** [comment]
I just deployed version 4.4.3 which includes this fix.
