### ISSUE TITLE
AIA 171 images look really bad

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#63]
Something is going on with the AIA 171 images - the screenshots look terrible.  See the attached screenshots.  I think also other images are affected also, but it is not as obvious when you look at those.
![screen shot 2016-02-29 at 10 58 13 am](https://cloud.githubusercontent.com/assets/983575/13399975/aadc6042-ded3-11e5-862b-7099d6dfd3fd.png)
![2016_02_28_23_59_46_aia_171](https://cloud.githubusercontent.com/assets/983575/13399980/af5477c2-ded3-11e5-8325-1aeeb03f050c.png)
![2016_02_28_23_59_46_aia_171 1](https://cloud.githubusercontent.com/assets/983575/13400016/d28c5c6e-ded3-11e5-8219-1337161334b0.png)

**Comment by ddialer** [comment]
fixed

**Comment by dmueller3000** [comment]
I believe I see a similar effect when embedding a helioviewer.org window: http://www.cosmos.esa.int/web/solar-orbiter/home

**Comment by wafels** [comment]
The fix was pushed to the 3.0beta branch.  @ddialer , could you backport this to helioviewer 2.4?  Thanks!

**Comment by ddialer** [comment]
done

**Comment by wafels** [comment]
Confirmed as fixed.
