### ISSUE TITLE
Pop-up summary window does not disappear sometimes.

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#64]
Occasionally, the pop-up window for the screenshot does not disappear after the mouse has left the area that activates it.  The window remains up.  See attached screenshot.

![screen shot 2016-03-01 at 2 22 53 pm](https://cloud.githubusercontent.com/assets/983575/13438959/564f44ea-dfb9-11e5-8ff4-9bc8bc513b85.png)

**Comment by ddialer** [comment]
I updated jQuery qTip plugin from v2.0.0pre to 2.2.1. There was many fixes applied to the plugin and few of them was responsible for fixing not closing tooltip windows

**Comment by wafels** [comment]
Looks good!
