### ISSUE TITLE
News and announcements - how to notify?

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#65]
How do we notify users of news and announcements?

In Helioviewer 2.4, this is easy, since the user always sees the last 3 news items, and so the recent one shows up.  However, in Helioviewer 3.0, we have put news and announcements behind a tab.  So how do we let users know that a new news/announcement item is available?

**Comment by ddialer** [comment]
Added notification icon if new news is available.
<img width="46" alt="screen shot 2016-03-07 at 2 27 40 pm" src="https://cloud.githubusercontent.com/assets/403007/13580556/dd5db6f4-e470-11e5-8692-41420ac2c35e.png">

**Comment by wafels** [comment]
Solution works!  Confirmed.
