### ISSUE TITLE
YouTube movie list not updating

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#66]
The list of thumbnail movies is not being updated.  Perhaps this will happen when we switch over to hv 2.4 to hv 3.0?

**Comment by ddialer** [comment]
The YouTube list is working, but you have to upload movie thru beta web site. Right now v2.4 and v3.0 is using separate databases and when we switch to v3.0 all links to YouTube movies will be transfered as well

**Comment by wafels** [comment]
Thanks!

**Comment by wafels** [comment]
Movie queue is updating, so closing
