### ISSUE TITLE
Making a movie and accessing other Helioviewer functions require an extra click

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#67]
When you click on the Movie icon, you get a pop-up that says "Generate a Movie".  Then you have to click to open that.  This is one extra click compared to helioviewer 2.4, and is completely unnecessary.  When clicking the Movie icon, the movie making capability should just open up.

Note that the same issue also affects the Screenshot, YouTube, news/announcements and help capabilities.

**Comment by ddialer** [comment]
Fixed.

**Comment by wafels** [comment]
Confirmed.
