### ISSUE TITLE
Deprecate SunPy data download script.

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#68]
See #51 . The capability to generate SunPy data download scripts should not be available on helioviewer.org, pending stable SunPy code.  This removes the generation of SunPy data download scripts as a blocking issue to the release of helioviewer 3.0

**Comment by ddialer** [comment]
Done.

**Comment by wafels** [comment]
Confirmed

**Comment by wafels** [comment]
SunPy's data download functionality is now stable.  This functionality should now be implemented.
