### ISSUE TITLE
SMART active regions are mislabeled

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#69]
SolarMonitor Active Region Tracker labels are mislabeled in helioviewer 3.0:

The pin label should be limited to SMART plus the frm_specificid.  See the attached screenshot for the faulty view.
![screen shot 2016-03-01 at 5 40 02 pm](https://cloud.githubusercontent.com/assets/983575/13444942/5429dea0-dfd7-11e5-8764-c84f16c07dc9.png)

Link:

http://beta3.helioviewer.org/?date=2000-03-02T10:15:07.000Z&imageScale=2.42044088&centerX=-0.5244485549316407&centerY=0.5244485549316407&imageLayers=%5BSOHO,EIT,171,1,100%5D,%5BSOHO,EIT,304,1,19%5D,%5BSOHO,LASCO,C2,white-light,1,100%5D&eventLayers=%5BAR,all,1%5D,%5BCC,all,1%5D,%5BCD,all,1%5D,%5BCH,all,1%5D,%5BCJ,all,1%5D,%5BCE,all,1%5D,%5BCR,all,1%5D,%5BCW,all,1%5D,%5BEF,all,1%5D,%5BER,all,1%5D,%5BFI,all,1%5D,%5BFA,all,1%5D,%5BFE,all,1%5D,%5BFL,all,1%5D,%5BLP,all,1%5D,%5BOS,all,1%5D,%5BPG,all,1%5D,%5BSG,all,1%5D,%5BSP,all,1%5D,%5BSS,all,1%5D&eventLabels=true

**Comment by ddialer** [comment]
Fixed

**Comment by wafels** [comment]
Confirmed.

**Comment by wafels** [comment]
This appears to be happening again - see attached screenshot.

![screen shot 2016-04-05 at 3 23 31 pm](https://cloud.githubusercontent.com/assets/983575/14295178/8aa285b4-fb42-11e5-8872-1340f3660953.png)

Probably related to this is the re-appearance of #70.

![2003_10_31_01_41_43_eit_171](https://cloud.githubusercontent.com/assets/983575/14295279/00e1463e-fb43-11e5-8558-40d138a42ad0.png)

**Comment by ddialer** [comment]
Fixed. 
There two fixes related to this issue. First is that old names for SMART events was cached on the server. This resolved by deleting cache files with SMART events and system will recreate it automatically. The second issue is on API side. Some of the events name contains punctuation brackets, and javascript/php automatically added slashes to the string to escape special characters. Solution was is to strip slashes from events string.

**Comment by wafels** [comment]
Confirmed as fixed by checking out two random times that have SMART detections.
