### ISSUE TITLE
Screenshots of EIT images with SMART detections do not reproduce what is on screen.

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#70]
The screenshot function applied to the link below does not reproduce what is in the viewport.  Also, the wavelengths of the EIT images have not been transferred to the screenshot.

http://beta3.helioviewer.org/?date=2000-03-02T10:15:07.000Z&imageScale=2.42044088&centerX=-0.5244485549316407&centerY=0.5244485549316407&imageLayers=%5BSOHO,EIT,171,1,100%5D,%5BSOHO,EIT,304,1,19%5D,%5BSOHO,LASCO,C2,white-light,1,100%5D&eventLayers=%5BAR,all,1%5D,%5BCC,all,1%5D,%5BCD,all,1%5D,%5BCH,all,1%5D,%5BCJ,all,1%5D,%5BCE,all,1%5D,%5BCR,all,1%5D,%5BCW,all,1%5D,%5BEF,all,1%5D,%5BER,all,1%5D,%5BFI,all,1%5D,%5BFA,all,1%5D,%5BFE,all,1%5D,%5BFL,all,1%5D,%5BLP,all,1%5D,%5BOS,all,1%5D,%5BPG,all,1%5D,%5BSG,all,1%5D,%5BSP,all,1%5D,%5BSS,all,1%5D&eventLabels=true

**Comment by ddialer** [comment]
Fixed

**Comment by wafels** [comment]
The wavelengths of the EIT images are not in the downloaded screenshot.  They should be in the screenshot.

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed.
