### ISSUE TITLE
SDO cutout has incorrect end date

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#72]
The first screenshot shows the requested start and end times for the SDO Cutout website.  The second screenshot shows that the requested helioviewer start time has been set as the SDO cutout end time.  The helioviewer start and end times should be passed in to the start and end times of the SDO cutout website.
![screen shot 2016-03-08 at 10 30 02 am](https://cloud.githubusercontent.com/assets/983575/13606287/79f588fe-e519-11e5-894c-799d750337e2.png)
![screen shot 2016-03-08 at 10 30 33 am](https://cloud.githubusercontent.com/assets/983575/13606294/83465960-e519-11e5-89cf-68ed635b3771.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed.
