### ISSUE TITLE
Start and end date in science data function update when view moves

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#73]
Moving the viewport, or changing the image data viewed, changes the start and end date in the science data function.  This is annoying since a user might want to get data at slightly different positions or from different measurements without changing the time range of the data request.  The start and end date should only change when the observation date changes.

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
The bug in the title is fixed, but the other one described in the text - changing the measurement resets the time - is still present.
There is a question issue though, because swapping to a new measurement will almost certainly mean that a new time is introduced.  What to do then?

I'm going to split this issue in two and mark this one as closed.
