### ISSUE TITLE
Timeline should push other open drop-down windows up

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#76]
When the timeline is popped up, it should not cover up any open drop-down windows.  Those windows should slide to accommodate the timeline.  Also, if the timeline is already open, then when a drop down window is open, it should have a length so that it does not cover the timeline.

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
looks like this has not been uploaded to the main beta3.

**Comment by ddialer** [comment]
done. forgot to push it to the main beta3 at first time

**Comment by wafels** [comment]
confirmed
