### ISSUE TITLE
Simplifying functionality names

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#77]
For some consistency with helioviewer 2.4, I think some of the functionality names on the left hand side should be changed/simplified.  So please change "Feature and Event Annotations" to "Features and Events", and change "Image data layers" to "Images".

**Comment by ddialer** [comment]
done

**Comment by wafels** [comment]
Should be "Features and Events" instead of the current "Feature & Events". Thanks!

**Comment by ddialer** [comment]
corrected

**Comment by wafels** [comment]
confirmed
