### ISSUE TITLE
Scrolling on macbooks with touchpad is too fast

### ISSUE THREAD

**Issue by ddialer** [Helioviewer-Project/helioviewer.org#78]
When scrolling, Zooming with touchpad on mac books scroll is happen too fast. 

Possible solution is to update jQuery MouseWheel plugin: https://github.com/jquery/jquery-mousewheel.
Current Version 3.0.6, New version available: 3.1.13

More information about the issue:
https://github.com/jquery/jquery-mousewheel/issues/36

**Comment by ddialer** [comment]
Fixed

**Comment by wafels** [comment]
The month and year selector is still a little fast.  Can that be slowed down to the pace of the hour/minute/second selector?

**Comment by ddialer** [comment]
calendar selectors fixed

**Comment by wafels** [comment]
confirmed as fixed.
