### ISSUE TITLE
Remove unnecessary rounded boxes in Help and Sharing functions

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#79]
The Help and Sharing functions have unnecessary rounded boxes around the various options.  These are visually distracting and should be removed - see attached screenshots.  The highlighting function is good though.  Also, the layout of the "Share to Social Networks" menu is different from the Help menu.  Both should conform to the simpler style of the Help menu.

![screen shot 2016-03-24 at 11 35 10 am](https://cloud.githubusercontent.com/assets/983575/14022354/d3a10dc6-f1b5-11e5-9322-9a6364d328e2.png)

![screen shot 2016-03-24 at 11 38 34 am](https://cloud.githubusercontent.com/assets/983575/14022320/a5c2771e-f1b5-11e5-9328-b12186be8f5f.png)

**Comment by ddialer** [comment]
New Style:
![hv-drawer-help-3 0](https://cloud.githubusercontent.com/assets/403007/14024614/5735a03e-f1c0-11e5-9537-ad6374cccb8e.png)
![hv-drawer-share-3 0](https://cloud.githubusercontent.com/assets/403007/14024615/57373020-f1c0-11e5-92ec-e2d1c8948979.png)

**Comment by wafels** [comment]
Looks better!
