### ISSUE TITLE
Timeline: zoomed out view sometimes leads to histogram bars that don't span the time range

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#80]
When zoomed out so that each histogram bin is approximately a month, sometimes the end time of the previous bin does not match up with the start time of the next bin.  Since the times are wrong, this seems to leave space between one histogram bar and the next.  Hence the histogram does not span the entire range

For example, this bin ends at 2013/05/29 00:00:00 UTC

![screen shot 2016-03-25 at 11 23 18 am](https://cloud.githubusercontent.com/assets/983575/14047154/64d7ab3a-f27c-11e5-8155-fcda7e988a23.png)

but the neighboring bin begins at 2013/06/01 00:00:00 UTC, leaving a gap of two days.

![screen shot 2016-03-25 at 11 23 47 am](https://cloud.githubusercontent.com/assets/983575/14047177/83b118a2-f27c-11e5-8e24-ac3ce07e85eb.png)

At other times, the end of one bin matches up with the start of the next - this is the expected behavior.

![screen shot 2016-03-25 at 11 23 59 am](https://cloud.githubusercontent.com/assets/983575/14047201/d775a02a-f27c-11e5-986b-131d296886b3.png)
![screen shot 2016-03-25 at 11 24 10 am](https://cloud.githubusercontent.com/assets/983575/14047203/d9db41bc-f27c-11e5-8bf3-8b9c9daa72ea.png)

**Comment by ddialer** [comment]
Fixed

**Comment by wafels** [comment]
confirmed as fixed.
