### ISSUE TITLE
Image display can exhibit unexpected behavior on Chrome browser under OS X

### ISSUE THREAD

**Issue by dmueller3000** [Helioviewer-Project/helioviewer.org#81]
![image](https://cloud.githubusercontent.com/assets/9073862/14119355/12000bf8-f5ee-11e5-82c8-dbd032cb66f9.png)

**Comment by wafels** [comment]
This should be fixed.  Please reload, and let us know if there is still an issue.

**Comment by wafels** [comment]
Seems to be fixed on Chrome on OS X (tested on my macbook air).  No other reports, so closing.
