### ISSUE TITLE
With Firefox (v43.0.4) on OS X, deleting multiple layers requires additional click

### ISSUE THREAD

**Issue by dmueller3000** [Helioviewer-Project/helioviewer.org#82]
Say you have 5 layers loaded and want to remove 4 of them. When I click on the 'remove' button of one of them, a vertical scroll bar appears on top of the other remove buttons and prohibits me from closing more layers. It disappears when I click anywhere on the page. I do not see this behavior with Chrome.

**Comment by wafels** [comment]
This might have something to do with how Firefox handles vertical scroll bars compared to Chrome.  This is an usability issue.  Will investigate to see if this is something we can control.

**Comment by ddialer** [comment]
can you please confirm that this issue is still present. I tried in many different browsers including FF v43.0.4  and can't reproduce this issue.

**Comment by ddialer** [comment]
This issue related to the Mac OS. Safari, Firefox and Chrome using system scrollbars that appearing automatically when user scroll or change content. This is also can be changed to always show scroll bar as described here: https://support.mozilla.org/en-US/questions/979836

As are simple solution I can move buttons for about 15px from the right side to leave space for the scrollbar. Below you can see two screenshots that show two layers. First layers buttons is moved 15px from right and second is staying in original position.

Without scrollbar:
<img width="326" alt="screen shot 2016-03-31 at 5 11 11 pm" src="https://cloud.githubusercontent.com/assets/403007/14191400/b0f68a70-f765-11e5-9507-59370699dffd.png">

With scrollbar:
<img width="326" alt="screen shot 2016-03-31 at 5 11 25 pm" src="https://cloud.githubusercontent.com/assets/403007/14191405/bae0b1fa-f765-11e5-9f80-487ee6992f78.png">

Should I move there Icons?

**Comment by wafels** [comment]
Let's try moving the icons. Thanks,

**Comment by wafels** [comment]
@ddialer also found that the scroll bar behavior can be changed in OS X by going to System Preferences > General.  In OS X 10.10.5, switching the scroll bar show preferences to "Always" removes this issue.

Since the scroll bar behavior is something we can't control easily in the web application, the solution is to move the icons so that they are never hidden by the scroll bar.

**Comment by ddialer** [comment]
Icons has been moved from the right side for 15px

**Comment by dmueller3000** [comment]
Great & looks good - thanks a lot!

Daniel

**Comment by wafels** [comment]
confirmed as fixed - closed.
