### ISSUE TITLE
Timeline: thumbnail view

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#84]
Perhaps the image timeline could show a thumbnail view of the viewport at the time where the cursor is.  This would help the user pick a time of interest.

**Comment by wafels** [comment]
This would probably trigger a lot of events, and so there would be a lot of calls to the thumbnail generation.  Perhaps this could be initially implemented at the very lowest level of the image time line when each selected image type has its own horizontal level and the image observation times appear separately.  So when resting on an AIA 171 time, an thumbnail of the AIA 171 image at that time is generated.

At longer time scales, the current viewport should be reproduced in thumbnail form.  As was suggested by @ddialer, the midpoint time for a given time bin is one option for a thumbnail.  Another option is to show the current viewport reproduced at the start and end times of the time bin.  Using this, the user may get a better idea of the change in the images at one end of the time bin compared to the other.

**Comment by ddialer** [comment]
Done. Timeline tooltips now have preview images

**Comment by wafels** [comment]
Looks like the preview images are not fully picking up the opacity.  I went down to the single point view of the time line and then back up, and noticed that the preview images were not fully picking up the opacity.

![screen shot 2016-04-01 at 4 56 59 pm](https://cloud.githubusercontent.com/assets/983575/14219910/dd5beee6-f82a-11e5-85f3-7198482f4583.png)

**Comment by ddialer** [comment]
issue related to the #90. It is already fixed

**Comment by wafels** [comment]
confirmed.
