### ISSUE TITLE
Feature and event timeline

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#85]
It would be useful for users to be able to view features and events as a function of time.  This will allow users to browse data using features and events, and to select data based on those features and events.

This is a major new feature, and will require some design.

Initially, the design could be based on the existing image time line.  At longer time scales, users are shown a histogram of the number of events in the time range.  Events will fall across histogram time bins.  Any time an event falls in to a time bin, that should count as one event in that time bin.  The histogram should be split in to feature/event (F/E) and feature recognition method (FRM).  Every F/E + FRM combination counts as one class to be counted in the histogram view.  As in the image timeline, hovering over a histogram bin will pop up a window that has the time range spanned by the time bin and the number of events in each F/E + FRM combination.

At shorter time scales, the view switches so that users are shown the duration of individual events.  This would be represented by horizontal lines of the required length.  Hovering over a horizontal line would show the same information as the feature/event pop up windows in main view port.  Horizontal lines should be grouped by F/E + FRM combination, and additionally by FRM_identifier.

Features and events will come initially from the HEK.  However, the timeline should be built a little more generally so it can accept features and events from anywhere that are specified by F/E, FRM, FRM_identifier, start time and end time.

**Comment by wafels** [comment]
The timeline shows that there is an active region on the Sun but there is not one displayed in the viewer window - see attached.
![screen shot 2016-06-08 at 8 35 30 am](https://cloud.githubusercontent.com/assets/983575/15894558/809ffbe8-2d54-11e6-8b07-f49953dbb064.png)

**Comment by wafels** [comment]
The flare peak time is not shown in the event tooltip - see attached.
![screen shot 2016-06-08 at 8 35 14 am](https://cloud.githubusercontent.com/assets/983575/15894585/9edb544a-2d54-11e6-9c91-238817052d9f.png)

**Comment by wafels** [comment]
Emerging flux peak time is not shown - see attached.  Area at disk center not formatted correctly - looks like the +/- signs are not being rendered.
![screen shot 2016-06-08 at 8 44 22 am](https://cloud.githubusercontent.com/assets/983575/15894694/4faaa0be-2d55-11e6-816d-3dcb8e14c954.png)

**Comment by wafels** [comment]
Are there really over 400 active region events on the 2016/05/26?  How are these numbers calculated?  I think the way these should be calculated is by counting the number of active regions that overlap even partially with the time range 2016/05/26 00:00:00 - 2016/05/27 00:00:00.

![screen shot 2016-06-10 at 6 44 09 am](https://cloud.githubusercontent.com/assets/983575/15962099/c513b1ec-2ed6-11e6-86c3-233d1aaa7d27.png)

**Comment by ddialer** [comment]
For the events that are not shown on the main viewport, there wasn't an issue.  It's just events timeline and main viewport were using different sources of events. Events timeline were used database storage, and the main viewport is old file storage.

I fixed it yesterday, so both timeline and viewport now using database storage.

**Comment by ddialer** [comment]
You are right. There only about 52 active regions was on 2016/05/26. There is a miscalculation in 'events_coverage_30_min' table.  That table has information about the number of the events in each 30-minute spans and is used to speed up the event timeline navigation. So one event can be in multiple spans, and can sum up to a bigger number if need to display in longer time spans than 30 minutes. 

So I need to reorganize how 'events_coverage_30_min' works or make timeline count events on the fly right from 'Events' table.

**Comment by ddialer** [comment]
Compleated and released in v3.1
