### ISSUE TITLE
Feature/event pop up window to allow "copy times to data download"

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#86]
A nice feature to have might be the ability to automatically transfer the start / end time combination for a feature event to the data download functionality.  This would allow users to quickly specify the data they want to download.  This could be provided as a link underneath the "View HEK data" button in the pop-up window.

![screen shot 2016-03-30 at 9 19 39 am](https://cloud.githubusercontent.com/assets/983575/14143549/dbb2b8b8-f659-11e5-9852-ece0132ed2d9.png)

**Comment by ddialer** [comment]
Added "Copy times to data download" button. When user click on the button it will insert start and end dates into VSO and SDO inputs. If currently "Data download" sidebar is closed it will open sidebar first.

<img width="360" alt="screen shot 2016-04-05 at 1 13 06 pm" src="https://cloud.githubusercontent.com/assets/403007/14291200/6b6f7f10-fb30-11e5-89ad-16bc9c8af347.png">

**Comment by wafels** [comment]
implemented!  Opening the data download sidebar is a nice touch.

**Comment by wafels** [comment]
SDO cutout service link does not pick up the copied times.

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
Fixed.

Could you change the text to "Copy start / end times to data download" ?  Thanks.

**Comment by ddialer** [comment]
Done.

**Comment by wafels** [comment]
thanks!
