### ISSUE TITLE
Allow for running difference images to be shown

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#87]
Running difference images are very useful for tracking the changes in the evolution of the solar atmosphere.  There should be an option to display running difference images in helioviewer.org.  The color table for all running difference images should be a grey scale color table.

**Comment by wafels** [comment]
Needs some more experimentation, and comparison with JHelioviewer.  Will need a new color table too.

**Comment by bogdanni** [comment]
See https://github.com/Helioviewer-Project/JHelioviewer-SWHV/blob/master/resources/data/fragmentcommon.glsl#L42 till L44

**Comment by wafels** [comment]
When a layer is running difference, or in base difference, this information must be added to the layer identification on the lower left hand side. Say the user makes a running difference image based using images from 60 minutes previously: this could be indicated as

AIA 171 2011-06-07 06:34:56 [RD 60 minutes]

For a base difference layer you could have

AIA 171 2011-06-07 06:34:56 [BD  2011-06-07 06:15:00]

A normal, non-differenced image does not have to have anything else added.

**Comment by wafels** [comment]
When switching to base difference, the default base difference time should be 60 minutes before the current observation time.

**Comment by wafels** [comment]
When switching to running difference, the default difference should be 60 minutes

**Comment by ddialer** [comment]
Image difference functionality compleated and can be tested on beta site.
