### ISSUE TITLE
Link to VSO finds no data under certain circumstances

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#88]
I tried the VSO website button for the following selection

![screen shot 2016-03-31 at 10 36 50 am](https://cloud.githubusercontent.com/assets/983575/14179284/8ee837dc-f72c-11e5-804d-428c34eb9c6f.png)

No data was returned.  This is because the start minute is the same as the end minute, and so is another version a bug #50 that was seen and squashed earlier.  The solution is to always span at least one minute when calling the VSO.

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed as fixed
