### ISSUE TITLE
Link to SDO cutout service finds no data under certain circumstances.

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#89]
Same as #50 and #88 .  The SDO cutout service accepts time specification up to the minute level.  So when the start and end time have the same minute number (and year month day hour for the start and the end times are the same) then no data is returned.  The solution is to ensure that at least one minute is spanned.

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed as fixed
