### ISSUE TITLE
NOAA active regions linked to ADS and arXiv literature search

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#92]
ADS (adswww.harvard.edu) and arXiv (arXiv.org) are two large repositories of scientific literature that are searchable.

It would be very useful to have NOAA active region pop-up windows show a link called "ADS Search" (with an arrow to indicate that the user is leaving helioviewer.org).  This would link to the ADS Bumblebee search interface.  For example,  searching for NOAA 10486 on ADS via

https://ui.adsabs.harvard.edu/#search/q=%22NOAA%2010486%22&sort=date%20desc

returns over 100 references.  For arxiv, the link would be "arXiv search"

http://search.arxiv.org:8081/?query=NOAA+10486&in=

NOAA active region numbers are among the most commonly used feature identifiers in solar physics, and appear in many papers.  This capability would connect what users are looking at in Helioviewer.org directly to the scientific literature.

**Comment by ddialer** [comment]
Added ADS and arXiv search
<img width="436" alt="screen shot 2016-04-06 at 2 21 56 pm" src="https://cloud.githubusercontent.com/assets/403007/14328039/050cd9f6-fc03-11e5-8e72-5340b248e747.png">

**Comment by wafels** [comment]
Looks good.  I randomly selected an active region from a couple of years ago, and clicked on both links.  ADS showed nothing, but I found a couple of articles on arXiv.  Neat!

Just one thing to add - could you put one of those arrow symbols beside the ADS search and the arXiv search to indicate that the user will be sent away from helioviewer.org ?  Thanks!

**Comment by wafels** [comment]
Could you also change the ADS search call to

https://ui.adsabs.harvard.edu/#search/q=full%3ANOAA%20AND%20full%3A10486&sort=date%20desc

This format seems to give more comprehensive results

Also, please change the text to

ADS search for NOAA 12319
arXiv search for NOAA 12319

Thanks!

**Comment by ddialer** [comment]
Done.
1. Fixed appearance of external link icon
2. Changed labels to show event name
3. Changed search query for ADS

**Comment by wafels** [comment]
One small changes: the word "search" in the text describing the ADS search should not be capitalized.

And I do apologize, I think the original search term "NOAA ?????" was probably the better search term as this is less likely to come up with false positives.  Sorry about that.

**Comment by ddialer** [comment]
Done

**Comment by wafels** [comment]
Looks like the ADS search term is still using the AND format.  Could you change back to using the original format

https://ui.adsabs.harvard.edu/#search/q=%22NOAA%2010486%22&sort=date%20desc

I think a search with fewer false positives is better.

**Comment by wafels** [comment]
confirmed as fixed.
