### ISSUE TITLE
Make movie link in Feature/Event pop-up windows

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#93]
Would it be possible to kick off the movie generation process from the feature/event pop-up windows?  The link would say something like "Make movie using event times and current field of view".  This would kick off the movie generation process using the start/end times of the feature/event and use the current viewport field of view.

**Comment by ddialer** [comment]
Added New button to generate movie based on event start and end times
<img width="352" alt="screen shot 2016-04-19 at 11 56 58 am" src="https://cloud.githubusercontent.com/assets/403007/14646014/eb21f0e4-0625-11e6-86ef-017b34993b5c.png">

**Comment by wafels** [comment]
Doesn't seem to be uploaded yet.

**Comment by wafels** [comment]
confirmed
