### ISSUE TITLE
Initial load on Safari does not display the Sun

### ISSUE THREAD

**Issue by ehsteve** [Helioviewer-Project/helioviewer.org#94]
Using Safari, when I first arrived at the page everything was being displayed properly except for the solar image and the x and y position values were not updating and just displayed `--`. When I forced a reload the problem was fixed and opening the page again, the problem did not seem to occur. This problem was confirmed by @wafels.

**Comment by ddialer** [comment]
Fixed.
Added modified date timestamp to JS and CSS helioviewer files to make sure it always load the latest versions

**Comment by wafels** [comment]
confirmed
