### ISSUE TITLE
Highlight and copy text always gives a link to state of Helioviewer

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#96]
Sometimes you just want to copy a piece of text that appears in Helioviewer.  For example, this could be a link appearing in the HEK "view data" window.  Highlighting the piece of text and applying the copy function (command-C on a Mac) does not copy the text, but instead generates a link to the current state of Helioviewer, which is obviously not what the user intended.

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed
