### ISSUE TITLE
First ever warning from Bitly

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#97]
We've used Bitly over 5,000 times this month, which has triggered a warning from Bitly.  At the moment, we can create 10,000 shortened links per month for free.  The warning also states that the number of free Bitly links will shrink to 5,000 per month.  So there may be a problem coming up.  I have to wonder why we seem to be generating that many more Bitly links now than previously - is this feature more popular now, or is there a bug?

**Comment by ddialer** [comment]
I made some optimization for Bitly request. Previously helioviewer was making bitly request on: page refresh, open share tab and close share tab. I removed api request for page reload and close share sidebar. This should reduce api usage by around 3 times or even more.

**Comment by wafels** [comment]
Ok, going to mark as closed.
