### ISSUE TITLE
Timeline did not update when going from SDO/AIA to SOHO/EIT

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#98]
I had an SDO AIA 131 image of the sun up, and then I changed to SOHO EIT in April 2003.  As can be seen by the attached screen shot, the timeline has not updated.

![screen shot 2016-04-08 at 11 39 58 am](https://cloud.githubusercontent.com/assets/983575/14389152/4b87a424-fd7f-11e5-9694-eff186573f9b.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed
