### ISSUE TITLE
Timeline loses data when image layer opacity is at zero

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#99]
When the opacity of a layer is set to zero, it disappears from the timeline.  Even although the layer is completely invisible, it is still selected, and I would expect to see it still counted in the timeline

Both layers have non-zero opacity:

![screen shot 2016-04-08 at 1 41 08 pm](https://cloud.githubusercontent.com/assets/983575/14392502/a45e0844-fd8f-11e5-871c-2578c604f74f.png)

Then when I minimize the opacity of the top layer:

![screen shot 2016-04-08 at 1 40 32 pm](https://cloud.githubusercontent.com/assets/983575/14392568/f0a6742a-fd8f-11e5-9e56-34ed2c8aca6a.png)

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed
